### ISSUE TITLE
Timed out connections are staying busy

### ISSUE THREAD

**Issue by junaidriaz** [oracle/odpi#101]
Hi
I have one question about timed out connections. My scenario is following:

I have set timeout of connection using **dpiConn_setCallTimeout**. Timeout is getting fired with following message _**DPI-1067**: call timeout of 100 ms exceeded with ORA-3136 (dpiStmt_execute: execute)_. Then that connection is released using **dpiConn_release** but still being shown as busy when get count using **dpiPool_getBusyCount**.  This is leading to _**ORA-24418**: Cannot open further sessions. (dpiPool_acquireConnection: get session)_ when more connections are being timed out and busy count reached poolCreateParams.maxSessions. Is this intended behaviour ?

I am asking because in documentation it says that connection is useable if DPI-1067 is returned.

>After a timeout is triggered, ODPI-C attempts to clean up the internal connection state. The cleanup is allowed to take another value milliseconds.
If the cleanup was successful, an exception **DPI-1067 will be raised but the application can continue to use the connection**.
For small values of call timeout, the connection cleanup may not complete successfully within the additional call timeout period. **In this case an exception ORA-3114 is raised and the connection will no longer be usable. It should be closed**.

#### Enviroment Information:
ODPI-C = 3.1.2
Oracle Instant Client: 18.3

**Comment by anthony-tuininga** [comment]
Do you have some code that demonstrates the issue?

**Comment by junaidriaz** [comment]
> Do you have some code that demonstrates the issue?

Yes, please check sample test case [here](https://gist.github.com/junaidriaz/26afe615610430b0d05cfde5816c8f42#file-odpi_timeout_test-c). 
Detailed output is [here](https://gist.github.com/junaidriaz/0e2057e5e5e0a7cd829a0e2cbf2cfaa3#file-odpi_timeout_test_output-txt)

**Comment by anthony-tuininga** [comment]
I took a look at your code. You're not closing the connection (releasing it back to the pool) which is why the busy count is increasing. If you close the connection by calling dpiConn_close() then the busy count stays at 0.

**Comment by junaidriaz** [comment]
Connection is being released back to pool at line [248](https://gist.github.com/junaidriaz/26afe615610430b0d05cfde5816c8f42#file-odpi_timeout_test-c-L248). 
As per documentation, **connection is useable after DPI-1067 is received, then why I have to close** the connection.

If I close connection using dpiConn_close(), open count is decreasing which means connection is not being returned to pool. When there are more timeouts coming, it can reduce open connections to zero and overhead of opening new connection will cause additional performance impact.

**Comment by anthony-tuininga** [comment]
> > You're not closing the connection (releasing it back to the pool) which is why the busy count is increasing.

> Connection is being released back to pool at line 248.

You are calling dpiConn_release() which is releasing a **reference** to the connection. This reduces the reference count and only if the reference count reaches zero does the connection get released back to the pool.

>  As per documentation, connection is useable after DPI-1067 is received, then why I have to close the connection.

Yes, you could reuse the connection by executing a second statement. You're not doing that in your example but you could. When you are finished with it you either need to call dpiConn_close() or make sure that all references to the connection have been released. Keep in mind that statements, variables, LOBs and other objects all hold internal references to the connection as well -- so you need to make sure that all objects referencing the connection have themselves had their reference counts reduced to zero.

> > If you close the connection by calling dpiConn_close() then the busy count stays at 0.

> If I close the connection using dpiConn_close(), open count is decreasing as well which means connection is not being returned to pool in open state. When there are more timeouts coming, it can reduce open connections to zero and overhead of opening new connection will cause additional performance impact.

With your example, modified by calling dpiConn_close() in addition to dpiConn_release(), the open count remains at 10, the minimum number of sessions you requested in your pool. In other words, your example works perfectly with the addition of that code. You can add an additional statement execution after the timeout to verify that the connection is still usable.

**Comment by junaidriaz** [comment]
okay, thanks for your comments.
