### ISSUE TITLE
Not supported event type in CQN when shutdown and startup database

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#102]
I ran TestCQN under the sample directory. When I shutted down and started up the database, it printed `ERROR: DPI-1013: not supported (dpiSubscr__callback: event type)`.

Here is the output.
```
$ pwd
/home/kubo/odpi/samples
$ LD_LIBRARY_PATH=../lib ./build/TestCQN  # shutdown and startup the database in another terminal
Registered query with id 101

In another session, modify the results of the query

select * from TestTempTable

Use Ctrl-C to terminate or wait for 100 seconds
Waiting for notifications...
Waiting for notifications...
ERROR: DPI-1013: not supported (dpiSubscr__callback: event type)
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
ERROR: DPI-1013: not supported (dpiSubscr__callback: event type)
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Waiting for notifications...
Done.
```
The values of [`message->eventType`](https://github.com/oracle/odpi/blob/7466408906748e5556d8aed954421311db267f1d/src/dpiSubscr.c#L408) were 'DPI_EVENT_SHUTDOWN` and `DPI_EVENT_STARTUP` when DPI-1013 errors were reported.

The following code should be added just next of [this line](https://github.com/oracle/odpi/blob/7466408906748e5556d8aed954421311db267f1d/src/dpiSubscr.c#L417)
```c
        case DPI_EVENT_STARTUP:
        case DPI_EVENT_SHUTDOWN:
        case DPI_EVENT_SHUTDOWN_ANY:
            break;
```

ODPI-C version: The latest in the github repository.
Oracle version: Oracle 18.3
OS: Linux

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. That was helpful. I hadn't known how to generate those events so left them as unsupported. It clearly wan't that hard to generate those events after all! :-)

**Comment by kubo** [comment]
@anthony-tuininga Thanks. I confirmed that my unpublished rust-oracle driver caught shutdown and startup events.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. Since the constants were already there and the code change was minimal I decided to consider this a bug and will include it in the patch I am about to release.
