### ISSUE TITLE
dpiEventType document

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#103]
In this [ODPI-C documentation](https://oracle.github.io/odpi/doc/enums/dpiEventType.html), descriptions of `DPI_EVENT_SHUTDOWN` and `DPI_EVENT_SHUTDOWN_ANY` are both "Indicates that a database is being shut down."

On the other hand, in [Oracle manual](https://docs.oracle.com/en/database/oracle/oracle-database/18/adfns/cqn.html#GUID-635139E3-40F9-49E2-8C3C-605771FB07D6):

* 0x2 OCI_EVENT_SHUTDOWN - Instance shutdown
* 0x3 OCI_EVENT_SHUTDOWN_ANY - Any instance shutdown - Oracle Real Application Clusters (Oracle RAC)

@anthony-tuininga Could you change the description of `DPI_EVENT_SHUTDOWN_ANY`?

In the ODPI-C documentation, `DPI_EVENT_DROP_DB` has description. However Oracle manual doesn't say nothing about it. I'm afraid that OCI may not produce the event type in any cases.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. Good points. I've implemented both suggestions.
