### ISSUE TITLE
queueNameLength argument of dpiConn_deqObject and dpiConn_enqObject

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#104]
[`dpiConn_deqObject`][] and [`dpiConn_enqObject`][] functions have `queueNameLength` arguments. However they aren't used in the functions. The length of the `queueName` looks `strlen(queueName)`.
For example when `dpiConn_deqObject(conn, "BOOKSXX", 5, ...)` was executed, it tried to use "BOOKSXX"(length 7) instead of "BOOKS"(length 5) and got an error "ORA-24010: QUEUE ODPIC.BOOKSXX does not exist".

[`dpiConn_deqObject`]: https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_deqObject
[`dpiConn_enqObject`]: https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_enqObject

**Comment by anthony-tuininga** [comment]
Interesting! It looks like the underlying OCI routine doesn't accept the length and wants a null-terminated string. I'll look into that further and get back to you on the best solution.

**Comment by anthony-tuininga** [comment]
In order to support RAW queues as well as array enqueue/dequeue I have created a new method called dpiConn_newQueue() which accepts the name and does not suffer from the issue you reported. Please take a look and let me know if you have any feedback. Thanks!

**Comment by kubo** [comment]
Thanks! I have a comment about `dpiConn_newQueue()`.

In the [comments] of [`OCITypeByName()`], which is called to get the TDO of RAW:
> This function always makes a round-trip to the server. Therefore calling this function repeatedly to get the type can significantly reduce performance. To minimize the round-trips, the application can call the function for each type and cache the type objects.
>
> To free the type obtained by this function, call `OCIObjectUnpin()` or `OCIObjectPinCountReset()`. 

Could you cache the TDO of RAW in the connection? Otherwise could you free the TDO by `OCIObjectUnpin()` in `dpiQueue_release()`? I prefer the former but accept the latter because I guess that `dpiConn_newQueue()` will not be called repeatedly.

[`OCITypeByName()`]: https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/oci-type-information-accessor-functions.html#GUID-3534AABC-E347-4BC7-B220-0CAECDC9ECE7
[comments]: https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/oci-type-information-accessor-functions.html#GUID-3534AABC-E347-4BC7-B220-0CAECDC9ECE7__GUID-09F9EFEF-977D-40DC-94FB-EA25487F6879

**Comment by anthony-tuininga** [comment]
Thanks, @kubo, for bringing that comment about ``OCITypeByName()`` to my attention. I'll cache the TDO on the connection and also defer getting it until the first enqueue or dequeue takes place -- that way the creation of a queue is merely storing parameters and never involves a round trip.

**Comment by anthony-tuininga** [comment]
And I've just pushed the changes for this.
