### ISSUE TITLE
Python cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found"

### ISSUE THREAD

**Issue by arbn** [oracle/odpi#105]
Cannot connect to Database with simple connect script , it complains about the cannot locate 64bit oracle client library. 

1. What version of ODPI-C are you using (see dpi.h)? 
Version: 7.1.3

2. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
Installation went fine , but unable to connect.

3. What error(s) you are seeing?
cx_Oracle.DatabaseError: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

4. What OS (and version) is your application executing on?
Windows 10 , 64bit

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
Oracle Client 18.5 , 
Installed by Unzipping the package : http://download.oracle.com/otn/nt/instantclient/185000/instantclient-basiclite-windows.x64-18.5.0.0.0dbru.zip
Installed in this location:  C:\Oracle\instantclient_18_5

6. What is your Oracle Database version?
Oracle version 12.02

7. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?
Path=C:\Oracle\instantclient_18_5;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jre1.8.0_201\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Cisco\Cisco AnyConnect Secure Mobility Client\;C:\Program Files\PuTTY;C:\Program Files\BMC Software\ARSystem\dataimporttool;C:\Anaconda;C:\Anaconda\Library\mingw-w64\bin;C:\Anaconda\Library\usr\bin;C:\Anaconda\Library\bin;C:\Anaconda\Scripts;C:\Users\arbn\AppData\Local\Continuum\anaconda3;C:\Users\arbn\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:\Users\arbn\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Users\arbn\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\arbn\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\arbn\AppData\Local\Microsoft\WindowsApps;

8. What environment variables did you set?  How *exactly* did you set them?
On windows 10 , Started "System Environment Variables" , opened "Environment Variables" and opened Path on System Variables and added a New variable "C:\Oracle\instantclient_18_5", and moved it to the top.

9. What compiler version did you use?
Python 3.7.2

**Comment by cjbj** [comment]
What required VS Redistributable did you install? (see the error message link).

**Comment by arbn** [comment]
Microsoft Visual Studio 2013 Redistributable.

**Comment by cjbj** [comment]
All seems fine, so keep playing: maybe PATH isn't set appropriately at the time you are running Python?

**Comment by edelgadocru** [comment]
Hi, I have the same problem. Have you been able to solve it?

**Comment by cjbj** [comment]
@edelgadocru many people have solved it and are using cx_Oracle successfully.  Without knowing your configuration, no one can do more than point you at the [cx_Oracle installation instructions](https://cx-oracle.readthedocs.io/en/latest/installation.html).

If that doesn't help, please open an issue in the cx_Oracle repo: https://github.com/oracle/python-cx_Oracle/issues and include all useful details.

**Comment by cjbj** [comment]
Closing - no update from original filer
