### ISSUE TITLE
Query Oracle Data hang

### ISSUE THREAD

**Issue by gooker** [oracle/odpi#107]
**In my Program read Oracle table thread hang in a few days to a week,I think it may be related to network quality.
but I don't understand why it causes the thread hang.I have set  timeout...
Please help;**

### thread stack:

Thread 5 (Thread 0x7f83557d4700 (LWP 2236)):
#0  0x00007f8362f14c1d in read () from /lib64/libc.so.6
#1  0x00007f8361a4b144 in snttread () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#2  0x00007f8360072441 in nttrd () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#3  0x00007f835ff673e4 in nsprecv () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#4  0x00007f836003929c in nscon () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#5  0x00007f835ff23a82 in nsdo () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#6  0x00007f836002e06f in nsbasic_rc () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#7  0x00007f836002e0fb in nsrecv () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#8  0x00007f835ff1fdc1 in nscall3 () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#9  0x00007f835ff1d00e in nscall () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#10 0x00007f835ffba454 in niotns () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#11 0x00007f836004bce5 in nigcall () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#12 0x00007f835ffc556c in osncon () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#13 0x00007f835fe5774f in kpuadef () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#14 0x00007f835fe3329b in upiini () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#15 0x00007f835fe2b026 in upiah0 () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#16 0x00007f835fe50c19 in kpuatch () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#17 0x00007f835fe3745f in OCIServerAttach () from /usr/lib/oracle/11.2/client64/lib/libclntsh.so.11.1
#18 0x00007f835f768d75 in dpiOci__serverAttach (conn=conn@entry=0x7f8344063900, connectString=connectString@entry=0x9352b0 "172.16.251.120:1522/orcl!", connectStringLength=connectStringLength@entry=24, error=error@entry=0x7f83557d3ba0) at src/dpiOci.c:2535
#19 0x00007f835f751db3 in dpiConn__createStandalone (error=0x7f83557d3ba0, createParams=0x7f83557d3c00, commonParams=0x7f83557d3bc0, commonParams@entry=0x7f8300000018, connectStringLength=24, connectStringLength@entry=9654960, connectString=0x9352b0 "172.16.251.120:1522/orcl!", connectString@entry=0x8 <Address 0x8 out of bounds>, passwordLength=6, password=0x935250 "xxxx", userNameLength=6, userName=0x935230 "xxxx", conn=0x7f8344063900) at src/dpiConn.c:333
#20 dpiConn__create (conn=0x7f8344063900, context=context@entry=0x935200, userName=userName@entry=0x935230 "WN_AGV", userNameLength=userNameLength@entry=6, password=password@entry=0x935250 "xxx", passwordLength=passwordLength@entry=6, connectString=connectString@entry=0x9352b0 "172.16.251.120:1522/orcl!", connectStringLength=connectStringLength@entry=24, pool=pool@entry=0x0, commonParams=commonParams@entry=0x7f83557d3bc0, createParams=createParams@entry=0x7f83557d3c00, error=error@entry=0x7f83557d3ba0) at src/dpiConn.c:305
#21 0x00007f835f752afe in dpiConn_create (context=0x935200, userName=0x935230 "xxx", userNameLength=6, password=0x935250 "xxx", passwordLength=6, connectString=<optimized out>, connectStringLength=24, commonParams=0x7f83557d3bc0, createParams=0x7f83557d3c00, conn=0x7f83557d3cf8) at src/dpiConn.c:1284
#22 0x0000000000403566 in dpi_getConn () at oracle.c:399

### Some settings about the system:

1. What version of ODPI-C are you using (see dpi.h)?  **3.0**

2. What error(s) you are seeing? **read oracle  thread hang;**

3. What OS (and version) is your application executing on? **Centos7.3 kernel 3.10.0-514.el7.x86_64**

4. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed? **oracle-instantclient 11.2.0.4.0**

5. What is your Oracle Database version? **oracle 11.2.0.1 windows**

6. What compiler version did you use? **gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)** 

7.sqlnet.ora:
```
SQLNET.SEND_TIMEOUT = 3
SQLNET.RECV_TIMEOUT = 3
SQLNET.INBOUND_CONNECT_TIMEOUT = 3
 SQLNET.OUTBOUND_CONNECT_TIMEOUT = 3
TCP.CONNECT_TIMEOUT = 3
SQLNET.EXPIRE_TIME = 1
```

**Comment by cjbj** [comment]
@onmp can you comment on this?

**Comment by cjbj** [comment]
Closing - no update.
