### ISSUE TITLE
List of APIs making server trips?

### ISSUE THREAD

**Issue by c-bik** [oracle/odpi#108]
Hi,

My apologies for not following the template, I am only looking for a documentation.

OCI lists functions calls which makes server trips [here](https://docs.oracle.com/cd/B28359_01/appdev.111/b28395/ociacrou.htm#g430405).

Is there a similar documentation avilable for dpi APIs?

TIA

**Comment by anthony-tuininga** [comment]
That information is currently not available but we have discussed adding it at some point -- so I appreciate the prod. :-)

**Comment by c-bik** [comment]
@anthony-tuininga 👍 Thanks for a quick reply.

We are working on a [erlang driver](https://github.com/K2InformaticsGmbH/oranif) where we need to implement NIF wrappers for server bound (IO) DPI APIs differently (Dirty Schedulars) from the rest.

Obvious ones can be easily identified (like connect, stmt_execute etc). For the rest I am still wondering if there is a way to figure this out (looking at code etc) for now (i.e. without a doc).

Any hints?

TIA

**Comment by anthony-tuininga** [comment]
Well, all of the OCI routines are wrapped in src/dpiOci.c and they all have the form ``dpiOci__<fnName>`` where ``<fnName>`` is the name of the OCI routine less the OCI prefix. So for example, ``OCIStmtExecute`` is ``dpiOci__stmtExecute``. Most of the ODPI-C routines are thin wrappers on the OCI routines, so this mapping shouldn't be too difficult. If you have questions about a particular API I can certainly help out further.

**Comment by c-bik** [comment]
Wonderful and thanks a lot @anthony-tuininga. I can contribute back to document this if that helps.

**Comment by anthony-tuininga** [comment]
Thanks @c-bik. For reasons which @cjbj can explain, contributions are not accepted. If you dump your findings in this issue, though, I can at least make sure that your findings match what I expect!

**Comment by c-bik** [comment]
Sure thing and no worries.

Will post my findings here.

Thanks again for your help. Much appreciate it.

**Comment by cjbj** [comment]
Hi @c-bik 
- feel free to contact us if you have driver questions or issues
- how does oranif relate to erloci (other than the NIF bit)? Are you planning on maintaining both indefinitely?
- let us know when you're happy with oranif and we will add it to the 3rd party driver list on https://oracle.github.io/odpi/

**Comment by c-bik** [comment]
> Hi @c-bik

Hi @cjbj,

Sorry for late reply. Its been crazy so far into this month.

> * feel free to contact us if you have driver questions or issues

Sure. Thanks a lot! 👍 

> * how does oranif relate to erloci (other than the NIF bit)?

Not much! `oranif` is completely new design from scratch (leveraging on lessions learned from `erloci`). Not only the C interface is much simplified (ODPI-C instead of OCI), the interface towards erlang applications is now much light weight and straight forward too.

The NIF based design is much superior and streamlined compared to port based design of erloci which had big erlang term marshaling overhead. Besides, ODPI-C APIs are quite easy and straight forward to work with compared to OCI (great job to you all 🥇) - this will make oranif dev and maintenance quite easy.

An unfortunate side effect of that is the erlang API signature change. Perhaps a migration guideline will help eventually.

> Are you planning on maintaining both indefinitely?

I am not planning to maintain erloci at all. It is already showing some weaknesses to support new features like PL/SQL array/table parameters (hard to get help too : [stackoverflow](https://stackoverflow.com/questions/53210131/oci-21560-ociobjectnew-oci-typecode-table) and [OTN](https://community.oracle.com/message/14987360#14987360)), which oranif easily solved. All development activity on erloci are already frozen -- no new feature addition or bug fixes, for a while now.

**oranif is being build to eventually replace erloci** 

> * let us know when you're happy with oranif and we will add it to the 3rd party driver list on https://oracle.github.io/odpi/

Certainly. And again thanks a lot 👍 

We are currently trying to implement all the feature we need into oranif to replace erloci in our other projects. A necessary first step to declare erloci as **deprecated**.

Also erloci lacks organized test cases, benchmarking and coverage etc. I am hoping to address these with oranif right away. `oranif` isn't there yet, but hopefully soon.

**Comment by cjbj** [comment]
@c-bik good information and a great plan.

**Comment by c-bik** [comment]
> If you dump your findings in this issue, though, I can at least make sure that your findings match what I expect!

@anthony-tuininga Took while to get back here, but here is what we have so far: https://github.com/K2InformaticsGmbH/oranif/blob/srver-trip-list/roundTrips.md

Knowing an API has `0` server trips can be given design advantage in erlang (CPU bound NIF) towards performance. However if it is **NOT** and declared as CPU bound it will cause a schedular **freeze**. So we quite rely on the correctness of this list in oranif design.

What do you think? Does this list look correct to you so far?

TIA

**Comment by cjbj** [comment]
@c-bik I know you have a specialized case but FWIW for general apps, I am aiming to let users evaluate the round-trips costs themselves with knowledge from (e.g.) https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md#roundtrips By the time the driver wraps ODPI-C which wraps OCI which may vary with DB version, not to mention caching and other variabilities at each layer, trying to count costs from first principles will be inaccurate.  And maintaining a list is a big overhead on our dev time :)  I'm glad you are doing the work!

**Comment by cjbj** [comment]
@c-bik PS you page references Oracle 10.1 doc.  The latest doc is at https://www.oracle.com/pls/topic/lookup?ctx=dblatest&id=GUID-9B2F05F9-D841-4493-A42D-A7D89694A2D1

**Comment by c-bik** [comment]
> @c-bik I know you have a specialized case but FWIW for general apps, I am aiming to let users evaluate the round-trips costs themselves with knowledge from (e.g.) https://github.com/oracle/node-oracledb/blob/dev-4.0/doc/api.md#roundtrips By the time the driver wraps ODPI-C which wraps OCI which may vary with DB version, not to mention caching and other variabilities at each layer, trying to count costs from first principles will be inaccurate. And maintaining a list is a big overhead on our dev time :) I'm glad you are doing the work!

I know what you mean. `oranif` is small now (only few odpi APIs are wrapped) but it will grow over time time and maintaining such a list probably would be similar overhead for us too. If thereisn't a automatic way of knowing this information, I need to re-think this design! One way would be to sacrifice the CPU benefit to all of the small set of APIs (we have identified so far). They way we can at least gurantee stability of the driver.

**Comment by cjbj** [comment]
Will knowing which APIs make 0 round-trips be sufficient?

**Comment by c-bik** [comment]
> Will knowing which APIs make 0 round-trips be sufficient?

Yes. Trip count > 0 can’t be CPU bound - that is all we need to know.

**Comment by anthony-tuininga** [comment]
@c-bik, I've just pushed documentation changes that provide information on round-trips. I know @cjbj suggested it would be a fair bit of effort to maintain, but I'm fairly certain it won't be too much of a burden. There may be some cases where only one round trip is mentioned but more may actually take place. For example, creating a connection actually involves multiple round-trips. In order to hedge around that we may change the documentation to simply state "no" (for no round-trips), "yes" (for one or more round-trips) and "maybe" (when the situation determine whether round-trips are incurred or not). I'll discuss with @cjbj. In the meantime, however, you can take a look and let me know if that satisfies your needs. Looking through what you had determined shows a few discrepancies. :-)

**Comment by c-bik** [comment]
Thanks a lot @anthony-tuininga this will help us a lot!

> ... we may change the documentation to simply state "no" (for no round-trips), "yes" (for one or more round-trips) and "maybe" (when the situation determines whether round-trips are incurred or not).

For `oranif` yes/no is enough and we will consider **maybe** as **YES** (to be safe)

> In the meantime, however, you can take a look and let me know if that satisfies your needs. Looking through what you had determined shows a few discrepancies. :-)

Looks great and https://github.com/K2InformaticsGmbH/oranif/issues/119 will have a close look and make correction on our side (perhaps also get back with questions)

I think I should close this issue now, right? (unless if you prefer we post any further related questions here)

**Comment by anthony-tuininga** [comment]
You're welcome, @c-bik! I've just pushed some changes to improve the formatting and to use the "yes", "no" and "maybe" scheme I suggested yesterday. For the "maybe" ones, you can certainly treat that as "yes" to be safe, but a number of them (in particular the *_release() methods) you can easily ensure that no round trip takes place if you wish. I'll close this issue now, but feel free to continue to ask questions. Open a new issue for them, though. If you have questions, the documentation probably needs improvement anyway. :-)

**Comment by ddevienne** [comment]
It would be helpful and informative, if possible, to perhaps have comments in the "maybe" cases, that explain why/when. I'm not talking about anything exhaustive, just hints on when something would round-trip, perhaps by using Object-Relational for example (which is pretty rare I guess). My $0.02.

**Comment by anthony-tuininga** [comment]
@ddevienne, I have included comments in the "maybe" cases. Take a look at the [documentation](https://oracle.github.io/odpi/doc/user_guide/round_trips.html). If you see a place where I missed comments for a "maybe" case, let me know. If the comments don't give you sufficient information, let me know that, too! Thanks.

**Comment by ddevienne** [comment]
This is great! Thanks a bunch.
