### ISSUE TITLE
NLS_LANG support through dpiConn_create

### ISSUE THREAD

**Issue by c-bik** [oracle/odpi#109]
Hi,

I am struggeling to find a way to set `NLS_LANGUAGE` or `NLS_TERRITORY` parts of `NLS_LANG` through `dpiConn_create(..., dpiCommonCreateParams, ...)`.

According to definition of [NLS_LANG](https://docs.oracle.com/cd/E12102_01/books/AnyInstAdm784/AnyInstAdmPreInstall18.html) it should be in format
`[NLS_LANGUAGE]_[NLS_TERRITORY].[NLS_CHARACTERSET]`

Setting only `NLS_CHARACTERSET` works as follows
```c
dpiCommonCreateParams commonParams;
commonParams.encoding = "AL32UTF8";
```

But the following returns error
`DPI-1026: invalid character set GERMAN_SWITZERLAND.AL32UTF8`
```c
dpiCommonCreateParams commonParams;
commonParams.encoding = "GERMAN_SWITZERLAND.AL32UTF8";
```

What am I missing?

Can you please help?

TIA

---
ODPI: 3.0.0, Windows 10, Instant Client 12.1/18.3 (both), Oracle XE
> Definition of [dpiCommonCreateParams.encoding](https://oracle.github.io/odpi/doc/structs/dpiCommonCreateParams.html#dpicommoncreateparams)
>> Specifies the encoding to use for CHAR data, as a null-terminated ASCII string. Either an IANA or Oracle specific character set name is expected. NULL is also acceptable which implies the use of the NLS_LANG environment variable (or ASCII, if the NLS_LANG environment variable is not set). The default value is NULL.

**Comment by anthony-tuininga** [comment]
Actually, there is no way to set NLS_LANGUAGE or NLS_TERRITORY aspects through ODPI-C. You must set those by setting the environment variable NLS_LANG prior to the first call to ``dpiContext_create()``. As mentioned in the documentation, that parameter only specifies the encoding (aka character set).

**Comment by c-bik** [comment]
> Actually, there is no way to set NLS_LANGUAGE or NLS_TERRITORY aspects through ODPI-C. You must set those by setting the environment variable NLS_LANG prior to the first call to `dpiContext_create()`. As mentioned in the documentation, that parameter only specifies the encoding (aka character set).

If `NLS_LANG = GERMAN_SWITZERLAND.AL32UTF8` already in environment and then in code `commonParams.encoding = "ISO-8859-13";` attempted, will that be an error or encoding `AL32UTF8` will be overridden with `ISO-8859-13` in session?

**Comment by anthony-tuininga** [comment]
The encoding will be overwritten but the language and territory information is still acquired from NLS_LANG.

**Comment by c-bik** [comment]
Thanks for clearing it up. This will work for me.
