### ISSUE TITLE
Cannot build project in Cygwin

### ISSUE THREAD

**Issue by nskforward** [oracle/odpi#11]
1) Downloaded and unzipped the Instant Client to "C:\instant_client"
2) Added "C:\instant_client" to PATH system variable
3) Copied the include files to Cygwin include folder
4) Copied src folder to the project folder
4) Created a simple program main.c:

<<<
#include <stdio.h>
#include <dpi.h>

int main()
{
    dpiErrorInfo errorInfo;
    dpiContext *gContext = NULL;
    if (dpiContext_create(DPI_MAJOR_VERSION, DPI_MINOR_VERSION, &gContext, &errorInfo) < 0) {
        fprintf(stderr, "ERROR: %.*s (%s : %s)\n", errorInfo.messageLength, errorInfo.message, errorInfo.fnName, errorInfo.action);
        return -1;
    }
    return 0;
}
>>>

in the CMakeList.txt:
<<<
cmake_minimum_required(VERSION 3.7)
project(odpi)
set(CMAKE_C_STANDARD 11)

set(SOURCE_FILES
       main.c
        src/dpiConn.c
        src/dpiContext.c
        src/dpiData.c
        src/dpiDeqOptions.c
        src/dpiEnqOptions.c
        src/dpiEnv.c
        src/dpiError.c
        src/dpiGen.c
        src/dpiGlobal.c
        src/dpiLob.c
        src/dpiMsgProps.c
        src/dpiObject.c
        src/dpiObjectAttr.c
        src/dpiObjectType.c
        src/dpiOci.c
        src/dpiOracleType.c
        src/dpiPool.c
        src/dpiRowid.c
        src/dpiStmt.c
        src/dpiSubscr.c
        src/dpiUtils.c
        src/dpiVar.c
        )
add_executable(odpi ${SOURCE_FILES})
>>>

When I try to build project I get the following error:
**ERROR: DPI-1047: Oracle Client library cannot be loaded: No such file or directory. See https://oracle.github.io/odpi/doc/installation.html for help (dpiContext_create : load library)**

How I can load client library?

**Comment by anthony-tuininga** [comment]
The error "no such file or directory" suggests that OCI.DLL cannot be found. Check your PATH environment variable again. Also, if you download and unpack the sqlplus package in the same directory, you can use it to test as well. If it runs, so will ODPI-C in the same configuration.

**Comment by nskforward** [comment]
I double checked PATH environment variable. Also I downloaded sqlplus, sdk packages and copied unzipped files to C:\instant_client but I get the same error.
Do you have other suggestions?

**Comment by anthony-tuininga** [comment]
Can you try it in a regular command prompt (ie not Cygwin)? It is something as simple as using a ";" instead of a ":" in your Cygwin PATH? Can you show the exact commands you are issuing and the exact output that you are receiving -- both for SQL\*Plus and your application?

**Comment by kubo** [comment]
Replacing [this line](https://github.com/oracle/odpi/blob/46430ce85e0eefe14f6ab33d709cc4acd9de7680/src/dpiOci.c#L360) with `#if defined _WIN32 || defined __CYGWIN__` will fix this issue.
Cygwin compiler doesn't define `_WIN32`.

**Comment by anthony-tuininga** [comment]
I have added the check, as suggested. Can you confirm that resolves the issue for you? Thanks.

**Comment by nskforward** [comment]
Antony, I figured out that everything works fine in Windows 7, but I still have error the same error in Windows 10

I tried to follow your suggestion and copied sqlplus to the same directory as instant client. When I try to run sqlplus from Windows CMD I get the following error:
error while loading shared libraries: MSVCR100.dll: cannot open shared object file: No 

Do you have ideas why this file is missing and what I should install to have this file in the right place?

**Comment by nskforward** [comment]
I have fixed this issue by installing additional Windows package from:
https://www.microsoft.com/en-us/download/details.aspx?id=14632

Now everything works fine in odpi under Cygwin

**Comment by cjbj** [comment]
@nskforward did you test with or without the patch that @kubo suggested? This was committed in 2.0.0-beta.4

**Comment by nskforward** [comment]
@cjbj 
I tested it with the patch. I did not test it without the patch.
