### ISSUE TITLE
Help using ODPI-C

### ISSUE THREAD

**Issue by tgulacsi** [oracle/odpi#12]
I'm trying to write a Go database/sql/driver from scratch (I've created a cx_Oracle-like driver back as goracle, and later joined rana/ora, rewritten as ora.v4, and now trying to rewrite it from scratch using ODPI-C. cx_Oracle's quality is what I'm chasing).

I've stuck right at the beginning: get the Data from a Query.

I use dpiConn_newVar to get a *dpiVar and an array of *dpiData, store them for later use
```
    C.dpiStmt_setFetchArraySize(st.dpiStmt, fetchRowCount)
    var info C.dpiQueryInfo
    for i := 0; i < colCount; i++ {
        if C.dpiStmt_getQueryInfo(st.dpiStmt, C.uint32_t(i+1), &info) == C.DPI_FAILURE {
            return nil, st.getError()
        }
        typ, numTyp := info.oracleTypeNum, info.defaultNativeTypeNum
        bufSize := maxArraySize * info.clientSizeInBytes
        switch typ {
        case C.DPI_ORACLE_TYPE_VARCHAR, C.DPI_ORACLE_TYPE_NVARCHAR, C.DPI_ORACLE_TYPE_CHAR, C.D
PI_ORACLE_TYPE_NCHAR:
            bufSize *= 4
        }
        var dataArr *C.dpiData
        if C.dpiConn_newVar(
            st.conn.dpiConn, typ, numTyp, maxArraySize,
            bufSize, 1, 0, info.objectType,
            &r.vars[i], &dataArr,
        ) == C.DPI_FAILURE {
            return nil, st.getError()
        }
        if C.dpiStmt_define(st.dpiStmt, C.uint32_t(i+1), r.vars[i]) == C.DPI_FAILURE {
            return nil, st.getError()
        }
        r.data[i] = (*((*[maxArraySize]*C.dpiData)(unsafe.Pointer(dataArr))))[:]
    }
    if C.dpiStmt_addRef(st.dpiStmt) == C.DPI_FAILURE {
        return &r, st.getError()
    }
```

then I use dpi_fetch (tried dpi_fetchRows, with no avail)

```
    var found C.int
    if C.dpiStmt_fetch(r.dpiStmt, &found, &r.bufferRowIndex) == C.DPI_FAILURE {
        return r.getError()
    }
    if found == 0 {
        r.finished = true
        return io.EOF
    }
     for i, col := range r.columns {
        var typ C.dpiNativeTypeNum
        var d *C.dpiData
        if C.dpiStmt_getQueryValue(r.dpiStmt, C.uint32_t(i+1), &typ, &d) == C.DPI_FAILURE {
            return r.getError()
        }
        if d.isNull == 1 {
            dest[i] = nil
            continue
        }
        switch typ {
        case C.DPI_ORACLE_TYPE_VARCHAR, C.DPI_ORACLE_TYPE_NVARCHAR, C.DPI_ORACLE_TYPE_CHAR, C.D
PI_ORACLE_TYPE_NCHAR, C.DPI_ORACLE_TYPE_LONG_VARCHAR:
            b := C.dpiData_getBytes(d)
            fmt.Printf("b=%p[%d]\n", b.ptr, b.length)
            if b.ptr == nil {
                dest[i] = ""
                continue
            }
            dest[i] = C.GoStringN(b.ptr, C.int(b.length))
 ...
```

Fails with SIGSEGV and when not, then data's bytes are zero.

1. any obvious failures?

2. is dpiStmt_define's position starts from 1?

3. what is bufferRowIndex? What shall I index it with? The array of dpiData? But then why is that needed in dpiStmt_fetch ?

4. I read cx_Oracle/src/Cursor.c, and it increments bufferRowIndex right after the fetch - why does this not skip the first value? As I printed out the dpiData array after the fetch, the first element is nil, so this indicates such thing, but I don't know.

Thanks in advance,
Tamás Gulácsi

#### Answer the following questions:

1. What version of ODPI-C are you using (see dpi.h)?
2.0.0-beta.4

2. What error(s) you are seeing?
It's all my application code's fault.

**Comment by tgulacsi** [comment]
Ok,

1. 
	r.data[i] = (*((*[maxArraySize]*C.dpiData)(unsafe.Pointer(&dataArr))))[:]

was the solution (I can convert only pointer types in Go) for the bad dpiData.

2. seems to be true

3. seems to start with 0

4. I must've read something wrong, now I increment bufferRowIndex only after reading out data, and seems to work.

**Comment by cjbj** [comment]
@tgulacsi I'll let @anthony-tuininga comment on the code (and decide what doc & sample improvements can be made).

During design & implementation of ODPI-C, @anthony-tuininga created an (unreleased) basic Go driver that uses ODPI-C.  Our plans were to get ODPI-C and cx_Oracle 6 in production, get node-oracledb V2 out, and then review the state of Go drivers.  The decision to be made is whether to contribute to an existing driver, or release & enhance our prototype. This would depend on the technical direction of the current Go drivers, and what their (your) communities think is best.

It seems you are already heading down the rewrite path, which is great.  We'd love to discuss this more and see how we can assist you.  Do you want to drop me an [email](https://github.com/cjbj)?

**Comment by tgulacsi** [comment]
Ok, another question:

I want to bind a slice of int64s
```
        if C.dpiConn_newVar(
            st.conn.dpiConn, typ, natTyp, C.uint32_t(dataSliceLen),
            bufSize, 1,
            isArray, nil,
            &st.vars[i], &dataArr,
        ) == C.DPI_FAILURE {
            return st.getError()
        }
        st.data[i] = (*((*[maxArraySize]*C.dpiData)(unsafe.Pointer(&dataArr))))[:dataSliceLen]
        fmt.Printf("%d. dpiConn_newVar(dpiConn=%p, typ=%d, natTyp=%d, arraySize=%d, bufSize=%d,
isBytes=%d, isArray=%d, obj=%p, *dpiVar=%p, *dataArr=%p): %#v\n",
            i, st.conn.dpiConn, typ, natTyp, dataSliceLen, bufSize, 1, isArray, nil, &st.vars[i]
, &dataArr, st.data[i])

```

result:

```
! go install && go test -run=Exec
0. dpiConn_newVar(dpiConn=0xb05eb0, typ=2010, natTyp=3000, arraySize=1000, bufSize=0, isBytes=1, isArray=0, obj=%!p(<nil>), *dpiVar=0xc42000e070, *dataArr=0xc42000e078): []*ora._Ctype_struct_dpiData{(*ora._Ctype_struct_dpiData)(0xb7be50), (*ora._Ctype_struct_dpiData)(0x827d90), (*ora._Ctype_struct_dpiData)(nil), (*ora._Ctype_struct_dpiData)(nil), (*ora._Ctype_struct_dpiData)(nil), (*ora._Ctype_struct_dpiData)(nil), (*ora._Ctype_struct_dpiData)(nil), (*ora._Ctype_str...
```

only 2 elements of the returned dpiData array is not nil, and even the second looks suspicious (`&ora._Ctype_struct_dpiData{isNull:537608192, _:[4]uint8{0xc4, 0x0, 0x0, 0x0}, value:[24]uint8{0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x18, 0xf3, 0x57, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}}`), 
and the C.dpiData_setInt64 results in SIGSEGV.

What am I doing wrong?

**Comment by anthony-tuininga** [comment]
The dataArr value that is returned is an array of dpiData structures -- not an array of pointers to dpiData structures. It looks like that might be the source of your difficulties?

**Comment by tgulacsi** [comment]
Thanks, that was the culprit!
Anthony Tuininga <notifications@github.com> ezt írta (időpont: 2017. jún.
10., Szo, 4:54):

**Comment by tgulacsi** [comment]
For the record, the correct conversion from `*C.dpiData` to []C.dpiData is:

    var p *C.dpiData
    ...
    ((*[1<<30]C.dpiData)(unsafe.Pointer(p)))[:arraySize:arraySize]

**Comment by tgulacsi** [comment]
Ok, next question:
What combinations of OracleType-NativeType pairs are accepted?
I get "DPI-1014: conversion between Oracle type 2010 and native type 3002 is not implemented" for binding float64 to NUMBER column.
And I got "ORA-01722: invalid number" for binding string to number column
(INSERT INTO table (F_num NUMBER) values (:1)).

**Comment by tgulacsi** [comment]
What are dpiVar_setFrom... (dpiVar_setFromLOB) for? What is the difference with dpiData_setLOB ?
When to use which?
I'm asking this because I use dpiConn_newVar, then dpiData_setLOB on the dpiData returned with the var by newVar, and though I can write the LOB (tempLob), I get "ORA-22275: invalid LOB locator specified" for dpiStmt_execute.

**Comment by anthony-tuininga** [comment]
> What combinations of OracleType-NativeType pairs are accepted?

That should be documented. I'll take care of that. In the meantime, though, you can look here: https://github.com/oracle/odpi/blob/master/src/dpiOracleType.c. That gives you the default native type for each Oracle type. Then you can look here: https://github.com/oracle/odpi/blob/master/src/dpiVar.c#L1412-L1438 for the non-default native types supported for each Oracle type.

> And I got "ORA-01722: invalid number" for binding string to number column
(INSERT INTO table (F_num NUMBER) values (:1)).

I'd need more information to know why that was happening. It might in fact be an invalid number! :-)

> What are dpiVar_setFrom... (dpiVar_setFromLOB) for? What is the difference with dpiData_setLOB ?
When to use which?

dpiVar_setFromLob() is intended when using variables. It manages the references and ensures things are copied internally. dpiData_setLOB() should only be used when managing attributes of Oracle objects, not for variables. I'll take a look at the documentation for these methods and ensure that is made clear.

**Comment by tgulacsi** [comment]
Thanks!

Trying to bind a "0" into a NUMBER column, I got 
`z_test.go:113: 1. {Name:f_num Value:[0]}: dpiStmt_execute(mode=32 arrLen=1): ORA-01722: invalid number`
As I see, this is allowed, so I missed something.

My other question was: I can read and write LOBs, but when I try to INSERT into a [BC]LOB from a string (VARCHAR), the result is some garbage in the database.

When I wrote these down, it struck me that maybe these correlate, and I do the VARCHAR binding simply wrong...

And that was the case: I used dpiData_setBytes, but here I have to use dpiVar_setFromBytes.
Just as with LOBs.

So I suggest writing this somewhere in the documentation:
"If there's a setter on the dpiVar for something, you have to use that, and not the same function on dpiData."

**Comment by anthony-tuininga** [comment]
> Trying to bind a "0" into a NUMBER column, I got
z_test.go:113: 1. {Name:f_num Value:[0]}: dpiStmt_execute(mode=32 arrLen=1): ORA-01722: invalid number
As I see, this is allowed, so I missed something.

Can you provide the full code for this test case? I can take a look at that and your Go driver code and let you know if something isn't happening correctly -- and clarify documentation further, if needed!

> So I suggest writing this somewhere in the documentation:
"If there's a setter on the dpiVar for something, you have to use that, and not the same function on dpiData."

Agreed. I'll add a note to each of the functions as well.

**Comment by tgulacsi** [comment]
Finally I could manage to fix it - the error was using dpiData_setBytes instead of dpiVar_setFromBytes - this resulted in a pointer being in the LOB data.
The current code (a3c3f2eefd217882aedf9097eb9be48ee24af9d8 at https://github.com/rana/ora/commit/a3c3f2eefd217882aedf9097eb9be48ee24af9d8) passes the tests, both when I INSERT a []byte, and when I INSERT a Lob (from a Reader).

**Comment by anthony-tuininga** [comment]
I have updated the documentation as suggested to include information on [data types](https://oracle.github.io/odpi/doc/user_guide/data_types.html) and provide warnings about the use of the dpiData functions [here](https://oracle.github.io/odpi/doc/public_functions/dpiData.html#c.dpiData_setLOB) for example.
