### ISSUE TITLE
DPI-1001: out of memory

### ISSUE THREAD

**Issue by zymon** [oracle/odpi#121]
Hi,
I have a problem with node-oracledb.

Selecting many columns of type VARCHAR2(4000 BYTE) causes 'out of memory' error.
I have a query that selects 22 columns, 6 of them are defined as VARCHAR2(4000), 14 are of type NUMBER, and several others as VARCHAR2 (100 BYTE, 400 BYTE, 3 BYTE, 1 BYTE)
Total length of all character columns in bytes is: 24 504 bytes.
When removing one column from the select I'm able to get the results. But after reloading the page several times I get the 'out of memory' error again. Looks like some buffer gets overflown and it's not cleared correctly.

I've contacted the node-oracledb team but didn't receive any valuable response. Do you know when DPI-1001 can happen?
And, what's more interesting it works on one server. We have 2 servers (dev, acceptance) - the same OS, the same instant client. When connecting to the same DB on dev everything works fine, on acceptance sometimes if fails. It happens after several calls.

**Comment by cjbj** [comment]
The node-oracledb and ODPI-C teams are the same.  I'll close this issue.
Please give the requested information in https://github.com/oracle/node-oracledb/issues/1186#issuecomment-563977432
