### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by wwanderley** [oracle/odpi#122]
I've been trying to find a memory leak on [godror](https://github.com/godror/godror).

[Here's](https://gist.github.com/wwanderley/8a7d21337ded2eceb4a96122cfc10d26) a little code to reproduce it directly on ODPI-C (with `DPI_DEBUG_LEVEL=38`).

Some dpiObjects are not freed. Where's my mistake?

2. What version of ODPI-C are you using (see dpi.h)?
v3.3.0

5. What OS (and version) are you using?
Ubuntu 18

6. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
18c official rpm package (converted to .deb with alien)

7. What is your Oracle Database version?
18c-xe

8. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?

9. What environment variables did you set?  How *exactly* did you set them?

10. What compiler version did you use?
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by anthony-tuininga** [comment]
In your loop, you are calling dpiObject_addRef() on the element object that is returned by the call to dpiObject_getElementValueByIndex(). That is incorrect. A new object was implicitly created by this call, so you simply need to use it and then call dpiObject_release() when you are finished with it. I've modified the documentation to make that clear!

**Comment by anthony-tuininga** [comment]
As an aside, the first step in determining such leaks is to look at the results with DPI_DEBUG_LEVEL=2 as this shows the reference counts. If you see that references are not being released you have discovered the source of the leak. You may wish to use DPI_DEBUG_LEVEL=6 if you need to see the particular ODPI-C calls that are increasing references -- such as in this case. It is only in the case where no references are being retained but memory is still being leaked that you need to set DPI_DEBUG_LEVEL=38. Hope that's helpful!

**Comment by wwanderley** [comment]
Thanks for this insight! It helps a lot.
