### ISSUE TITLE
Oracle XE 18c in Travis

### ISSUE THREAD

**Issue by c-bik** [oracle/odpi#124]
Hi,

I have been using [`accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh`](https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh) script for some time now to automated test with code coverage.

This script is however isn't very scalable or maintenable, among other things!

What I am looking to know is what is the recommended way. Travis (Ubuntu) is very handy (specially with coveralls integration etc), but Oracle only has yum support!

Currently working around with docker, but that have significantly increased the time for each test run.

How do you suggest I should go about testing integration?

TIA

**Comment by cjbj** [comment]
For private testing you could try https://www.oracle.com/cloud/free/ 

The DB team is well aware of the general issue.  See https://github.com/oracle/docker-images/issues/1156

**Comment by c-bik** [comment]
@cjbj thanks for the pointers and sorry for posting this as issue here. I realized after posting it that it may be not in context here.

**Comment by cjbj** [comment]
@c-bik we're good people to empathize with, and we champion your causes internally.  We just don't have the magic we'd like to have,
