### ISSUE TITLE
odpic.dll created by Makefile.win32 exports nothing.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#126]
Platform: Windows
ODPI-C version: latest at github.

`nmake -f Makefile.win32` creates `lib\odpic.dll` and `lib\odpic.lib`. However `lib\odpic.dll` exports nothing and `lib\odpic.lib` is a static library. There is no way to use `odpic.dll`.

Could you use [`__declspec(dllexport)`](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-declspec-dllexport) or [DEF file](https://docs.microsoft.com/en-us/cpp/build/exporting-from-a-dll-using-def-files) to export public functions?

Export functions using `__declspec(dllexport)`:

1. Add `-DDPI_EXPORTS` at the end of [this line](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L61).
2. Add the following code [here](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/include/dpi.h#L44)
   ```c
   #if defined(_MSC_VER) && defined(DPI_EXPORTS)
   #define DPI_EXPORT __declspec(dllexport)
   #else
   #define DPI_EXPORT
   #endif
   ```
3. Add `DPI_EXPORT` for all functions in dpi.h
   ```c
   // create a context handle and validate the version information
   DPI_EXPORT int dpiContext_create(unsigned int majorVersion, unsigned int minorVersion,
           dpiContext **context, dpiErrorInfo *errorInfo);

   // destroy context handle
   DPI_EXPORT int dpiContext_destroy(dpiContext *context);

   ...(omitted)...
   ```

4. Add `IMPLIB_NAME=$(LIB_DIR)\odpic_dll.lib` [here](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L32)

5. Add `/IMPLIB:$(IMPLIB_NAME)` at the end of [this line](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L64)

Otherwise, export functions using a DEF file

1. Add the following file as `src\odpic.def`
   ```
   LIBRARY  ODPIC
   EXPORTS
      dpiContext_create
      dpiContext_destroy
      ... list all public functions...
   ```

2. Add `IMPLIB_NAME=$(LIB_DIR)\odpic_dll.lib` [here](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L32)

3. Add `/DEF:$(SRC_DIR)\odpic.def /IMPLIB:$(IMPLIB_NAME)` at the end of [this line](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L64)

In both cases `lib\odpic_dll.lib`, import library for `odpic.dll`, is created at [this line](https://github.com/oracle/odpi/blob/3adeb7e9f62d816a1dae38bec5e11486198da492/Makefile.win32#L64) in addition to `lib\odpic.dll`.

---
What I checked:
```bat
C:\>git clone  https://github.com/oracle/odpi.git
Cloning into 'odpi'...
remote: Enumerating objects: 729, done.
remote: Counting objects: 100% (729/729), done.
remote: Compressing objects: 100% (369/369), done.
remote: Total 8449 (delta 548), reused 487 (delta 348), pack-reused 7720
Receiving objects: 100% (8449/8449), 3.35 MiB | 1.90 MiB/s, done.
Resolving deltas: 100% (7011/7011), done.

C:\>cd odpi

C:\odpi>nmake -f Makefile.win32

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl /nologo /c /Fobuild\ /Iinclude src\dpiConn.c src\dpiContext.c src\dpiData.c src\dpiEnv.c src\dpiError.c src\dpiGen.c src\dpiGlobal.c src\dpiLob.c src\dpiObject.c src\dpiObjectAttr.c src\dpiObjectType.c src\dpiPool.c src\dpiStmt.c src\dpiUtils.c src\dpiVar.c src\dpiOracleType.c src\dpiSubscr.c src\dpiDeqOptions.c src\dpiEnqOptions.c src\dpiMsgProps.c src\dpiRowid.c src\dpiOci.c src\dpiDebug.c src\dpiHandlePool.c src\dpiHandleList.c src\dpiSodaColl.c src\dpiSodaCollCursor.c src\dpiSodaDb.c src\dpiSodaDoc.c src\dpiSodaDocCursor.c src\dpiQueue.c
dpiConn.c
dpiContext.c

...(omitted)...

dpiSodaDocCursor.c
dpiQueue.c
Generating Code...
        link /nologo /dll /OUT:lib\odpic.dll build\dpiConn.obj build\dpiContext.obj  build\dpiData.obj build\dpiEnv.obj  build\dpiError.obj build\dpiGen.obj  build\dpiGlobal.obj build\dpiLob.obj  build\dpiObject.obj build\dpiObjectAttr.obj  build\dpiObjectType.obj build\dpiPool.obj  build\dpiStmt.obj build\dpiUtils.obj  build\dpiVar.obj build\dpiOracleType.obj  build\dpiSubscr.obj build\dpiDeqOptions.obj  build\dpiEnqOptions.obj build\dpiMsgProps.obj  build\dpiRowid.obj build\dpiOci.obj  build\dpiDebug.obj build\dpiHandlePool.obj  build\dpiHandleList.obj build\dpiSodaColl.obj  build\dpiSodaCollCursor.obj build\dpiSodaDb.obj  build\dpiSodaDoc.obj build\dpiSodaDocCursor.obj  build\dpiQueue.obj
        lib /nologo /OUT:lib\odpic.lib build\dpiConn.obj build\dpiContext.obj  build\dpiData.obj build\dpiEnv.obj  build\dpiError.obj build\dpiGen.obj  build\dpiGlobal.obj build\dpiLob.obj  build\dpiObject.obj build\dpiObjectAttr.obj  build\dpiObjectType.obj build\dpiPool.obj  build\dpiStmt.obj build\dpiUtils.obj  build\dpiVar.obj build\dpiOracleType.obj  build\dpiSubscr.obj build\dpiDeqOptions.obj  build\dpiEnqOptions.obj build\dpiMsgProps.obj  build\dpiRowid.obj build\dpiOci.obj  build\dpiDebug.obj build\dpiHandlePool.obj  build\dpiHandleList.obj build\dpiSodaColl.obj  build\dpiSodaCollCursor.obj build\dpiSodaDb.obj  build\dpiSodaDoc.obj build\dpiSodaDocCursor.obj  build\dpiQueue.obj

C:\odpi>dumpbin /EXPORTS lib\odpic.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file lib\odpic.dll

File Type: DLL

  Summary

        C000 .data
        1000 .gfids
        4000 .pdata
        C000 .rdata
        1000 .reloc
       47000 .text
```
`lib\odpic.dll` exports nothing.

```bat
C:\odpi>cd samples

C:\odpi\samples>nmake -f Makefile.win32 build\DemoBLOB.exe

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl /nologo /c /Fobuild\ /I..\include .\SampleLib.c .\DemoBLOB.c
SampleLib.c
DemoBLOB.c
Generating Code...
        link /nologo /out:build\DemoBLOB.exe build\DemoBLOB.obj build\SampleLib.obj ..\lib\odpic.lib

C:\odpi\samples>dumpbin /IMPORTS build\DemoBLOB.exe
Microsoft (R) COFF/PE Dumper Version 14.00.24215.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file build\DemoBLOB.exe

File Type: EXECUTABLE IMAGE

  Section contains the following imports:

    KERNEL32.dll
             140048000 Import Address Table
             140052DD0 Import Name Table
                     0 time date stamp
                     0 Index of first forwarder reference

                         135 EnterCriticalSection
                         3C0 LeaveCriticalSection

...(omitted)...

                         620 WriteConsoleW
                         466 RaiseException

  Summary

        C000 .data
        1000 .gfids
        4000 .pdata
        C000 .rdata
        1000 .reloc
       47000 .text

C:\odpi\samples>
```
`build\DemoBLOB.exe` uses functions in kernel32.dll. It doesn't use any function in odpic.dll.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. I'll take care of this.

**Comment by anthony-tuininga** [comment]
I've made the necessary changes, I believe. I am continuing to accept the default name for the import library, however. Is that change necessary?

**Comment by kubo** [comment]
> I am continuing to accept the default name for the import library, however. Is that change necessary?

It depends on whether a static library should be created or not. If not, it isn't necessary.
I suggested `/IMPLIB:$(IMPLIB_NAME)` in order not to overwrite the static library.

Could you change Makefile.win32 as follows if only the import library is necessary.
* Remove [these lines](https://github.com/oracle/odpi/commit/fce6e31a0d6673ad03ef10738f391ba063a9c046#diff-fae9a8864af0fd512d95800a4b153ddbL65-L67)
* Change [this line](https://github.com/oracle/odpi/commit/fce6e31a0d6673ad03ef10738f391ba063a9c046#diff-fae9a8864af0fd512d95800a4b153ddbL63) to `$(DLL_NAME) $(LIB_NAME): $(OBJS)`

And add the following comment after `LD_LIBRARY_PATH=...` in README.md files under the samples and test directories.

    On Windows you need to copy odpic.dll to the current directory in advance.
    
        copy ..\..\lib\odpic.dll .

**Comment by anthony-tuininga** [comment]
I am not a Windows expert by any means. Would there be a good reason to create a static library in addition to the import library?

Can you explain the comment about needing to copy odpic.dll to the current directory? Presumably it can be placed anywhere in the PATH and it should work as expected?

**Comment by kubo** [comment]
> Would there be a good reason to create a static library in addition to the import library?

Only compatibility in minor version updates. I would remove the static library if the next version is major version update because `embed/dpi.c` is available instead.

> Presumably it can be placed anywhere in the PATH and it should work as expected?

Yes. I firstly hit on that way. But I didn't get a concise English sentence so I wrote another way.

See [Windows DLL search order](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications). Whereabout of an executable is the first place of the search order. The PATH environment variable is the last.

**Comment by anthony-tuininga** [comment]
ODPI-C 4.0 was just released containing these changes.
