### ISSUE TITLE
The mode argument of dpiConn_startupDatabase

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#127]
- Include a link to the documentation section or the example

[`dpiConn_startupDatabase`](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_startupDatabase)

- Describe the confusion

The second argument is:
```
mode [IN] – one of the values from the enumeration dpiStartupMode.
```

The `mode` argument is passed to the `flags` argument of [`OCIDBStartup`](https://docs.oracle.com/en/database/oracle/oracle-database/19/lnoci/connect-authorize-and-initialize-functions.html#GUID-8E4CB0D4-DC77-4AA1-A3F8-9C05DE595353). I'm concerned that `flags` is a plural form. I don't think `OCI_DBSTARTUPFLAG_RESTRICT` and `OCI_DBSTARTUPFLAG_FORCE` are exclusive if I don't misunderstand explanation about them. So I guess that dpiStartupMode may be combined using bit-OR though the Oracle manual doesn't describe that flags could be combined.

- Suggest changes that would help

If my guess is correct, could you change the [ODPC-C document](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_startupDatabase) such as "one or more of the values from the enumeration dpiStartupMode, OR’ed together"?
If it isn't correct, could you request the Oracle manual team to change the fifth argument name of `OCIDBStartup` from `flags` to `flag`?

**Comment by anthony-tuininga** [comment]
Yes, you are correct. It is one or more of the flags, OR'ed together. I have adjusted the documentation for this function as well as its sister function `dpiConn_startupDatabaseWithPfile`.

**Comment by kubo** [comment]
Thanks. I confirmed the change.
