### ISSUE TITLE
ORA-24911: Cannot start listener thread at specified port for CQN portNumber

### ISSUE THREAD

**Issue by dinvlad** [oracle/odpi#128]
**See https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html for how to report security issues**.

For other issues:

**1. What version of ODPI-C are you using (see dpi.h)?**
3.3 (from [godror](https://github.com/godror/godror/tree/master/odpi))

**2. Do you have a runnable code snippet to describe the problem?**
Pseudocode (an equivalent of Go commands):
```
// commonCreateParams contains createMode with DPI_MODE_CREATE_EVENTS flag set
dpiPool_create(..., *commonCreateParams, ..., **pool);
//
dpiPool_acquireConnection(*pool, ..., **conn);
//
// subscrCreateParams contains poolNumber != 0
dpiConn_subscribe(*conn, *subscrCreateParams, **subscr);
```

**3. What error(s) you are seeing?**
When I set poolNumber to a non-zero value in `subscrCreateParams`, I always see
```
ORA-24911: Cannot start listener thread at specified port
```
which according to [Oracle docs](http://ora.codes/ora-24911/), means
```
Cause:
Thread already running at a different port.
Action:
Set the correct port in the environment handle or let the system choose the port.
```
This is unexpected, as I set an arbitrary `poolNumber`, and each time I'm getting this error.
Is the port for the subscription notification not supposed to be chosen in this way (when we prefer to choose it)? The error message suggests that a (random) port is already picked for us when we open the connection, however there are no controls (as far as I can tell) for setting it anywhere prior.

Although I've experienced these problems using a wrapper in Go ([godror](https://github.com/godror/godror/tree/master/odpi)), others have reported very similar symptoms in Node.js (https://stackoverflow.com/questions/51750368/dynamic-ports-with-docker-and-oracle-cqn). This suggests that the issue might not be within language-specific wrappers, but rather in the ODPI-C layer itself (or the dynamic libraries).

**4. What OS (and version) is your application executing on?**
macOS 10.14.6 (native)
Oracle Linux 7 (in a Docker)

**5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?**
```Dockerfile
FROM oraclelinux:7-slim AS oracle
ARG VERSION=19.5
RUN yum -y install oracle-release-el7 && \
    yum-config-manager --enable ol7_oracle_instantclient && \
    yum -y install oracle-instantclient${VERSION}-basiclite && \
    rm -rf /var/cache/yum
```

**6. What is your Oracle Database version?**
`11.2.0.4.0`, `12.1.0.2.v18`

**7. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?  On macOS, what is in `~/lib`?**
`LD_LIBRARY_PATH` is set internally by the Docker image from above; unset on macOS.
`~/lib` only contains `libclntsh.dylib` on Mac.

**8. What environment variables did you set?  How *exactly* did you set them?**
`TNS_ADMIN=/` inside the Docker image. The `/` folder contains only `sqlnet.ora` with `sqlnet.encryption_client = required`.

**9. What compiler version did you use?**
CGO bundled with Go `1.13.7`.

**Comment by cjbj** [comment]
Are you able to test with Python cx_Oracle?

**Comment by dinvlad** [comment]
Will do later tonight, thanks!

**Comment by dinvlad** [comment]
Sorry for the delay - I don't have the same problem with `cx_Oracle`. I.e. when I specify `port=xxxxx` on my Mac, the notifications still get received. So this might be a problem specific to `godror`, after all.

**Comment by anthony-tuininga** [comment]
Closing as this is likely specific to godror. See [other issue](https://github.com/godror/godror/issues/22) for additional information.
