### ISSUE TITLE
extern "C" {...} for C++

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#129]
`dpi.h` must be included as follows in C++ source files to avoid [C++ name mangling](https://en.wikipedia.org/wiki/Name_mangling#C++).
```c++
extern "C" {
#include <dpi.h>
}
```
Could you use [this idiom](https://en.wikipedia.org/wiki/Name_mangling#Handling_of_C_symbols_when_linking_from_C++) to allow C++ files to include `dpi.h` without `extern "C" {...}` as follows?
```c++
#include <dpi.h>
```

**Comment by anthony-tuininga** [comment]
I've added the changes as requested. Let me know if they work for you. The only question I have is whether someone already added the ```extern "C"`` idiom whether this addition will cause their code to fail?

**Comment by kubo** [comment]
Thanks. It works.

> The only question I have is whether someone already added the extern "C" idiom whether this addition will cause their code to fail?

No.
