### ISSUE TITLE
Changing the default encoding to UTF-8

### ISSUE THREAD

**Issue by anthony-tuininga** [oracle/odpi#132]
This discussion began with cx_Oracle on issue [409](https://github.com/oracle/python-cx_Oracle/issues/409) where a suggestion was made to change the default encoding to UTF-8. Currently ODPI-C uses the `NLS_LANG` and `NLS_NCHAR` environment variables by default unless an encoding is specified. If these environment variables are not set, then the ASCII encoding is used, which is not helpful in many cases. Examining the drivers using ODPI-C, however, all of them (except cx_Oracle) use UTF-8 either as the default or as the only encoding supported. As such, I am now planning on changing the default encoding to UTF-8 and removing support for the use of the `NLS_LANG` and `NLS_NCHAR` environment variables. If there is a good reason for not doing so, however, I would love to hear from you. Please comment below.

**Comment by cjbj** [comment]
I'd still like to have further discussion on whether the national character set default should be UTF-8 or follow the DB default and use UTF-16

**Comment by anthony-tuininga** [comment]
UTF-16 has the "endianness" problem, which could potentially be a problem when translating from a big endian server to a little endian client -- or vice versa, of course! In addition, not all languages have particularly good support for UTF-16. As such I'd suggest using UTF-8 for the national character set as well. I can perform some testing next week to see if there is any notable performance difference between the two -- but for the reasons given above I'd suggest not using UTF-16.

**Comment by ddevienne** [comment]
FWIW, we've always configured the server to use AL32-UTF8, and ditto for the client, given that anything else can result in data-loss on round-trips. Default as UTF8 sounds like a safe bet to me.

**Comment by kubo** [comment]
I think that encodings of drivers using ODPI-C depends on the specification of the language targeted by the drivers. When the language's string representation is UTF-8, it is reasonable to use UTF-8 as the only Oracle client encoding. In that case, character encoding is converted at most once between Oracle server and client. If non-UTF-8 is used as the client encoding, characters must be convert additionally. So rust-oracle uses UTF-8.

> As such, I am now planning on changing the default encoding to UTF-8 and removing support for the use of the NLS_LANG and NLS_NCHAR environment variables.

I don't hit on real-world use cases to need the NLS environment variables except compatibility. So changing the default encoding to UTF-8 seems reasonable for fail safe. However could you leave an option to use the NLS environment variables just in case? For example when an empty string is set to encoding, NLS_LANG is used.

**Comment by anthony-tuininga** [comment]
> However could you leave an option to use the NLS environment variables just in case? For example when an empty string is set to encoding, NLS_LANG is used.

That sounds like a reasonable idea. The default would be UTF-8, but deliberately picking an empty string would result in the use of NLS_LANG. @cjbj, what do you think?

**Comment by anthony-tuininga** [comment]
ODPI-C 4.0 was just released.
