### ISSUE TITLE
oci.dll not loader in windows with node-oracledb

### ISSUE THREAD

**Issue by robsonkades** [oracle/odpi#139]
it looks like it's not using the correct bar for the operating system

`
ODPI [16304] 2020-07-01 13:03:51.509: load in dir C:\oracle\instantclient_19_6
ODPI [16304] 2020-07-01 13:03:51.513: load with name C:\oracle\instantclient_19_6/oci.dll
ODPI [16304] 2020-07-01 13:03:51.545: load by OS failure: The specified module could not be found
c:\test\node_modules\oracledb\lib\oracledb.js:142
`

**C:\\oracle\\instantclient_19_6/oci.dll**

maybe I found the problem.
https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1912
or 
https://github.com/oracle/odpi/blob/master/src/dpiOci.c#L1805

I don't know the language C

Issue origin https://github.com/oracle/node-oracledb/issues/1270

@anthony-tuininga

**Comment by anthony-tuininga** [comment]
The second one is specific to non-Windows platforms. The first one should not be an issue, though, as Windows no longer minds forward slashes in directory paths. You can do this for example:

```
notepad c:/myDocs/myDoc.txt
notepad c:\mydocs/myDoc.txt
```

Both of those will be acceptable. See my other comment on the node-oracledb issue for what may be the issue. I'll rerun my tests again tomorrow to make sure that something else hasn't come in to cause problems. Let me know the results of your own tests. Thanks!

**Comment by robsonkades** [comment]
Resolved!
