### ISSUE TITLE
App crashes when acquiring connection from pool

### ISSUE THREAD

**Issue by leflabs** [oracle/odpi#14]
Hello,

I what to use the driver in a multithreaded project. So I created a pool and I am acquiring a connection from the pool in order to create a statement and then to execute this statement. However the code crashes when sending multiple request (via an http interface). It never crashes so far when sending the requests one by one.
The method where the crash begins is:
```
int test_method( ... , *context ) {
  if (dpiPool_acquireConnection(pool, NULL, 0, NULL, 0, NULL, &conn) < 0 )
        return ShowError(context);
 
    if( conn ) {
            dpiConn_release(conn) ;
     }
}

```
and the pool is created like this

  ```
 dpiErrorInfo errorInfo;
    dpiContext *context;

    if (dpiContext_create(DPI_MAJOR_VERSION, DPI_MINOR_VERSION, &context, &errorInfo) < 0) {
        return -1;
    }
    dpiCommonCreateParams commonParams;
    dpiPoolCreateParams createParams;

    dpiPool *pool;

    if (dpiContext_initCommonCreateParams(context, &commonParams) < 0) {
        std::cout << "cannot init common params" << std::endl;
        return 1;
    }
    commonParams.createMode = DPI_MODE_CREATE_THREADED;

    if (dpiContext_initPoolCreateParams(context, &createParams) < 0)
    {
        std::cout << "cannot init the params" << std::endl;
        return 1; //dpiTestCase_setFailedFromError(testCase);
    }
    createParams.minSessions = 50; //MINSESSIONS;
    createParams.maxSessions = 100; //MAXSESSIONS;
    createParams.sessionIncrement = 20; //SESSINCREMENT;

    if (dpiPool_create(context, "DB", strlen("DB"),
            "DB", strlen("DB"), "1.7.7.16:1521/DEV",
            strlen("1.7.7.16:1521/DEV"), NULL, &createParams,  &pool) < 0)
        return 1; //dpiTestCase_setFailedFromError(testCase);
```

Is there a problem with the way I am creating the pool or the problem is one the way I am acquiring the connection?

I am working with oracle 12c in a Linux machine, and as I said the app works w/o problem when the requests are made sequentially.

**Comment by anthony-tuininga** [comment]
Your call to dpiPool_create() is not passing the &commonParams you just created -- and threaded mode is definitely required! That would explain things quite well. :-)

**Comment by leflabs** [comment]
OK, I found it works well know. Thank you very much.

**Comment by anthony-tuininga** [comment]
Glad to be of help!
