### ISSUE TITLE
Get record, not by column.

### ISSUE THREAD

**Issue by mrwaynedev** [oracle/odpi#142]
I've been working on a project in which we use odpi-c to fetch data and use it as plain text.
I've seen that in odpi-c the data is only accessed by position (column), also that I 've to define n variables for each column.
Would you be so kind as to tell me if there is any way to fetch the record directly? something like dpi_stmt_get_record?

thanks!!!

**Comment by anthony-tuininga** [comment]
There is no way currently to fetch into a structure. Each column is managed independently. If that is something you would like to see you can change this to an enhancement request!

**Comment by mrwaynedev** [comment]
Thanks for the answer. I'd like to see that, so I'll create the enhancement request.
