### ISSUE TITLE
thread-safe API

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#147]
Given a valid Pool, is `dpiPool_acquireConnection()` thread-safe?
Given a valid connection acquired from a Pool, is `dpiConn_close()` thread-safe?

**Comment by cjbj** [comment]
In a threaded environment set `DPI_MODE_CREATE_THREADED` in `createMode` E.g. https://github.com/oracle/python-cx_Oracle/blob/master/src/cxoSessionPool.c#L92

**Comment by felipenoris** [comment]
Thans, @cjbj !
