### ISSUE TITLE
ER: Arm64/Aarch64 support

### ISSUE THREAD

**Issue by junior** [oracle/odpi#157]
**Is your feature request related to a problem? Please describe.**
Trying to build for Arm64/aarch64 generates an undefined error. Oracle Instant Client supports Arm64 for some time now and the whole market is going to this path, either on the Cloud(linux/arm64) or on the Client (Apple's M1, Raspberry PIs, and others). Right now, just Java allow that, and people would prefer to change the DB instead to change from NodeJs or Go to Java, which is not going to happen.

**Describe the solution you'd like**
godror support for Arm64 platforms

**Describe alternatives you've considered**
No alternatives. when trying to build on arm64 platform the errors are always the same:

NodeJs and Golang, which depends on ODPi are failing

**Comment by anthony-tuininga** [comment]
What error are you getting when compiling ODPI-C? I don't personally have access to such a platform but I may still be able to help you along if you provide more information.

**Comment by cjbj** [comment]
Please share your error and environment when building ODPI.

I had not seen problems on Oracle Linux when I tested some time back,.

**Comment by cjbj** [comment]
@junior any update?

At a data point: here is someone using cx_Oracle (which uses ODPI-C just like godror) on ARM: https://twitter.com/GeraldVenzl/status/1390007812630061057

**Comment by junior** [comment]
Looks like the error was on the godror module to connect go to Oracle Db. Will test with NodeJs as well.

**Comment by junior** [comment]
Closing. Doing right, works Golang and NodeJs with respective drivers ([godror](https://github.com/godror/godror/) and [node-oradb](https://github.com/oracle/node-oracledb))) works perfectly on Arm64, and is simpler to compile than some guides around.
