### ISSUE TITLE
Default branch renaming to "main" this week

### ISSUE THREAD

**Issue by cjbj** [oracle/odpi#158]
Letting you know that ODPI-C's default branch will be renamed to "main" this week.

**Comment by anthony-tuininga** [comment]
This was just completed a few moments ago. Please update your local repositories or re-clone as appropriate.

**Comment by cjbj** [comment]
As per the pop-up instructions:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
