### ISSUE TITLE
Releasing Enq / Deq options

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#159]
It looks like  we just have to call `dpiQueue_getDeqOptions` and `dpiQueue_getEnqOptions` from a given queue to create an instance for Deq and Enq options. After that, calling *setter functions* (`dpiDeqOptions_setCondition` for instance) will change its properties.

Do we have to call `dpiEnqOptions_release` or `dpiDeqOptions_release` to release the options instance? Looks like it segfaults if I try to do that.

**Comment by anthony-tuininga** [comment]
No, you should not do so! I can add a note to the documentation to make that clearer.
