### ISSUE TITLE
Commit 292d09bdf breaks dpiDeqOptions_getWait and dpiMsgProps_getNumAttempts

### ISSUE THREAD

**Issue by CraZySacX** [oracle/odpi#16]
The changes to the `dpiDeqOptions__getAttrValue` function where the valueLength is checked for null cause the `dpiDeqOptions_getWait` call to always fail because the valueLength is hardcoded to NULL.  

```
int dpiDeqOptions_getWait(dpiDeqOptions *options, uint32_t *value)
{
    return dpiDeqOptions__getAttrValue(options, DPI_OCI_ATTR_WAIT, __func__,
   value, NULL);
}
```

Similar case in `dpiMsgProps`
```
int dpiMsgProps_getNumAttempts(dpiMsgProps *props, int32_t *value)
{
    return dpiMsgProps__getAttrValue(props, DPI_OCI_ATTR_ATTEMPTS, __func__,
            value, NULL);
}
```

Those two fell out of my tests, but a quick glance at some other functions where a numeric is the out value have the same issue.

**Comment by anthony-tuininga** [comment]
Oops. I'll get that corrected. Thanks for reporting it!

**Comment by anthony-tuininga** [comment]
This has been corrected. I've added some test cases in the cx_Oracle test suite to ensure this problem doesn't turn up again. Thanks again.
