### ISSUE TITLE
correlation String lifetime

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#160]
After I get a string value using `dpiMsgProps_getCorrelation`, what is the lifetime of the byte string pointer? Is it a new allocation, or is it a reference to a `dpiMsgProps` attribute that will be released when `dpiMsgProps_release` gets called?

**Comment by anthony-tuininga** [comment]
It is a reference to an internal attribute which will be valid for the lifetime of the `dpiMsgProps` object itself.

**Comment by felipenoris** [comment]
Alright! Thanks!
