### ISSUE TITLE
6 years later, still a pain to install...

### ISSUE THREAD

**Issue by ionutale** [oracle/odpi#161]
i worked with this lib 6 years ago, and it was a pain to install.
6 years later, still a pain...

and i know this is not the maintainer, but the oracle rules and licence...

_i just felt the need to complain as is a horrible experience_

**Comment by tgulacsi** [comment]
What is horrible?

With Go (github.com/godror/godror) I've just  embedded the .h and .c files, and it Just Works, no library is needed!
(Not even Instant Client, which is also much nicer nowadays, as it can be just downloaded).

**Comment by ionutale** [comment]
hi @tgulacsi 
My apologies i am on the wrong repo, 
I ment to complain about this repo https://github.com/oracle/node-oracledb.
Which after 6 years i was expecting it to work, exactly  like it does in go github.com/godror/godror.

but no, it still needs manual install of the drivers... not even a shell file ...

**Comment by cjbj** [comment]
A shell file would be two lines: wget & unzip.

Over the last 6 years there have been lots of improvements, from being able to build without installing anything (as @tgulacsi noted), to no-click through downloads, to being able to set the library location in app at runtime (admittedly not on Linux). The team you are complaining to is the team working with all the various stakeholders and trying to make things better for you.

**Comment by ionutale** [comment]
Hi, so after 6 year i finally manage to convince my company to move to Linux from Windows.
I was following this guide and had issues: https://oracle.github.io/node-oracledb/INSTALL.html#-32-node-oracledb-installation-on-linux
today i found this guide: https://oracle.github.io/node-oracledb/INSTALL.html#3214-install-the-free-oracle-instant-client-basic-zip-file
and this one actually works great, people with Linux, on first install, should be directed on the second link.

Anyway, sorry for my first 2 messages, i was frustrated for my inability to make it work, while all i had to do is just to scroll a bit down.
----
@cjbj one more thing:  i know how much you worked on Oracledb driver, i have seen your first commits timestamps, i know how much time you dedicated and i respect you.
My issues was with oracle way-of-doing, but that is another topic.
