### ISSUE TITLE
Is there a reference example dequeue message with message ID dequeue option

### ISSUE THREAD

**Issue by eugene-vodyanko** [oracle/odpi#167]
1. What version of ODPI-C are you using (see dpi.h)?
ODPI-C v4.3.0

2. What OS (and version) is your application on?
OS: win
Architecture: x86_64
Version: 10

3. What compiler (and version) did you use?
TODO

4. What is your version of the Oracle Client (e.g. Instant Client)?  How was it installed?  Where it is installed?
11.2.0.4

5. What is your Oracle Database version?
11.2.0.4

6. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?
TODO

7. What environment variables did you set?  How *exactly* did you set them?
TODO

8. What problem or error(s) you are seeing?
Get ORA-25263 (no message in queue) when try dequeue message with message ID dequeue option while using (godror go driver).

9. Do you have a runnable code snippet to describe the problem?
How it all started: please take a look relevant issue: https://github.com/godror/godror/issues/201

**Comment by cjbj** [comment]
We are checking with the AQ team.

**Comment by cjbj** [comment]
@eugene-vodyanko I do suggest you try with a more recent version of Oracle.

**Comment by eugene-vodyanko** [comment]
Thanks for your answer.
What do you mean: Oracle Server or Oracle Client?
By the way, I repeated the test on the server (Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production), but without success.

**Comment by cjbj** [comment]
I mean both newer Oracle client libraries & DB server, e.g. 19c  Or 21c!

**Comment by eugene-vodyanko** [comment]
Unfortunately, there is no such possibility at the moment. 
Do I understand correctly that at 19c and 21c, the dequeue of a message from the queue with setting the MsgID is guaranteed to work correctly?

Is the opposite true that the dequeue of a message from the queue with the MsgID does not work correctly in versions below 12?

**Comment by cjbj** [comment]
I have not tested and cannot say - I was hoping you could check your actual testcase with a recent.  I do know that 11.2 is _very_ old.

**Comment by eugene-vodyanko** [comment]
OK, thanks for your time. 
I will return to this issue as soon as I get the environment with the new versions at my disposal and report the test results.
