### ISSUE TITLE
M1 Mac issue ( incompatible architecture)

### ISSUE THREAD

**Issue by philip-mok** [oracle/odpi#169]
The instant client has no arm64e build , is there any way to work around the issue?
'/usr/local/lib/libclntsh.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by cjbj** [comment]
See related discussions like https://github.com/oracle/node-oracledb/issues/1349

**Comment by philip-mok** [comment]
Thanks! It is the dead end and we could only waiting for oracle porting team to solve this issue, I switch to a intel mac to continue my development.
