### ISSUE TITLE
Rust bindings over ODPI

### ISSUE THREAD

**Issue by CraZySacX** [oracle/odpi#17]
Looks like you have new implementations announcements here, so I'll toss mine in the mix.

https://github.com/rustyhorde/mimir

Still a work in progress, but the initial implementation is complete.  Needs documentation.

**Comment by anthony-tuininga** [comment]
Thanks! Let me know if/when you would like me to include a reference to it in the top-level documentation containing drivers that are implemented using ODPI-C.

**Comment by cjbj** [comment]
@CraZySacX Nice!  @kubo did a bit of work too, but has decided not to use Rust https://github.com/kubo/rust-oracle-wip

**Comment by kubo** [comment]
I restarted [rust oracle](https://github.com/kubo/rust-oracle) this month.
I'll publish oracle 0.1.0 to [crates.io](https://crates.io/) in a few weeks.
I'm now writing documents and changing code to fit the documents.
