### ISSUE TITLE
How to use ODPI-C with Oracle Times Ten?

### ISSUE THREAD

**Issue by junaidriaz** [oracle/odpi#170]
1. What version of ODPI-C are you using (see dpi.h)?
4.1.0-dev

2. What OS (and version) is your application on?
CentOS 7

3. What compiler (and version) did you use?
gcc 4.8.5

4. What is your version of the Oracle Client (e.g. Instant Client)?  How was it installed?  Where it is installed?
11.2

5. What is your Oracle Database version?
Oracle Times Ten 11.2

6. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?
LD_LIBRARY_PATH:/usr/local/lib/:/etc/TimesTen/tt1122/lib:/etc/TimesTen/tt1122/ttoracle_home/instantclient_11_2:

7. What environment variables did you set?  How *exactly* did you set them?
LD_LIBRARY_PATH and UV_THREADPOOL_SIZE

8. What problem or error(s) you are seeing?
ORA-12547: TNS:lost contact

9. Do you have a runnable code snippet to describe the problem?
Can be produced.

**Comment by cjbj** [comment]
I see you set UV_THREADPOOL_SIZE.  Is your problem with a C application or node-oracledb?

**Comment by junaidriaz** [comment]
It is my C application.

**Comment by junaidriaz** [comment]
@cjbj Do I need to build ODPI-C with Times Ten specific instant client and header files? 
I could not find any guide related to ODPI-C with Times Ten. I have seen [this](https://docs.oracle.com/database/timesten-18.1/TTOSL/TTOSL.pdf) for node js. 
I suppose any other application using ODPI-C should also be able to connect and use Times Ten.

**Comment by cjbj** [comment]
ODPI-C doesn't rely on any Oracle client headers.  

Try with an updated TimesTen:   https://docs.oracle.com/database/timesten-18.1/TTOSL/toc.htm#TTOSL102

BTW, if you're not using Node.js then there is no need to set UV_THREADSIZE_POOL, which is used by Node.js itself.

**Comment by junaidriaz** [comment]
@cjbj Sure, let me try with updated Times Ten.

Actually, I am using LibUV in combination with ODPI-C in my application for DB operations.

**Comment by cjbj** [comment]
@junaidriaz sounds like a cool app.  Drop me a line and let me know more about it.

**Comment by junaidriaz** [comment]
@cjbj Sure, Let me send you an email.
