### ISSUE TITLE
Oracle Rust driver

### ISSUE THREAD

**Issue by Swe77** [oracle/odpi#173]
Can you create an official Oracle Rust driver please?

As I work in a company that makes extensive use of Oracle databases, it would be excellent having a Oracle Rust driver.

**Comment by cjbj** [comment]
Use [rust-oracle](https://github.com/kubo/rust-oracle) created by the wonderful @kubo who also maintains the [ruby-oci8 driver](https://github.com/kubo/ruby-oci8).

**Comment by Swe77** [comment]
Ok, thank you.
