### ISSUE TITLE
Bytes after nul in members of dpiXid are zeroed.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#175]
ODPIC 4.3.0

https://github.com/oracle/odpi/blob/515a426239cfbd37d9446def11d0c5f8f1bb808b/src/dpiConn.c#L1343-L1348

`xid->globalTransactionId` and `xid->branchQualifier` are copied by `strncpy`. Bytes after a nul byte are zeroed. Shouldn't it be `memcpy`?

In the [man page of `strncpy`](http://manpages.ubuntu.com/manpages/bionic/en/man3/strncpy.3.html):
>  If the length of _src_ is less than _n_, **strncpy()** writes additional null  bytes  to  _dest_  to  ensure that a total of _n_ bytes are written.

Well, if global transaction id and branch qualifier must not contain null, this isn't a bug.

**Comment by anthony-tuininga** [comment]
Thanks, Kubo. Its not stricly a bug as it is extremely unlikely that an embedded NULL character would be passed and it is uncertain what would happen in the database if one was. Nevertheless, memcpy() is the safer approach anyway, so I changed it!

**Comment by kubo** [comment]
Thanks for fixing.
