### ISSUE TITLE
Is DPI_TPC_END_SUSPEND an undocumented flag in the OCI manual?

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#176]
The third argument `flags` of `dpiConn_tpcEnd` is passed to the the third argument of `OCITransDetach`. ([here](https://github.com/oracle/odpi/blob/515a426239cfbd37d9446def11d0c5f8f1bb808b/src/dpiConn.c#L2589-L2600) and [here](https://github.com/oracle/odpi/blob/515a426239cfbd37d9446def11d0c5f8f1bb808b/src/dpiOci.c#L4184-L4191))

The former must be `DPI_TPC_END_NORMAL(0)` or `DPI_TPC_END_SUSPEND(0x00100000)`.

In the [ODPI-C manual](https://oracle.github.io/odpi/doc/functions/dpiConn.html#c.dpiConn_tpcEnd):
> flags [IN] – one of the values from the enumeration [dpiTpcEndFlags](https://oracle.github.io/odpi/doc/enums/dpiTpcEndFlags.html#dpitpcendflags).

In dpi.h:
```c
// two-phase commit (flags for dpiConn_tpcEnd())
typedef uint32_t dpiTpcEndFlags;
#define DPI_TPC_END_NORMAL                          0
#define DPI_TPC_END_SUSPEND                         0x00100000
```

On the other hand, the third argument of `OCITransDetach` must be `OCI_DEFAULT(0)` according to the OCI manual. There are no flags corresponding to `DPI_TPC_END_SUSPEND`. Is it an undocumented flag?

In the [OCI manual](https://docs.oracle.com/en/database/oracle/oracle-database/21/lnoci/transaction-functions.html#GUID-03AB7BAB-C8F0-4DFF-BD10-7CE0F3C8CE09):
> **flags (IN)**
>
>    You must pass a value of OCI_DEFAULT for this parameter.

**Comment by cjbj** [comment]
I'll take a look when I'm back from vacation.

**Comment by cjbj** [comment]
When we did the TPC project we identified a few Oracle doc corrections.  Mentioning `OCI_TRANS_NOMIGRATE` for `OCITransDetach()` was on the list.  I'll chase up.  Thanks for checking with us.

**Comment by kubo** [comment]
Thanks. I got it.
