### ISSUE TITLE
dpiEnqOptions_setVisibility and dpiLob_getType are listed not in round_trips.rst

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#178]
1. What is the link to the documentation section that needs improving?
   
   https://github.com/oracle/odpi/blob/main/doc/src/user_guide/round_trips.rst

2. Describe the confusion
   
   `dpiEnqOptions_setVisibility` and `dpiLob_getType` are not listed in `round_trips.rst`.

3. Suggest changes that would help

    Add `dpiEnqOptions_setVisibility` and `dpiLob_getType`.

**Comment by cjbj** [comment]
@kubo your attention to detail is appreciated.  Thank you.  We'll update the doc.

**Comment by anthony-tuininga** [comment]
This has been included in ODPI-C 4.4. Thanks, Kubo!
