### ISSUE TITLE
Get column name for position

### ISSUE THREAD

**Issue by lovetodream** [oracle/odpi#179]
1. Describe your new request in detail

Similar to `dpiStmt_getQueryValue`, it would be very handy to have a function to get the column name at a specific position of a statement.

2. Give supporting information about tools and operating systems.  Give relevant product version numbers

not relevant

**Comment by tgulacsi** [comment]
Maybe I don't understand the question, but ain't dpiStmt_getQueryInfo enough?

**Comment by lovetodream** [comment]
Oh yes, this is exactly what I needed. I didn't recognize it somehow.
