### ISSUE TITLE
dbName and instanceName in dpiConnInfo and SQL in the doc

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#185]
1. What is the link to the documentation section that needs improving?

   In https://odpi-c.readthedocs.io/en/latest/structs/dpiConnInfo.html#c.dpiConnInfo.dbName

   > This is the same value returned by the SQL expression `SELECT NAME FROM V$DATABASE.`

   In https://odpi-c.readthedocs.io/en/latest/structs/dpiConnInfo.html#c.dpiConnInfo.instanceName

   > This is the same value returned by the SQL expression `SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME') FROM DUAL`.

2. Describe the confusion

   The members are not same with the values returned by the SQL.
   In the following environment, `dbName` and `instanceName` values are lowercase characters `free`.
   On the other hand  the SQL statements print uppercase ones `FREE`. 

   Environment: Oracle Database 23ai Free 23.5.0.24.07
   ```
   $ docker image list
   REPOSITORY                                    TAG       IMAGE ID       CREATED         SIZE
   container-registry.oracle.com/database/free   latest    e1ff84cf03ed   3 months ago    9.45GB
   ```
   C code
   ```c
   #include <stdio.h>
   #include <string.h>
   #include "dpi.h"
   
   int main()
   {
     const char *username = "odpic";
     const char *password = "welcome";
     const char *connStr = "127.0.0.1/FREEPDB1";
     dpiContext *context;
     dpiErrorInfo errorInfo;
     dpiConn *conn;
     dpiVersionInfo versionInfo;
     dpiConnInfo info;

     dpiContext_create(DPI_MAJOR_VERSION, DPI_MINOR_VERSION, &context, &errorInfo);
     dpiContext_getClientVersion(context, &versionInfo);
     printf("client version: %d.%d.%d.%d.%d\n", versionInfo.versionNum,
            versionInfo.releaseNum, versionInfo.updateNum, versionInfo.portReleaseNum,
            versionInfo.portUpdateNum);
     dpiConn_create(context, username, strlen(username), password, strlen(password), connStr, strlen(connStr), NULL, NULL, &conn);
     dpiConn_getInfo(conn, &info);
     printf("dbname: %.*s\n", info.dbNameLength, info.dbName);
     printf("instance_name: %.*s\n", info.instanceNameLength, info.instanceName);
     return 0;
   }
   ```
   Output of the above C code
   ```
   client version: 23.5.0.24.7
   dbname: free
   instance_name: free
   ```
   Output of SQL
   ```
   SQL> SELECT NAME FROM V$DATABASE;
   
   NAME
   ---------
   FREE
   
   SQL> SELECT SYS_CONTEXT('USERENV', 'INSTANCE_NAME') FROM DUAL;
   
   SYS_CONTEXT('USERENV','INSTANCE_NAME')
   --------------------------------------------------------------------------------
   FREE
   ```

3. Suggest changes that would help

   The values are case-insensitive?

**Comment by cjbj** [comment]
Thanks for the suggested correction.  We'll address it.

**Comment by cjbj** [comment]
@kubo check the doc now.  @priyankanair8 kept it simple.

**Comment by kubo** [comment]
Checked.

Thanks for the improvement.
