### ISSUE TITLE
Connect to ASM instance via ODPI-C and call a stored procedure

### ISSUE THREAD

**Issue by zhuhui6-lang** [oracle/odpi#188]
1. What version of ODPI-C are you using (see dpi.h)?
5.4.1
2. What OS (and version) is your application on?
CentOS7
3. What compiler (and version) did you use?
8.3.1
4. What is your version of the Oracle Client (e.g. Instant Client)?  How was it installed?  Where it is installed?
instantclient_19_18
5. What is your Oracle Database version?
19c
6. What is the `PATH` environment variable (on Windows) or `LD_LIBRARY_PATH` (on Linux) set to?
7. What environment variables did you set?  How *exactly* did you set them?
8. What problem or error(s) you are seeing?
I saw in the documentation that it supports connecting to ASM instances, but when I tried, I found that I couldn't connect. My current requirement is to find a C/C++ library that supports connecting to ASM instances and calling stored procedures within ASM.
![image](https://github.com/user-attachments/assets/217635da-b899-47bc-bce0-8a845fbd483b)
9. Do you have a runnable code snippet to describe the problem?
As follows.
```c++
int main(int argc, char** argv) {

    {
        // 测试执行存储过程
        char * sql = "BEGIN dbms_diskgroup.getfileattr(:1, :2, :3, :4); END;";
        dpiContext *context = nullptr;
        dpiConn *connection = nullptr;
        dpiErrorInfo *error = nullptr;
        dpiStmt *ps = nullptr;
        dpiData in, *outValue1, *outValue2, *outValue3;
        dpiVar *outVal1, *outVal2, *outVal3;
        uint32_t columnNums;
        char *inParam = "+DATA/P19C0/ONLINELOG/group_2.263.1185906387";

        // 初始化 DPI 环境
        if (dpiContext_create(5, 1, &context, error) != DPI_SUCCESS) {
            dpiContext_getError(context, error);
            std::cerr << "Error creating DPI context:" << error->message << std::endl;
        }

        // 创建数据库连接
        int status = dpiConn_create(context, "klrasm as sysasm", strlen("klrasm as sysasm"), "klrasm", strlen("klrasm"),
                                    "192.168.12.137:1521/+ASM", strlen("192.168.12.137:1521/+ASM"), nullptr, nullptr, &connection);
        if (status != DPI_SUCCESS) {
            dpiContext_getError(context, error);
            std::cerr << "Error creating connection:" << error->message << std::endl;
        }

        std::cout << "Connected to Oracle Database![odpi-c] -> " <<  status << std::endl;
        status = dpiConn_ping(connection);
        std::cout << "ping:" << status << std::endl;

        status = dpiConn_prepareStmt(connection, 0, sql,strlen(sql),nullptr, 0, &ps);
        std::cout << "stmt:" << status << std::endl;

        // 绑定输入和输出参数
        in.isNull = 0;
        in.value.asBytes.ptr = inParam;
        in.value.asBytes.length = strlen(inParam);
        status = dpiStmt_bindValueByPos(ps, 1, DPI_NATIVE_TYPE_BYTES, &in);
        std::cout << "bind in param:" << status << std::endl;

        status = dpiConn_newVar(connection, DPI_ORACLE_TYPE_NUMBER, DPI_NATIVE_TYPE_INT64, 1,
                       0, 0, 0, nullptr, &outVal1, &outValue1);
        std::cout << "create out param1:" << status << std::endl;
        status = dpiStmt_bindByPos(ps, 2, outVal1);
        std::cout << "bind out param1:" << status << std::endl;

        status = dpiConn_newVar(connection, DPI_ORACLE_TYPE_NUMBER, DPI_NATIVE_TYPE_INT64, 1,
                                0, 0, 0, nullptr, &outVal2, &outValue2);
        std::cout << "create out param2:" << status << std::endl;
        status = dpiStmt_bindByPos(ps, 3, outVal2);
        std::cout << "bind out param2:" << status << std::endl;

        status = dpiConn_newVar(connection, DPI_ORACLE_TYPE_NUMBER, DPI_NATIVE_TYPE_INT64, 1,
                                0, 0, 0, nullptr, &outVal3, &outValue3);
        std::cout << "create out param3:" << status << std::endl;
        status = dpiStmt_bindByPos(ps, 4, outVal3);
        std::cout << "bind out param3:" << status << std::endl;

        status = dpiStmt_execute(ps, DPI_MODE_EXEC_DEFAULT, &columnNums);
        if (status == DPI_FAILURE) {
            dpiContext_getError(context, error);
            std::cerr << "Error call proc:" << error->message << std::endl;
        }
        std::cout << "call proc:" << status << std::endl;

        //std::string result(outValue1->value.asBytes.ptr, outValue1->value.asBytes.length);
        std::cout << "out value1:" << outValue1->value.asInt64 << std::endl;
        std::cout << "out value2:" << outValue2->value.asInt64 << std::endl;
        std::cout << "out value3:" << outValue3->value.asInt64 << std::endl;

        // 关闭连接
        dpiVar_release(outVal1);
        dpiStmt_release(ps);
        dpiConn_release(connection);
        dpiContext_destroy(context);
    }

    return 0;
}
```

**Comment by cjbj** [comment]
What error are you getting?

**Comment by cjbj** [comment]
And are you running your app on the machine hosting the DB?

**Comment by zhuhui6-lang** [comment]
> And are you running your app on the machine hosting the DB?

Sorry, sir, the code I pasted earlier was incorrect. I have re-edited it. My current development setup is Windows + Linux, and I am using CLion for remote development. I am able to connect to the ASM instance using the same connection information via JDBC, but it seems that the C++ side cannot connect.
![image](https://github.com/user-attachments/assets/a5aa2820-4977-4acf-8a41-f5a82c3f90d6)

**Comment by zhuhui6-lang** [comment]
So what I actually want to ask is whether our ODPI library supports connecting to ASM instances. If it doesn't, then everything is normal...

**Comment by tgulacsi** [comment]
Why do you insert pure text as image?

Please handle the errors, do NOT continue!
(Maybe even the context creation was unsuccessful, but you cut that part of the screenshot)

**Comment by zhuhui6-lang** [comment]
> Why do you insert pure text as image?
> 
> Please handle the errors, do NOT continue! (Maybe even the context creation was unsuccessful, but you cut that part of the screenshot)

Gentlemen, currently I am focused on whether the ODPI library supports direct connection to an ASM instance. From the documentation, it seems to be supported (the version [Version 2.0.0-beta.1] mentions this), so I tried it, but it seems like the connection is not working at all. Also, the screenshot of my code only shows a little bit because the failure actually occurs when trying to obtain the connection, and the error pointer is null, so I don't know why I can't retrieve the error message, which causes the program to stop directly.

**Comment by kubo** [comment]
> the error pointer is null, so I don't know why I can't retrieve the error message

See code in the samples directory:
https://github.com/oracle/odpi/blob/v5.4.0/samples/SampleLib.c#L318-L322

**Comment by zhuhui6-lang** [comment]
> > the error pointer is null, so I don't know why I can't retrieve the error message
> 
> See code in the samples directory: https://github.com/oracle/odpi/blob/v5.4.0/samples/SampleLib.c#L318-L322

Thank you, sir. I have adjusted the way errors are printed, and now I can see the full error message. Based on the error, it seems that the odpi library does not support connecting to an ASM instance...
![image](https://github.com/user-attachments/assets/42627514-b5d4-455f-b937-78f554c6cd2f)

**Comment by zhuhui6-lang** [comment]
Thank you all for your help. At the moment, I am eager to know whether the odpi library supports direct connection to an ASM instance. I have seen some related information in the documentation, so I am still holding onto a bit of hope...

**Comment by kubo** [comment]
I've not written programs connecting to ASM. The followings are just a guess.

1. Use "klrasm" as username instead of  "klrasm as sysasm".
2. Initialize `dpiConnCreateParams` by `dpiContext_initConnCreateParams`  as https://github.com/oracle/odpi/blob/v5.4.0/samples/DemoAppContext.c#L70.
3. Set `DPI_MODE_AUTH_SYSASM` to the `authMode` member of `dpiConnCreateParams`.
4. Pass `dpiConnCreateParams` to `dpiConn_create` as https://github.com/oracle/odpi/blob/v5.4.0/samples/DemoAppContext.c#L74-L77.

**Comment by zhuhui6-lang** [comment]
> I've not written programs connecting to ASM. The followings are just a guess.
> 
> 1. Use "klrasm" as username instead of  "klrasm as sysasm".
> 2. Initialize `dpiConnCreateParams` by `dpiContext_initConnCreateParams`  as https://github.com/oracle/odpi/blob/v5.4.0/samples/DemoAppContext.c#L70.
> 3. Set `DPI_MODE_AUTH_SYSASM` to the `authMode` member of `dpiConnCreateParams`.
> 4. Pass `dpiConnCreateParams` to `dpiConn_create` as https://github.com/oracle/odpi/blob/v5.4.0/samples/DemoAppContext.c#L74-L77.

I tried the method you provided, and I was able to connect to the ASM instance. Thank you very much!

**Comment by cjbj** [comment]
Thanks @kubo !
