### ISSUE TITLE
mismatch of parameter names in  function prototypes and tables in doc

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#189]
1. What is the link to the documentation section that needs improving?
2. Describe the confusion

   I found two types of issues when I made a script picking up function descriptions from ODPI-C doc.

   The first is that some parameter names in function prototypes aren't same with that in the table about the functions.

   For example:
   ![dpiConn_getTransactionInProgress](https://github.com/user-attachments/assets/0540b6a2-4310-4886-838b-0183f7944aa3)

   There are 6 mismatched names including the above.

   function name | name in function  prototype | name in table
   ---|---|---
   `dpiConn_getTransactionInProgress` | `txnInProgress` | `value`
   `dpiData_setIntervalDS` | `fsceconds` | `fseconds`
   `dpiJson_getValue` | `value` | `json`
   `dpiPool_reconfigure` | `maxSesssions` | `maxSessions`
   `dpiSodaColl_dropIndex` | `nameLength` | `indexSpecLength`
   `dpiVector_setValue` | `json` | `vector`

   The second is that some parameters are duplicated.

   * Two  `connectStringLength` in  [`dpiPool_create`](https://odpi-c.readthedocs.io/en/latest/functions/dpiPool.html#c.dpiPool_create)
   * Two `nativeTypeNum` in [`dpiObject_getAttributeValue`](https://odpi-c.readthedocs.io/en/latest/functions/dpiObject.html#c.dpiObject_getAttributeValue)

3. Suggest changes that would help

**Comment by cjbj** [comment]
The attention to detail is appreciated.

**Comment by anthony-tuininga** [comment]
Since this is all documentation, the changes will be made available shortly. Thanks for the clear report!

**Comment by kubo** [comment]
Confirmed. Thank you!
