### ISSUE TITLE
more data type information about object types

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#23]
Could you add precision and scale members to dpiObjectAttrInfo and dpiObjectTypeInfo?
dpiOracleTypeNum is in dpiObjectAttrInfo, dpiObjectTypeInfo and dpiQueryInfo structures. However precision and scale are only in dpiQueryInfo.
Language bindings may refer these members to determine data types in its language.
For example if a member of an object type is `NUMBER(20)`, a language binding may get the data as integer. (I'm making [ruby-odpi](https://github.com/kubo/ruby-odpi), which is not a replacement of ruby-oci8. I'm doing it just to know ODPI.)

I prefer to make a structure as follows and put it in dpiObjectAttrInfo, dpiObjectTypeInfo and dpiQueryInfo. But I could not imagine use cases using size and nullOk members except just information for users as in the https://github.com/oracle/odpi/issues/22#issue-248156269 example. So I don't adhere to my idea.
```C
struct dpiDataTypeInfo
    dpiOracleTypeNum oracleTypeNum;
    dpiNativeTypeNum defaultNativeTypeNum;
    uint32_t dbSizeInBytes;
    uint32_t clientSizeInBytes;
    uint32_t sizeInChars;
    int16_t precision;
    int8_t scale;
    int nullOk;
    dpiObjectType *objectType;
};
```

**Comment by anthony-tuininga** [comment]
I'll take a look and will implement this suggestion if there aren't any difficulties in doing so!

**Comment by kubo** [comment]
Thank you! I'm looking forward to it.

**Comment by anthony-tuininga** [comment]
I created the structure dpiDataTypeInfo as suggested. Thanks! It made sense. The nullOk member is only relevant for queries (not object attributes and collection elements) but the other members all do make sense, and it simplified the code a fair bit, too. Take a look and let me know if that answers your request.

**Comment by kubo** [comment]
Thank you!

When I wrote the dpiDataTypeInfo, I didn't realize that nullOK is unavailable for object attributes and collection elements. Sorry to bother you, but could you remove the nullOk member from the dpiDataTypeInfo and put it back to dpiQueryInfo? I think that it is better. Well, if my request looks inappropriate, feel free to reject it.

I found a related potential bug.
In dpiStmt__getQueryInfoFromParam, DPI_OCI_HTYPE_DESCRIBE is used as the handle type of the param value. Though it works, it should be DPI_OCI_DTYPE_PARAM because the param is got from [OCIParamGet](https://docs.oracle.com/database/122/LNOCI/handle-and-descriptor-functions.htm#LNOCI17136).

**Comment by anthony-tuininga** [comment]
> When I wrote the dpiDataTypeInfo, I didn't realize that nullOK is unavailable for object attributes and collection elements. Sorry to bother you, but could you remove the nullOk member from the dpiDataTypeInfo and put it back to dpiQueryInfo? I think that it is better.

Agreed. I looked at the documentation and it is explicitly forbidden on object attributes and collection elements -- so I have moved it back as suggested. Thanks.

> I found a related potential bug. In dpiStmt__getQueryInfoFromParam, DPI_OCI_HTYPE_DESCRIBE is used as the handle type of the param value. Though it works, it should be DPI_OCI_DTYPE_PARAM because the param is got from OCIParamGet.

It does indeed work so I'll ask about what the correct code ought to be when I ask about the precision attributes, too. Thanks for your feedback.

**Comment by kubo** [comment]
Thank you!
What I want was added.
