### ISSUE TITLE
Compiling samples and tests.

### ISSUE THREAD

**Issue by braulio** [oracle/odpi#24]
Hello.

I'm trying to compile the samples and tests and error occurs:

Make
Gcc -c -I ../ include -O2 -g -Wall -obuild / TestContext.TestContext.c
Gcc -c -I ../ include -O2 -g -Wall -obuild / TestLib.o TestLib.c
Gcc -L ../ lib -lodpic -ldl build / TestContext.o -obuild / TestContext build / TestLib.o
Build / TestContext.o: in function `dpiTest_100_validMajorMinor ':
/odpi/test/TestContext.c:35: undefined reference to `dpiContext_create '
/odpi/test/TestContext.c:38: undefined reference to `dpiContext_destroy '
...

OS: Ubuntu 16.4,
InstantClient: /usr/lib/oracle/12.2/client64/lib

Any tips?
Thank you.

**Comment by anthony-tuininga** [comment]
Did you build the ODPI-C library? In other words, did you run make in the main directory first?

**Comment by kubo** [comment]
I have noticed same issue.
Makefiles in samples and test directories don't work on Linux.

> gcc -L../ lib -lodpic -ldl build/TestContext.o -obuild/TestContext build/TestLib.o

`-lodpic -ldl` must be after `.o` files. Otherwise, functions in `.o` files could not be resolved.
Conventionally `-L../ lib -lodpic -ldl` are set to `LIBS` not to `LDFLAGS`.

@braulio Could you post command output as it is? When it is not exactly what you get, it is unreliable.

**Comment by anthony-tuininga** [comment]
> Makefiles in samples and test directories don't work on Linux.

They work for me! @kubo, @braulio, does the changed order eliminate the problem? I can easily adjust the order if that is the case.

**Comment by kubo** [comment]
I'm using Ubuntu 16.04, gcc 5.4.0, binutils 2.26.1.
Moving `$(LDFLAGS)` to the end of the `$(LD)` line fixes the problem.

before:
```shell
$ make
mkdir build
gcc -c -I../include -O2 -g -Wall -obuild/TestBLOB.o TestBLOB.c
gcc -c -I../include -O2 -g -Wall -obuild/SampleLib.o SampleLib.c
gcc -L../lib -lodpic -ldl build/TestBLOB.o -obuild/TestBLOB build/SampleLib.o
build/TestBLOB.o: In function `main':
/home/kubo/src/odpi/samples/TestBLOB.c:45: undefined reference to `dpiConn_prepareStmt'
/home/kubo/src/odpi/samples/TestBLOB.c:48: undefined reference to `dpiStmt_execute'
/home/kubo/src/odpi/samples/TestBLOB.c:50: undefined reference to `dpiStmt_release'
...
```
after:
```shell
$ make
mkdir build
gcc -c -I../include -O2 -g -Wall -obuild/TestBLOB.o TestBLOB.c
gcc -c -I../include -O2 -g -Wall -obuild/SampleLib.o SampleLib.c
gcc build/TestBLOB.o -obuild/TestBLOB build/SampleLib.o -L../lib -lodpic -ldl
gcc -c -I../include -O2 -g -Wall -obuild/TestCLOB.o TestCLOB.c
gcc build/TestCLOB.o -obuild/TestCLOB build/SampleLib.o -L../lib -lodpic -ldl
gcc -c -I../include -O2 -g -Wall -obuild/TestFetch.o TestFetch.c
gcc build/TestFetch.o -obuild/TestFetch build/SampleLib.o -L../lib -lodpic -ldl
...
```

**Comment by braulio** [comment]
Perfect, Kubo. You're right. I moved the $ (LDFLAGS) to the end of the line and it worked.

Thank you my friends.

**Comment by braulio** [comment]
Kubo, can you help me with this one? Libodpic.so is in odpi/lib.
./TestSuiteRunner: error while loading shared libraries: libodpic.so: cannot open shared object file: No such file or directory.
Thank you.

**Comment by anthony-tuininga** [comment]
> ./TestSuiteRunner: error while loading shared libraries: libodpic.so: cannot open shared object file: No such file or directory.

You need to set LD_LIBRARY_PATH so that it finds the library, as in:

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../../lib ./TestSuiteRunner

**Comment by anthony-tuininga** [comment]
I have moved the libraries to the end of the link line as suggested and also renamed the variable to $(LIBS). @kubo, please take a look and make sure it matches what you are expecting and that it works for you now! Thanks.

**Comment by braulio** [comment]
OK, Anthony. 
Thanks.

**Comment by kubo** [comment]
Thanks for your prompt commit! It worked for me.

Well, could you change as follows?
from:
```
LIBS=//nologo ../lib/odpic.lib
```
to
```
LDFLAGS=//nologo
LIBS=../lib/odpic.lib
```
from:
```
	$(LD) $< $(EXE_OUT_OPTS)$@ ... $(LIBS)
```
to:
```
	$(LD) $(LDFLAGS) $< $(EXE_OUT_OPTS)$@ ... $(LIBS)
```
LDFLAGS is for linker options except libraries.
LIBS is for libraries.

**Comment by anthony-tuininga** [comment]
I have included your suggestion, @kubo. I think this can be closed now. Thanks for your help!
