### ISSUE TITLE
DPI_NATIVE_TYPE_UINT64 is handled as signed int.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#3]
When a dpiVar is created with `DPI_NATIVE_TYPE_UINT64` and `DPI_ORACLE_TYPE_NATIVE_INT`, it is defined or bound as `SQLT_INT`. It should be `SQLT_UIN`.
When a dpiVar is created with `DPI_NATIVE_TYPE_UINT64` and `DPI_ORACLE_TYPE_NUMBER`, `OCINumberFromInt()` and `OCINumberToInt` are called with `OCI_NUMBER_SIGNED`. It should be `OCI_NUMBER_UNSIGNED`.

**Comment by anthony-tuininga** [comment]
@kubo Thanks. I'll address these.
