### ISSUE TITLE
 init 0 for last byte for padding terminator

### ISSUE THREAD

**Issue by Taymindis** [oracle/odpi#31]
Please init 0 for last byte while initialize xxx->value.asBytes.ptr. It always display the weird thing at the last character. For example
strIngColval->value.asBytes.ptr[strIngColval->value.asBytes.length] = 0;

**Comment by Taymindis** [comment]
I have tried select some data and display by using  xxx->value.asBytes.ptr, some is empty some is invalid character comeout

**Comment by cjbj** [comment]
Can you show us your code? (Use a [gist](https://gist.github.com/)).
Have you looked at the samples?

**Comment by kubo** [comment]
If the data are printed as `printf("xxx value is: %s\n",  xxx->value.asBytes.ptr)`, use `printf("xxx value is: %.*s\n",  xxx->value.asBytes.length, xxx->value.asBytes.ptr)` instead.

**Comment by anthony-tuininga** [comment]
Kubo has it right. Almost all of the strings in ODPI-C use pointer/length semantics, not null-termination. This is to handle encodings like UTF-16. Unless otherwise stated, you should assume that there is no null byte terminating strings.

**Comment by Taymindis** [comment]
Just tested Kubo Suggestion, it is working fine now.
