### ISSUE TITLE
Make libodpic.so depend on libdl and libpthread on Unix.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#33]
Could you add `LIBS=-ldl -lpthread` to [`Makefile`](../blob/master/Makefile) and remove `-ldl -lpthread` in `test/Makefile` and `samples/Makefile`?

When libodpic.so depends on libdl and libpthread, there is no need to link with `-ldl -lpthread` to build programs depending on libodpic.so.

**Comment by anthony-tuininga** [comment]
I'll take a look. Makes sense to me, though!

**Comment by anthony-tuininga** [comment]
Suggestion implemented. Thanks!
