### ISSUE TITLE
Could not get object type attribute number as int64 or bytes

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#35]
Object type attribute number could be get as double but not as int64 or bytes.

I made a test program.
https://gist.github.com/kubo/aea497d746d3d1603882c86b450accc0

It printed:
```
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_DOUBLE
  => 1
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_INT64
  => ERROR: DPI-1014: conversion between Oracle type 2010 and native type 3000 is not implemented
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_BYTES
  => ERROR: DPI-1014: conversion between Oracle type 2010 and native type 3004 is not implemented
```
What I want is:
```
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_DOUBLE
  => 1
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_INT64
  => 1
Getting ObjectCol.NumberValue as DPI_NATIVE_TYPE_BYTES
  => 1
```

**Comment by anthony-tuininga** [comment]
Thanks for the example. I don't see any reason not to implement the additional conversions as requested so will do that at some point!

**Comment by anthony-tuininga** [comment]
Conversion added as requested. Note that you must provide the buffer for conversion to text -- unlike with variables where this is done for you. The length of the buffer provided needs to be found in value.asBytes.length and after completion will contain the actual length. I also added support for DPI_NATIVE_TYPE_UINT64.

**Comment by kubo** [comment]
Thank you!
Could you fix document about dpiObjectType_getAttributes also?

**Comment by anthony-tuininga** [comment]
I have adjusted the documentation as suggested. Thanks.
