### ISSUE TITLE
query re api stability

### ISSUE THREAD

**Issue by jmcp** [oracle/odpi#42]
While preparing the Solaris Userland (https://github.com/oracle/solaris-userland) integration
of ODPI-C, one of my code reviewers asked about the stability of the API. 

* Is it anticipated that there will be incompatible changes to the API in future?
* Is it anticipated that customers might want to have multiple versions of this library installed?

#### Answer the following questions:

1. What version of ODPI-C are you using (see dpi.h)?

2.0.2

2. What error(s) you are seeing?

None

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

n/a

4. What environment variables did you set?  How *exactly* did you set them?

n/a

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

12.1 and 12.2, via IPS packages

6. What is your OS and version?

Solaris 11.4 and 11.3

7. What compiler version did you use?

gcc 5.4

**Comment by cjbj** [comment]
Answers are yes & yes. The stated compat is in: https://oracle.github.io/odpi/doc/public_functions/dpiContext.html#c.dpiContext_create
