### ISSUE TITLE
soname in libodpic.so

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#44]
Do you have any plan to add [soname](https://en.wikipedia.org/wiki/Soname) such as `libodpic.so.2`?

* Link `libodpic.so` with `-hlibodpic.so.2` linker flag.
* Install `libodpic.so` as `libodpic.so.2.0.x`.
* Make two symbolic links `libodpic.so.2` and `libodpic.so` which point to `libodpic.so.2.0.x`.
* When the major version is changed to 3, the soname is also changed to `libodpic.so.3`.

Soname gets it anticipated that customers might want to have incompatible versions such as ODPI-C 2.x and ODPI-C 3.x installed. (the second question in #42)

**Comment by anthony-tuininga** [comment]
Yes, it would be a good idea to add soname at some point as you suggest. Thanks.

**Comment by kubo** [comment]
@anthony-tuininga Thanks for the commit.

Could you change `ln -s $< $@` in [this line](https://github.com/oracle/odpi/blob/84be55e45266d6b03a0599b5efbfc13a5467c6e3/Makefile#L115) and [this line](https://github.com/oracle/odpi/blob/84be55e45266d6b03a0599b5efbfc13a5467c6e3/Makefile#L118) as follows respectively?
```
	ln -fs $(FULL_LIB_NAME) $@
```
```
	ln -fs $(VERSION_LIB_NAME) $@
```

When `$@` exists and the `-f` option isn't set, the `ln` command fails:
```
$ sudo make install
...omitted...
$ touch lib/libodpic.so
$ sudo make install
install lib/libodpic.so /usr/local/lib/libodpic.so.2.4.0
ln -s /usr/local/lib/libodpic.so.2.4.0 /usr/local/lib/libodpic.so.2
ln: failed to create symbolic link '/usr/local/lib/libodpic.so.2': File exists
Makefile:115: recipe for target '/usr/ocal/lib/libodpic.so.2' failed
```

`ln -s $< $@` commands make symbolic links to full path.
```
$ cd /usr/local 
$ ls -l libodpic.so.*
lrwxrwxrwx 1 root root     28 Jun  3 15:19 libodpic.so -> /usr/local/lib/libodpic.so.2
lrwxrwxrwx 1 root root     32 Jun  3 15:19 libodpic.so.2 -> /usr/local/lib/libodpic.so.2.4.0
```
However symbolic links in `/usr/lib` don't use full path usually.

When the commands are changed as above:
```
$ cd /usr/local 
$ ls -l libodpic.so.*
lrwxrwxrwx 1 root root     13 Jun  3 15:19 libodpic.so -> libodpic.so.2
lrwxrwxrwx 1 root root     17 Jun  3 15:19 libodpic.so.2 -> libodpic.so.2.4.0
```

**Comment by cjbj** [comment]
That seems logical. I verified the change - not that @kubo needs verifying!

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. Changes integrated. Thanks for the explanation as well!
