### ISSUE TITLE
Texts retrieved by FormatMessage on Windows

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#47]
Some issues about FormatMessage used [here](https://github.com/oracle/odpi/blob/v2.0.3/src/dpiOci.c#L1363) on Windows
I might have to create separate issues. But some issues are related so I put all in one.

#### A potential bug

The 6th argument `FormatMessageW` is `sizeof(wLoadError)` but it should be `sizeof(wLoadError)/sizeof(wchar_t)` because the argument is the number of characters, not bytes, allocated for the 5th argument.

#### Message is incorrectly stripped on Japanese.

Trailing period and carriage return are stripped [here](https://github.com/oracle/odpi/blob/v2.0.3/src/dpiOci.c#L1372-L1374). However, when the last character before carriage return is a multi-byte character, the character is broken. It should be stripped only when it is really period.

#### Message language

The error message retrieved by `FormatMessageW` depends on the OS language. Could you change the messages to English or add a compile-time option to change it?
The message is changed to English when the 4th argument is `MAKELANGID(LANG_ENGLISH, SUBLANG_DEFAULT)`.

Programs in the samples directory print garbled text in Japanese Windows command prompt when OCI.DLL is not found. If the message language is English, it isn't garbled.

#### Add error number to the message

When the message isn't changed to English, could you add the error number to the message?
For example when the error code is 126:
```
DPI-1047: 64-bit Oracle Client library cannot be loaded: Win32 error 126: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help
```

When an issue is posted with a localized error message and you don't know the language, you cannot read the message. Moreover if it is garbled as messages in Japanese Windows command prompt, nobody read it. If the error number is included in the text, you can know the error as follows.
```
DPI-1047: 64-bit Oracle Client library cannot be loaded: Win32 error 126: "指定されたモジュールが見つかりません。". See https://oracle.github.io/odpi/doc/installation.html#windows for help
```

**Comment by anthony-tuininga** [comment]
Since these are all in the same area of code it makes sense to deal with them at once. Thanks, @kubo.

**Comment by kubo** [comment]
> The message is changed to English when the 4th argument is MAKELANGID(LANG_ENGLISH, SUBLANG_DEFAULT).

Node.js uses `MAKELANGID(LANG_ENGLISH, SUBLANG_ENGLISH_US)`. If it fails, it uses `0`, which equals `MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT)`.
https://github.com/nodejs/node/blob/v9.2.0/deps/uv/src/win/dl.c#L104-L115

**Comment by anthony-tuininga** [comment]
I've pushed a commit that should resolve these issues. Let me know. Thanks!

**Comment by kubo** [comment]
Thank you! It solved these issues.
I found a bug in the commit. Trailing period and carriage return are not stripped.
See https://github.com/oracle/odpi/commit/0fc9751a695866fb116914f7cbe4e0c2dcec0cf4#r25996466.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. I have resolved that logic error as well. Not sure how I missed that!

**Comment by kubo** [comment]
Thanks!
All these issues were solved.
