### ISSUE TITLE
DPI_ORACLE_TYPE_LONG_NVARCHAR?

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#5]
`LONG` corresponds to DPI_ORACLE_TYPE_LONG_VARCHAR.
`LONG RAW` corresponds to DPI_ORACLE_TYPE_LONG_RAW.
What Oracle data type corresponds to DPI_ORACLE_TYPE_LONG_NVARCHAR?

**Comment by anthony-tuininga** [comment]
I believe it was needed in the past to handle passing NVARCHAR data longer than 64K (for insertion into an NCLOB, for example) but that is no longer needed. If that is true, I'll drop the type to avoid confusion. Thanks for bringing it to my attention.

**Comment by anthony-tuininga** [comment]
The type has been dropped.
