### ISSUE TITLE
dpioci_errorGet crashes when encounter chinese characters(utf-8) in Windows debug mode.

### ISSUE THREAD

**Issue by a315558547** [oracle/odpi#52]
I'm using odpi-c2.1 version with oci11.2. My program crashes in function dpioci_errorGet function when it calls isspace(*ptr--) in line 1223(file dpioci.c).
Here is my test environments:
os: windows 7
ide visual studio 2010, debug mode, x64. multibyte charset
dpicommoncreateparams encoding UTF8, nencoding UTF8
windows environment varialbe NLS_LANG=SIMPLEFIED CHINESE_CHINA.AL32UTF8

**Comment by cjbj** [comment]
Can you post a [Gist](https://gist.github.com/) of a running example that crashes?

**Comment by a315558547** [comment]
I just use the "TestInsert.c" example, and I did not create testtemptable. When the example program call the function "dpistmt_execute", I got the errorinfo ora-00942(and some chinese characters), then the program will crashes when it process space characters when it calss isspace function.
I googled, isspace function just crashes in windows debug mode.

**Comment by kubo** [comment]
In https://msdn.microsoft.com/en-us/library/y13z34da.aspx
> The behavior of isspace and _isspace_l is undefined if c is not EOF or in the range 0 through 0xFF, inclusive. When a debug CRT library is used and c is not one of these values, the functions raise an assertion.

Add cast `(uint8_t)` as follows or change the data type of `ptr` to `uint8_t *` to avoid assertions.
```
    while (ptr > error->buffer->message && isspace((uint8_t)*ptr--))
```

**Comment by anthony-tuininga** [comment]
Curious! The type of the pointer is already char* which restricts the size from 0 through 0xFF already -- or am I missing something?

Can one of you verify that this cast actually resolves the issue? If it does I'm happy enough to make the change. :-)

**Comment by anthony-tuininga** [comment]
Got it. Thanks, @kubo.

**Comment by anthony-tuininga** [comment]
Can one of you verify that the commit I just made actually resolves the issue? It should, but confirmation would be appreciated! Thanks.

**Comment by kubo** [comment]
I verified it.
I added `/MDd` option to `cl` in `Makefile.win32` and `samples/Makefile.win32` and did the followings:

```
c:\odpi> nmake -f Makefile.win32
 ...
c:\odpi> cd samples
c:\odpi\samples> nmake -f Makefile.win32
 ...
c:\odpi\samples> chcp 65001
Active code page: 65001
c:\odpi\samples> set NLS_LANG=french_france.AL32UTF8
c:\odpi\samples> build\TestInsert.exe
ERROR: ORA-12541: TNS : pas de processus d'écoute (dpiConn_create: server attach)
FATAL: Unable to create connection.
```
It printed a non-ascii character `é`.

When the cast `(uint8_t)` was removed, it raised a message box: `Debug Assertion Failed!`.

**Comment by anthony-tuininga** [comment]
Thanks, @kubo. Based on this response I'll close this now.
