### ISSUE TITLE
Haskell Bindings over ODPI-C

### ISSUE THREAD

**Issue by leptonyu** [oracle/odpi#53]
Still working in progress, just complete basic function to access database. Planning to implements haskell persistent-adaptor using this raw lib.

https://github.com/leptonyu/odpic-raw

**Comment by cjbj** [comment]
Nice!  Thanks for sharing.

**Comment by cjbj** [comment]
@leptonyu you have a fan: https://twitter.com/jmerritt/status/957922328427425792
