### ISSUE TITLE
How can I get the error info when preparestmt failed?

### ISSUE THREAD

**Issue by leptonyu** [oracle/odpi#54]
I want catch the error info and throw it to the upper layer.

Debug log seems not fit for this.

**Comment by anthony-tuininga** [comment]
Yes, the debug log is not the place for this! You need to use the function [dpiContext_getError()](https://oracle.github.io/odpi/doc/public_functions/dpiContext.html#c.dpiContext_getError). You can see examples of how that is done in the [samples](https://github.com/oracle/odpi/blob/master/samples/SampleLib.c).

**Comment by leptonyu** [comment]
@anthony-tuininga is there any concurrency problem with this function  dpiContext_getError()?

and btw, can i get dpiContext directly from dpiConn or dpiStmt?

**Comment by anthony-tuininga** [comment]
ODPI-C manages errors for each thread that is executing so there is no concurrency problem. You can't get dpiContext from dpiConn or dpiStmt. It is assume that dpiContext will be a global variable in your program since you only require one of them and you need it to get error information as well.

**Comment by anthony-tuininga** [comment]
You can create as many dpiContext variables as you would like, but only one is necessary. Errors are handled in a thread safe manner so it doesn't matter how many connections or pools you create with a dpiContext variable. There isn't much overhead in dpiContext, so if you would prefer to create one for each connection or session pool you could certainly do that, too. But there is no need to do so!

**Comment by leptonyu** [comment]
Thank you. I got it.
