### ISSUE TITLE
Who has been using ODPI-C 2.2.0-dev?

### ISSUE THREAD

**Issue by cjbj** [oracle/odpi#55]
It seems about time to freeze 2.2.0.  Who's picked up 2.2.0-dev from master and validated it in their projects? Particularly the elimination of the DPI-1054 errors.  /cc @tgulacsi @kubo @CraZySacX @leptonyu

**Comment by tgulacsi** [comment]
Not yet - when last time I've tried to use it, it produced strange runtime errors.

It's still there:

acquireConnection[oracle://br_ktny:*****@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=lnx-dev-kbe.unosoft.local)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=kbe_tst.unosoft.local)))?connectionClass=POOLED&poolIncrement=1&poolMaxSessions=64&poolMinSessions=1&sysdba=0&sysoper=0]: ORA-00000: DPI-1013: not supported

**Comment by cjbj** [comment]
@tgulacsi strange indeed.  I was wondering why you'd rolled back. Can you set DPI_DEBUG_LEVEL to some value(s) e.g. 4 and upload a trace so @anthony-tuininga can take a look?

**Comment by tgulacsi** [comment]
ODPI [11649] 2018-02-06 07:39:31.135: ODPI-C 2.2.0-dev
ODPI [11649] 2018-02-06 07:39:31.135: debugging messages initialized at
level 4
ODPI [11649] 2018-02-06 07:39:31.136: fn start dpiContext_create
ODPI [11649] 2018-02-06 07:39:31.145: fn end dpiContext_create -> 0
ODPI [11649] 2018-02-06 07:39:31.146: fn start
dpiContext_initConnCreateParams(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.146: fn end
dpiContext_initConnCreateParams(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.146: fn start
dpiContext_initCommonCreateParams(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.146: fn end
dpiContext_initCommonCreateParams(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.146: fn start
dpiContext_initPoolCreateParams(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.146: fn end
dpiContext_initPoolCreateParams(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.146: fn start dpiPool_create(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.173: fn end dpiPool_create(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.173: fn start dpiPool_setTimeout(0x23c7630)
ODPI [11649] 2018-02-06 07:39:31.173: fn end dpiPool_setTimeout(0x23c7630)
-> 0
ODPI [11649] 2018-02-06 07:39:31.173: fn start
dpiPool_setMaxLifetimeSession(0x23c7630)
ODPI [11649] 2018-02-06 07:39:31.173: fn end
dpiPool_setMaxLifetimeSession(0x23c7630) -> -1
ODPI [11649] 2018-02-06 07:39:31.173: fn start
dpiPool_setStmtCacheSize(0x23c7630)
ODPI [11649] 2018-02-06 07:39:31.173: fn end
dpiPool_setStmtCacheSize(0x23c7630) -> 0
ODPI [11649] 2018-02-06 07:39:31.173: fn start
dpiContext_initConnCreateParams(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.173: fn end
dpiContext_initConnCreateParams(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.173: fn start
dpiPool_acquireConnection(0x23c7630)
ODPI [11649] 2018-02-06 07:39:31.191: fn end
dpiPool_acquireConnection(0x23c7630) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiContext_getClientVersion(0x23c7280)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiContext_getClientVersion(0x23c7280) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiConn_getServerVersion(0x2447eb0)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiConn_getServerVersion(0x2447eb0) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start dpiContext_create
ODPI [11649] 2018-02-06 07:39:31.192: fn end dpiContext_create -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiContext_getClientVersion(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiContext_getClientVersion(0x23c7600) -> 0
client: 11.2.0.4.0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiContext_initConnCreateParams(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiContext_initConnCreateParams(0x23c7600) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiContext_initCommonCreateParams(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiContext_initCommonCreateParams(0x23c7600) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start
dpiContext_initPoolCreateParams(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.192: fn end
dpiContext_initPoolCreateParams(0x23c7600) -> 0
ODPI [11649] 2018-02-06 07:39:31.192: fn start dpiPool_create(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.210: fn end dpiPool_create(0x23c7600) -> 0
ODPI [11649] 2018-02-06 07:39:31.210: fn start dpiPool_setTimeout(0x23c7570)
ODPI [11649] 2018-02-06 07:39:31.210: fn end dpiPool_setTimeout(0x23c7570)
-> 0
ODPI [11649] 2018-02-06 07:39:31.210: fn start
dpiPool_setMaxLifetimeSession(0x23c7570)
ODPI [11649] 2018-02-06 07:39:31.210: fn end
dpiPool_setMaxLifetimeSession(0x23c7570) -> -1
ODPI [11649] 2018-02-06 07:39:31.210: fn start
dpiPool_setStmtCacheSize(0x23c7570)
ODPI [11649] 2018-02-06 07:39:31.210: fn end
dpiPool_setStmtCacheSize(0x23c7570) -> 0
ODPI [11649] 2018-02-06 07:39:31.210: fn start
dpiContext_initConnCreateParams(0x23c7600)
ODPI [11649] 2018-02-06 07:39:31.210: fn end
dpiContext_initConnCreateParams(0x23c7600) -> 0
ODPI [11649] 2018-02-06 07:39:31.210: fn start
dpiPool_acquireConnection(0x23c7570)
ODPI [11649] 2018-02-06 07:39:31.210: fn end
dpiPool_acquireConnection(0x23c7570) -> -1
--- FAIL: TestObjectDirect (0.02s)
        obj_test.go:72:
acquireConnection[oracle://br_ktny:br_ktny@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=lnx-dev-kbe.unosoft.local)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=kbe_tst.unosoft.local)))?connectionClass=POOLED&poolIncrement=1&poolMaxSessions=4&poolMinSessions=1&sysdba=0&sysoper=0]:
ORA-00000: DPI-1013: not supported

The same happens with empty connectionClass, BUT not this without pooling.

Christopher Jones <notifications@github.com> ezt írta (időpont: 2018. febr.
6., K, 7:31):

**Comment by cjbj** [comment]
@tgulacsi what is the Oracle DB version?  Have you tried a 12c client?

**Comment by CraZySacX** [comment]
FWIW, I've been using the latest with no issue.

**Comment by kubo** [comment]
@cjbj 
I have not used 2.2.0-dev yet.
I'm pleased about the elimination of the DPI-1054. If the feature were not added, I would implement *cascading close* in ruby-odpi as ruby-oci8 does.

**Comment by anthony-tuininga** [comment]
@tgulacsi, the reason for your issues is because you have hard-coded the DpiMajorVersion and DpiMinorVersion in your library. Once I changed them to match (C.DPI_MAJOR_VERSION and C.DPI_MINOR_VERSION) the problems went away. The reason for that is that the structure size changed from 2.0 to 2.2 and you were claiming to still use 2.0!

**Comment by tgulacsi** [comment]
Thanks @anthony-tuininga , that was the issue!
It works now.

**Comment by cjbj** [comment]
@tgulacsi Anthony will improve the doc on this.

@CraZySacX Good work.

@kubo When you take up 2.2.0, I'm sure you'll let us know if there is something to be fixed!

**Comment by cemremengu** [comment]
Fails to build on windows?

I am using `goracle` and getting the following error after the update

```
In file included from go\src\github.com\go-goracle\goracle\odpi\embed/dpi.c:37:0,
                 from go\src\github.com\go-goracle\goracle\drv.go:48:
go\src\github.com\go-goracle\goracle\odpi\embed/../src/dpiOci.c: In function 'dpiOci__getLoadErrorOnWindows':
go\src\github.com\go-goracle\goracle\odpi\embed/../src/dpiOci.c:1485:38: error: 'ERROR_MUI_FILE_NOT_FOUND' undeclared (first use in this function)
     if (!status && GetLastError() == ERROR_MUI_FILE_NOT_FOUND)
                                      ^
go\src\github.com\go-goracle\goracle\odpi\embed/../src/dpiOci.c:1485:38: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by cjbj** [comment]
@cemremengu what version of Windows etc are you using?

**Comment by cemremengu** [comment]
The build process is done by `go build` which asks for `gcc`. Here is what I am using:

Windows 10 with

oracle client 
```TNS Ping Utility for 64-bit Windows: Version 12.2.0.1.0 - Production on 12-FEB-2018 13:04:38```

mingw gcc
```
$ gcc -v
Reading specs from c:/gcc/bin/../lib64/gcc/x86_64-w64-mingw32/4.8.3/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/gcc/bin/../libexec/gcc/x86_64-w64-mingw32/4.8.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-4.8.3/configure --prefix=/opt/windows_64 --with-sysroot=/opt/windows_64 --libdir=/opt/windows_64/lib64 --mandir=/opt/windows_64/man --infodir=/opt/windows_64/info --enable-shared --disable-bootstrap --disable-multilib --enable-threads=posix --enable-languages=c,c++ --enable-checking=release --enable-libgomp --with-system-zlib --with-python-dir=/lib64/python2.7/site-packages --disable-libunwind-exceptions --enable-__cxa_atexit --enable-libssp --with-gnu-ld --verbose --enable-java-home --with-java-home=/opt/windows_64/lib64/jvm/jre --with-jvm-root-dir=/opt/windows_64/lib64/jvm --with-jvm-jar-dir=/opt/windows_64/lib64/jvm/jvm-exports --with-arch-directory=amd64 --with-antlr-jar='/home/adrien/projects/win-builds-1.5/slackware64-current/d/gcc/antlr-*.jar' --disable-java-awt --disable-gtktest --build=x86_64-slackware-linux --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32
Thread model: posix
gcc version 4.8.3 (GCC)
```

I checked and only v2.0.3 succeeds v2.1.0 fails with the same error as well.

**Comment by anthony-tuininga** [comment]
I am using the following version of gcc: gcc version 7.3.0 (Rev1, Built by MSYS2 project) and did not have any difficulties. At a guess, you are using an older version of the Windows header files which does not define the manifest constant ERROR_MUI_FILE_NOT_FOUND. On my system it is defined inside winerror.h. Can you check and report back?

**Comment by cemremengu** [comment]
Got the latest `mingw-w64` with gcc 7.2.0 which solved the problem. Thanks so much for the help!

**Comment by cjbj** [comment]
A quick update: @anthony-tuininga tagged v2.2.0 to allow [node-oracledb](https://github.com/oracle/node-oracledb/)'s submodule use a nice 'clean' tag.  However he has a couple of tweaks needed for cx_Oracle that will soon land in ODPI-C v2.2.1.
