### ISSUE TITLE
"libclntsh.so" not found

### ISSUE THREAD

**Issue by UnitedMarsupials** [oracle/odpi#56]
I wanted to create a FreeBSD port. The odpi library compiled nicely with minimal changes.

The contents of `test/` subdirectory compiled just as nicely as well. Unfortunately, none of it is any good, because _using_ the open-sourced ODPI-C still requires OCI, which is not available in source form.

Maybe, it is time for Oracle to open source the OCI as well? Or, at least, make it available in binary form for a wider variety of Operating Systems? Once, many years ago, Oracle8 client was made available for FreeBSD (only for i386)... But it only offered static `libclntsh.a`.

#### Answer the following questions:

1. What version of ODPI-C are you using (see dpi.h)?

2.1 as of January 3 (the latest at this time)

2. What error(s) you are seeing?

```
FN: dpiContext_create
ACTION: load library
MSG: DPI-1047: 32-bit Oracle Client library cannot be loaded: "Shared object "libclntsh.so" not found, required by "TestTransactions"". See https://oracle.github.io/odpi/doc/installation.html#linux for help
FATAL: Unable to create initial DPI context.
```

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

`env LD_LIBRARY_PATH=../lib ./build/TestTransactions`

4. What environment variables did you set?  How *exactly* did you set them?

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?

There is not.

6. What is your OS and version?

FreeBSD-11.1-STABLE

7. What compiler version did you use?

gcc version 7.3.0 (FreeBSD Ports Collection)

**Comment by anthony-tuininga** [comment]
Unfortunately, ODPI-C **does** require the Oracle Client libraries. They simply aren't required when building, only at run-time. I doubt there will be much change on this front but I'll let @cjbj comment further if he wishes.

**Comment by cjbj** [comment]
The request is noted. I recently put some other comments on Instant Client in https://github.com/oracle/docker-images/issues/507#issuecomment-362463784

**Comment by UnitedMarsupials** [comment]
@cjbj, any updates 15 months later? I perfectly understand the desired to keep the _server_ code closed and otherwise protected, but why not open the source of the _client_?

**Comment by cjbj** [comment]
@UnitedMarsupials fundamentally it is a business decision made many levels of management above me.  There's a lot of IP in the client libraries (which, BTW, are also used by the DB server).

**Comment by UnitedMarsupials** [comment]
Of course, it is a business decision -- yet, you are many levels closer to those decision-makers, than I am :)
