### ISSUE TITLE
What's the default format for timestamp without timezone

### ISSUE THREAD

**Issue by leptonyu** [oracle/odpi#57]
I want to convert timestamp to utctime. but it seems that dpiTimestamp give me the localized time.
```Haskell
2018-02-13 11:03:13
-- i want following format
2018-02-13 03:03:13 UTC
```

Is this localized timezone depending on oracle database timezone or client's timezone?

**Comment by leptonyu** [comment]
https://stackoverflow.com/questions/17922106/different-current-timestamp-and-sysdate-in-oracle

**Comment by cjbj** [comment]
Also see https://docs.oracle.com/en/database/oracle/oracle-database/12.2/nlspg/datetime-data-types-and-time-zone-support.html#GUID-578B5988-31E2-4D0F-ACEA-95C827F6012B
