### ISSUE TITLE
Array enqueue function of advanced Queuing supported?

### ISSUE THREAD

**Issue by a315558547** [oracle/odpi#58]
I want to ask if the array enqueue function of advanced Queuing supported?

**Comment by anthony-tuininga** [comment]
It is not currently supported. If you would like it to be supported I can change this to an enhancement request and add it to the list of things to be considered.

**Comment by a315558547** [comment]
Yes, I need it for performance consideration. When using array enque and array deque, performance is 4x better than normal enque and deque in my environment.

**Comment by anthony-tuininga** [comment]
Ok. Thanks. I'll mark this as an enhancement request, then. :-)

**Comment by cjbj** [comment]
@a315558547 what is your environment - what DB version, are you using RAC etc?

**Comment by a315558547** [comment]
oracle 11.2, no RAC. centos7.2 x64,  ssd disk and so on

**Comment by anthony-tuininga** [comment]
I've just pushed some changes to ODPI-C to support array enqueue/dequeue. Please take a look and let me know if you have any feedback. Thanks!

**Comment by anthony-tuininga** [comment]
Support was added in 3.2.
