### ISSUE TITLE
Missing `install` rule in Makefile

### ISSUE THREAD

**Issue by segabor** [oracle/odpi#59]
I'm working on a [Homebrew](brew.sh) formula that makes it possible to install ODPI-C as a package on macOS. Unfortunately the provided Makefile misses install rule so I have to copy library and header files manually to their destination which is not the best way of doing such things. It is always expected to rely on Makefile when it already exist.

Please consider updating Makefile.
Thanks.

**Comment by anthony-tuininga** [comment]
Thanks for the suggestion!

**Comment by anthony-tuininga** [comment]
Do you have a suggestion on what the install rule should look like?

**Comment by jmcp** [comment]
On 15/02/18 04:24 am, Anthony Tuininga wrote:
> Do you have a suggestion on what the install rule should look like?

For Solaris, we patch the released Makefile with

https://github.com/oracle/solaris-userland/blob/master/components/odpi/patches/00-Makefile.patch

to get an install rule which puts the 32- and 64-bit libraries
as well as symlinks into usr/lib and usr/lib/64.


James

**Comment by cjbj** [comment]
@segabor is @jmcp's patch usable for you?

**Comment by segabor** [comment]
@anthony-tuininga, @cjbj let me check it out.

**Comment by segabor** [comment]
@jmcp thanks for sharing it. Looks good, but needs some tweaks in order to use on macOS. First off, I'm not quite expert in writing cross-platfom Makefiles. 

So my questions are
- your makefile contains references to InstantClient which is originally not needed. Why are they there?
- noticed a lib removal in LDFLAGS
- having different rules for 32/64 bit builds are cool.
- inlining macro defs are referenced with relative path. I did a quick research on my Mac but did not find shared-macros.mk. It is quite possible that I forgot to install a dependency although I have "make".

What I would need:
- customizable destination via PREFIX env variable defaulted to /usr/local path
- install lib into $PREFIX/lib, headers into $PREFIX/include, sample files into $PREFIX/share/odpi
- able to remove files from destination via "uninsall" command.

It would be good to find a common solution for all platforms but either we need to involve field experts or consider using tools like cmake to generate platform specific Makefile.

Gábor

**Comment by jmcp** [comment]
@segabor I'm glad that patch is useful for you. I'll answer your questions here:

- ODPI-C needs to be able to find the Instant Client bits; since Solaris ships the Instant Client in a Well-KnownLocation (/usr/oracle/instantclient/...) and we take the approach that our users shouldn't have to muck around with setting LD_LIBRARY_PATH etc, therefore we're baking in the rpath right from the start.

- Solaris' dynamic loading functionality is part of libc, and referred to as a "filter" library:

```
     $ elfdump -d /usr/lib/64/libdl.so

Dynamic Section:  .dynamic
    index  tag          value     
      [0]  FILTER       0x134       libc.so.1
      [1]  SONAME       0x129       libdl.so.1
      [2]  HASH         0x318       
      [3]  STRTAB       0x7c0       
      [4]  STRSZ        0x33e       
      [5]  SYMTAB       0x448       
      [6]  SYMENT       0x18        
      [7]  CHECKSUM     0x285f      
      [8]  VERDEF       0xb00       
      [9]  VERDEFNUM    0xa         
     [10]  SYMINFO      0x280       
     [11]  SYMINSZ      0x94        
     [12]  SYMINENT     0x4         
     [13]  SUNW_PHNAME  0xc9c       
     [14]  FLAGS        0           0
     [15]  FLAGS_1      0x20001100  [ DIRECT NODUMP WEAKFILTER ]
     [16]  SUNW_STRPAD  0x200       
     [17]  SUNW_LDMACH  0x3e        EM_AMD64
     [18-28]  NULL         0           
```

**Comment by anthony-tuininga** [comment]
I've added the requested support for installing the include file, the library and the samples and tests. This appears to work fine on both Linux and macOS. Let me know if any further changes ought to be made.

**Comment by segabor** [comment]
@anthony-tuininga thanks, checking it..

**Comment by segabor** [comment]
Default `make install` runs perfectly!
With custom PREFIX target it fails copying include files,

```bash
PREFIX=/opt/local make install
mkdir -p /opt/local/share/odpi/samples/sql
mkdir -p /opt/local/share/odpi/test/sql
install include/dpi.h /opt/local/include/dpi.h
install: /opt/local/include/dpi.h: No such file or directory
make: *** [/opt/local/include/dpi.h] Error 71
```
Can you please fix it?

Uninstall works fine even with custom PREFIX.
Thank you,

Gábor

**Comment by anthony-tuininga** [comment]
Should be fixed now. Added checks for the base include and library directories as well. Please confirm!

**Comment by segabor** [comment]
Tested on macOS, now everything looks good!
Thanks,

Gábor

**Comment by segabor** [comment]
@cjbj as a developer, I might want to see examples compile and link with the library provided with the package, even without using github repository. So there's nothing wrong with them if installed to share folder.

**Comment by cjbj** [comment]
@segabor do you want the tests too?

**Comment by segabor** [comment]
@cjbj I think examples are fine to be installed but anything that a developer can try out / learn is useful. I ran through the tests and they are quite similar to examples so they can be excluded. But they make no harm if they are installed along with the examples.

**Comment by cjbj** [comment]
I'm still of the mindset that there is a distinction between using and developing with ODPI-C.  Perhaps there should be two installation targets.
