### ISSUE TITLE
Long string converted from number corrupts memory.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#6]
ODPI-C defines `DPI_NUMBER_AS_TEXT_CHARS` as 135 in dpiImpl.h. However it is too short. It must be at least 170.

I made a test code and put it [here](https://gist.github.com/kubo/a4ea764a15044a0a8c1e57e0b1d3b6d8).
The following is the result.
```
define as DPI_ORACLE_TYPE_VARCHAR and DPI_NATIVE_TYPE_BYTES
  isNull=0x0
  len=170
  str=-.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009999999999999999999999999999999999999999

define as DPI_ORACLE_TYPE_NUMBER and DPI_NATIVE_TYPE_BYTES
  isNull=0x39393939
  len=960051553
  str=0x3939393939393939
```
When a number column `UTL_RAW.CAST_TO_NUMBER('7F0202020202020202020202020202020202020202')` is defined as DPI_ORACLE_TYPE_VARCHAR and DPI_NATIVE_TYPE_BYTES, it is fetched as a string whose length is 170.
When the same number is defined as DPI_ORACLE_TYPE_NUMBER and DPI_NATIVE_TYPE_BYTES, `isNull` is 0x39393939 and `str` is 0x3939393939393939. `isNull` must be either 0 or 1. It is apparently overwritten with "9999" (code point of '9' is 0x39). `str` is also overwritten with "99999999".

**Comment by anthony-tuininga** [comment]
@kubo Thanks. I have confirmed the issue. I found a string which is a little longer so have set the maximum length to 172 characters.
