### ISSUE TITLE
breakExecution (sometimes) has no effect

### ISSUE THREAD

**Issue by tgulacsi** [oracle/odpi#60]
One goracle user has experiencing problems with goracle Breaking the Execute on timeout:

Although dpiConn_breakExecution is called, the other thread is still stuck on dpiStmt_execute (https://github.com/go-goracle/goracle/issues/48#issuecomment-370626154)

The database is quite busy (https://github.com/go-goracle/goracle/issues/48#issuecomment-370984191), so I'm asking a general advice here: shall the goracle driver expect that Break won't have effect, and return with error, junking that session, or am I using breakExecution with bad assumptions?

**Comment by anthony-tuininga** [comment]
I'm not sure of the answer myself. Perhaps @cjbj has a better idea. I can try something similar with cx_Oracle, however, which also uses ODPI-C, and see if i get the same results.

**Comment by anthony-tuininga** [comment]
Can you clarify which version of the Oracle Client and Oracle Database are being used in your tests?

**Comment by rbastic2** [comment]
Hi,

I have commented on https://github.com/go-goracle/goracle/issues/48 on the behavior surrounding SQL*Net and break-resets. I did not see anything mentioned in the issue surrounding TNS configuration.

If this is not clear then I can try to add more detail. However, I'm not sure yet that this will help solve the user's issue.

Cheers,

**Comment by anthony-tuininga** [comment]
Thanks. That was helpful, and I hope the poster on goracle also finds it useful. :-)

**Comment by veqryn** [comment]
Our Oracle DB server is version 12.1.0.2
Our Golang Application is using Oracle Client 12.2.0.1 (from the docker container: container-registry.oracle.com/database/instantclient:12.2.0.1)
Our Perl Application (which is seeing similar problems) is using Oracle Client 12.1.0.2

I'd be happy to answer any further questions not already covered in https://github.com/go-goracle/goracle/issues/48

**Comment by cjbj** [comment]
This hasn't been forgotten but I don't have any update.

**Comment by tgulacsi** [comment]
As reported at https://github.com/go-goracle/goracle/issues/48#issuecomment-371924286 

```
DISABLE_OOB = on
BREAK_POLL_SKIP = 10
TCP.CONNECT_TIMEOUT = 390
SQLNET.RECV_TIMEOUT = 390
SQLNET.SEND_TIMEOUT = 390
SQLNET.INBOUND_CONNECT_TIMEOUT = 390
SQLNET.OUTBOUND_CONNECT_TIMEOUT = 390
SQLNET.EXPIRE_TIME = 8
```

in `sqlnet.ora` helped `dpiConn_breakExecution` in that bad network. Thanks for the suggestions!
