### ISSUE TITLE
Prefetch size - the comment contradicts the code

### ISSUE THREAD

**Issue by tgulacsi** [oracle/odpi#61]
https://github.com/oracle/odpi/blob/e4a722cf100c8e28a07abf97a06f4f28fdd6cd20/src/dpiStmt.c#L554-L557

The comment says "set the prefetch rows to the fetch array size", but the code sets the prefetch rows to the default prefetch rows count (2). Why not as the comment says? Why not configurable?

**Comment by anthony-tuininga** [comment]
Good catch. Thanks!
