### ISSUE TITLE
Can't run any of samples

### ISSUE THREAD

**Issue by DiegoFelipe** [oracle/odpi#63]
### For general questions:
Problem when running any of the builded samples, I installed oracle instant client from zip in the same folder of this odpi-c

#### Answer the following questions:

1. What version of ODPI-C are you using (see dpi.h)?
idk i downloaded it today by cloning github repository.

2. What error(s) you are seeing?
./TestFetch: error while loading shared libraries: libodpic.so.2: cannot open shared object file: No such file or directory

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?

4. What environment variables did you set?  How *exactly* did you set them?
export LD_LIBRARY_PATH=/home/diego-felipe/document_root/odpi/instantclient

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
instantclient 12.2 I followed the instructions here:
https://oracle.github.io/odpi/doc/installation.html

6. What is your OS and version?
Deepin 15.5

7. What compiler version did you use?
gcc version 6.4.0 20170724 (Debian 6.4.0-2)

**Comment by anthony-tuininga** [comment]
This issue was discovered yesterday and resolved in the release of ODPI-C 2.4 (which was also yesterday). You may need to do the following in the root directory of your ODPI-C repository:

```shell
make clean
make
cd samples
make clean
make
```

Let me know if that resolves the issue for you. Thanks!

**Comment by DiegoFelipe** [comment]
I just did it and got the same error

**Comment by anthony-tuininga** [comment]
Can you make sure that you have the latest code? Issue a git pull command to confirm. Can you also display the contents of the "lib" directory? It should look like this:

lrwxrwxrwx. 1 anthony anthony     13 Jun  7 09:31 libodpic.so -> libodpic.so.2
lrwxrwxrwx. 1 anthony anthony     17 Jun  7 09:31 libodpic.so.2 -> libodpic.so.2.4.0
-rwxrwxr-x. 1 anthony anthony 916880 Jun  7 09:31 libodpic.so.2.4.0

**Comment by anthony-tuininga** [comment]
Looks like that should work. Perhaps do an ldd on your built sample to make sure that it is using the right one? Perhaps you have another one somewhere else?

**Comment by DiegoFelipe** [comment]
what do you mean by "ldd on your built" ?

**Comment by DiegoFelipe** [comment]
oh sorry, there's my ldd :)

`	linux-vdso.so.1 (0x00007ffd347e5000)
	libodpic.so.2 => not found
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fad5fbc0000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fad60163000)

	Version information:
	./TestFetch:
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
`

**Comment by anthony-tuininga** [comment]
Ah! You need to set LD_LIBRARY_PATH to include the library directory. As in

export LD_LIBRARY_PATH=/my/odpi_dir/lib:$LD_LIBRARY_PATH

So that when you run ldd libodpic.so.2 will actually be found!

**Comment by DiegoFelipe** [comment]
hum, my LD_LIBRARY _PATH looks like this:
/home/diego-felipe/document_root/odpi/instantclient:/home/diego-felipe/document_root/odpi/instantclient/

**Comment by anthony-tuininga** [comment]
The directory I asked you to do an "ls" command on -- the one containing libodpic.so.2! This is explained in the README.md in the samples directory. Did you read it? :-)

**Comment by DiegoFelipe** [comment]
yes I noticed it and added the path to $LD_LIBRARY_PATH, but now I got the error of my last comment

**Comment by anthony-tuininga** [comment]
Oh, sure enough. :-) What does /home/diego-felipe/document_root/odpi/instantclient contain? There should be a libclntsh.so file in that directory. If not, find the one that contains your instant client and set LD_LIBRARY_PATH to that location. Also make sure that it is 64-bit. You can find out by running the file command. For example, in my system:

`file /share/oracle/app/product/12.2.0/lib/libclntsh.so`

gives the output

`/share/oracle/app/product/12.2.0/lib/libclntsh.so: symbolic link to libclntsh.so.12.1`

and using the same command on the linked file

`file /share/oracle/app/product/12.2.0/lib/libclntsh.so.12.1`

gives the output

`/share/oracle/app/product/12.2.0/lib/libclntsh.so.12.1: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=8d403aa8de583a94ddc775eecd02790a2dafb9e0, not stripped`

Note that it says 64-bit in the output. If it isn't, download the 64-bit version.

**Comment by DiegoFelipe** [comment]
Thanks so much for you time, now it's "working", I'm trying to run the ./TestFetch sample, but I got no idea about how to configure the connection, I'm getting ORA-12541 error
