### ISSUE TITLE
darwin: don't set install_name to pwd

### ISSUE THREAD

**Issue by flokli** [oracle/odpi#65]
Followup of #64 

1. What version of ODPI-C are you using (see dpi.h)?
cd9b3f7142dd458b39c37652ccf6afba7f482c6d (v2.4.0)

2. What error(s) you are seeing?
the Makefile currently uses `$(shell pwd)` to assemble `-install_name` argument for `LIB_OUT_OPTIONS`. This leads to problems, if builds are run in an ephemeral sandbox path, as that temporary path is baked into the library.

Suggested fix:

```
From 42762944772e938fecc5c366dd27b3890e9f642a Mon Sep 17 00:00:00 2001
From: Florian Klink <flokli@flokli.de>
Date: Fri, 8 Jun 2018 03:54:38 +0200
Subject: [PATCH] Makefile: darwin: don't set install_name to pwd

doing so introduces a dependency from libodpic.dylib to the ephemeral
sandbox path of libodpic.dylib:

result/lib/libodpic.dylib:
	/private/tmp/nix-build-odpic-2.4.0.drv-0/odpi-2.4.0/lib/libodpic.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/xn55wd7nimdi085kji54mrrqqnqvcasz-Libsystem-osx-10.11.6/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

Instead, keep the path relative
---
 Makefile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Makefile b/Makefile
index 7e18a23..44ff449 100644
--- a/Makefile
+++ b/Makefile
@@ -45,7 +45,7 @@ FULL_LIB_NAME = $(VERSION_LIB_NAME).$(MINOR_VERSION).$(PATCH_LEVEL)
 ifeq ($(shell uname -s), Darwin)
 	LIB_NAME = libodpic.dylib
 	LIB_OUT_OPTS = -dynamiclib \
-		-install_name $(shell pwd)/$(LIB_DIR)/$(LIB_NAME) \
+		-install_name $(LIB_DIR)/$(LIB_NAME) \
 		-o $(LIB_DIR)/$(FULL_LIB_NAME)
 else
 	LIB_NAME = libodpic.so
-- 
2.16.3

```

3. What *exact* command caused the problem (e.g. what command did you try to install with)?  Who were you logged in as?
`make PREFIX=\$\(out\) CC=cc LD=cc`
See build description too: https://github.com/flokli/nixpkgs/blob/3ebfb98490f75d9aed8de07a9ed5de64dd4ae014/pkgs/development/libraries/odpic/default.nix

4. What environment variables did you set?  How *exactly* did you set them?
exactly: 

5. What is your version of the Oracle client (e.g. Instant Client)?  How was it installed?  Where it is installed?
12.2.0.1.0

6. What is your OS and version?
Mac OSX (Sierra), using [Nix package manager](https://nixos.org/nix/)

7. What compiler version did you use?
```
cc --version
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by cjbj** [comment]
Thanks.  Out of interest, what are you using ODPI-C for?  Any feature requests?

**Comment by flokli** [comment]
@cjbj That was currently merely to get it to build properly through Nix on Darwin (which is being used by some devs, and I wanted to ease the pain in setting all up manually).

At the moment, it's just `sqlalchemy` using `cx_oracle` using `ODPI-C` (although I could imagine other usecases using `ODPI-C` more directly, possibly resulting in some feature requests too ;-)).

I do however have an architecture specific request - `ODPI-C` under Linux itself seems to be quite portable, but I'm currently missing the instantclient libraries for armv7l/aarch64 (and due to their binary nature, that's not something an outsider can fix). Maybe you know where to ask for that? ;-)

**Comment by cjbj** [comment]
@flokli you can ask me, but the decision is something upper management need to make - porting (and maintenance) is resource intensive.  Keeping gathering votes for it if you come across other users - this is useful for me to help get resources.

**Comment by flokli** [comment]
Will do - and please let me know if there are any questions regarding this issue :-)

**Comment by kubo** [comment]
I'm against the patch. If the patch is applied, programs using ODPI-C run only when `libodpic.dylib` is in `$HOME/lib`, `/usr/local/lib`, `/usr/lib`, `/lib` or a `lib` directory under **the current working directory**.

> the Makefile currently uses $(shell pwd) to assemble -install_name argument for LIB_OUT_OPTIONS. This leads to problems, if builds are run in an ephemeral sandbox path, as that temporary path is baked into the library.

@flokli What problem you encounter when temporary path is baked into the library? Nix seems to change the baked path [here](https://github.com/NixOS/nixpkgs/blob/a1b5b1a6/pkgs/build-support/setup-hooks/fix-darwin-dylib-names.sh#L26). (Well, I have not used Nix. My guess may be incorrect.)

Apart from Nix, the baked path including `pwd` causes the following problem.

1. Compile ODPI-C in `/tmp/odpi` and install it to `/opt/odpi`
    ```shell
    $ cd /tmp
    $ git clone https://github.com/oracle/odpi.git
    $ cd odpi
    $ make    #  /tmp/odpi/lib/libodpi.dylib is baked into libodpi.dylib.
    $ make install PREFIX=/opt/odpi
    ```

2. Create a program using files under `/opt/odpi`.
    ```shell
    $ cc -o program program.c -I/opt/opdi/include -L/opt/odpi/lib -lodpic
    $ otool -L program
    program:
	/tmp/odpi/lib/libodpic.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
    ```
    The program depends on `/tmp/odpi/lib/libodpi.dylib`; the install name of `/opt/odpi/lib/libodpi.dylib`.

3. Run the program.
    ```shell
    $ ./program
    ... it runs when `/tmp/odpi` is not removed...
    $ rm -rf /tmp/odpi
    $ ./program  #  it fails when `/tmp/odpi` is removed.
    dyld: Library not loaded: /tmp/odpi/lib/libodpic.dylib
      Referenced from: /xxx/./program
      Reason: image not found
    Abort trap: 6
    ```

This issue is fixed by changing [here](https://github.com/oracle/odpi/blob/v2.4.0/Makefile#L118-L119) as follows. It fixes the install name when libodpic.dylib is installed.
```Makefile
$(INSTALL_LIB_DIR)/$(FULL_LIB_NAME): $(LIB_DIR)/$(LIB_NAME)
	$(INSTALL) $< $@
	if test "`uname -s`" = Darwin; then install_name_tool -id $(INSTALL_LIB_DIR)/$(VERSION_LIB_NAME) $@; fi
```

**Comment by flokli** [comment]
> @flokli What problem you encounter when temporary path is baked into the library? Nix seems to change the baked path [here](https://github.com/NixOS/nixpkgs/blob/a1b5b1a6/pkgs/build-support/setup-hooks/fix-darwin-dylib-names.sh#L26). (Well, I have not used Nix. My guess may be incorrect.)

`fixDarwinDylibNames` can be used to rewrite relative dylib names to absolute ones (and I was using it in [here](https://github.com/flokli/nixpkgs/commit/3ebfb98490f75d9aed8de07a9ed5de64dd4ae014) to rewrite the relative one coming from the patch to an absolute one). That's a very nix-specific thing (there's no shared `/usr/lib`, but each instantiation of a derivation is stored inside a read-only `/nix/store/${hash}-${name}-${version}/` location, so every path is rewritten as absolute, allowing co-existence of multiple instantiations).

Before any patching, I basically ran into the same issue as demonstrated by you (during build, cwd was somewhere in /tmp), when trying to use it later on, that path didn't yet exist anymore, so loading the library fails.

Your patch much better, as it basically does the same as `fixDarwinDylibNames` did, but in a way that's compatible for "plain Darwin builds", too :-)

**Comment by flokli** [comment]
```
From 2a01c40ccb1a1aefefc710797fee9a774a3c5d8b Mon Sep 17 00:00:00 2001
From: Kubo Takehiro <kubo@jiubao.org>
Date: Fri, 8 Jun 2018 21:07:38 +0200
Subject: [PATCH] Makefile: fix dylib names

Tested-by: Florian Klink <flokli@flokli.de>
---
 Makefile | 1 +
 1 file changed, 1 insertion(+)

diff --git a/Makefile b/Makefile
index 7e18a23..5ff1838 100644
--- a/Makefile
+++ b/Makefile
@@ -117,6 +117,7 @@ $(INSTALL_INC_DIR)/%.h: %.h
 
 $(INSTALL_LIB_DIR)/$(FULL_LIB_NAME): $(LIB_DIR)/$(LIB_NAME)
 	$(INSTALL) $< $@
+	if test "`uname -s`" = Darwin; then install_name_tool -id $(INSTALL_LIB_DIR)/$(VERSION_LIB_NAME) $@; fi
 
 $(INSTALL_LIB_DIR)/$(VERSION_LIB_NAME): $(INSTALL_LIB_DIR)/$(FULL_LIB_NAME)
 	ln -sf $(FULL_LIB_NAME) $@
-- 
2.17.1

```

**Comment by anthony-tuininga** [comment]
Thanks, @kubo and @flokli. I've integrated the suggested solution.

**Comment by flokli** [comment]
Thanks!
