### ISSUE TITLE
The ODPI-C version in Makefile stays 2.4.0.

### ISSUE THREAD

**Issue by kubo** [oracle/odpi#66]
The ODPI-C version in dpi.h is [3.0.0](https://github.com/oracle/odpi/blob/28bbadc33a629c4c3abefd030369f7c38cad044d/include/dpi.h#L46-L48). However the version in Makefile stays 2.4.0.

How about changing [here](https://github.com/oracle/odpi/blob/28bbadc33a629c4c3abefd030369f7c38cad044d/Makefile#L33-L35) as follows to automatically follow the version defined in dpi.h?

```Makefile
MAJOR_VERSION := $(shell gawk '/\#define.*DPI_MAJOR_VERSION/ {print $$3}' include/dpi.h )
MINOR_VERSION := $(shell gawk '/\#define.*DPI_MINOR_VERSION/ {print $$3}' include/dpi.h )
PATCH_LEVEL := $(shell gawk '/\#define.*DPI_PATCH_LEVEL/ {print $$3}' include/dpi.h )
```

**Comment by anthony-tuininga** [comment]
Thanks for pointing that out and for the suggestion. I used awk since gawk may not be present. I added another variable to allow for the selection of gawk if needed, though!
