### ISSUE TITLE
Why odpi will listen any network inteface like ipv6 :::57222

### ISSUE THREAD

**Issue by dingkaich** [oracle/odpi#71]
I use goracle for test, find odpi/oci will listen any interface .
below is
SZX1000367778:/home/install/license/log # netstat -anp | grep license
tcp 0 0 10.93.79.78:62935 10.162.105.135:1547 ESTABLISHED 115247/licenseserve
tcp 0 0 10.93.79.78:47656 10.93.79.78:2181 ESTABLISHED 115247/licenseserve
tcp 0 0 127.0.0.1:58554 127.0.0.1:65003 ESTABLISHED 115247/licenseserve
tcp 0 0 10.93.79.78:62934 10.162.105.135:1547 ESTABLISHED 115247/licenseserve
tcp 0 350 10.93.79.78:62946 10.162.105.135:1547 ESTABLISHED 115247/licenseserve
tcp 0 0 127.0.0.1:50034 127.0.0.1:65001 ESTABLISHED 115247/licenseserve
tcp 0 0 :::59273 :::* LISTEN 115247/licenseserve

how to close the :::59273 :::* ???
we think this is non-securtiy ? Could we listen in 127.0.0.1 ?

For more details , Please refer to https://github.com/go-goracle/goracle/issues/98

**Comment by cjbj** [comment]
This is a mostly question about Oracle Net behavior and not specific to ODPI-C.  You can Google for how the handoff from the Oracle Listener works, e.g. https://community.oracle.com/thread/575108 

I've pinged the Net team for comment so we can get the latest info.

**Comment by dingkaich** [comment]
Looking forward to the info from net team.
But I don't understand why client will start a listen

**Comment by dingkaich** [comment]
hi 
I find something about this listen.

when we call  func  dpiConn_create, 
the dpiCommonCreateParams.createMode =  C.DPI_MODE_CREATE_DEFAULT | C.DPI_MODE_CREATE_THREADED | C.DPI_MODE_CREATE_EVENTS it will start the ::: listen.
if  dpiCommonCreateParams.createMode =  C.DPI_MODE_CREATE_DEFAULT | C.DPI_MODE_CREATE_THREADED ; the ::: listen will not start.

Do you know why ?

**Comment by dingkaich** [comment]
goracle FIX this issue, close it ,3ks

**Comment by anthony-tuininga** [comment]
That makes sense. Events mode requires a communication channel between the database and the client independently of the connection itself.
