### ISSUE TITLE
Binding NULL value

### ISSUE THREAD

**Issue by horrendo** [oracle/odpi#74]
Hi,

I'm building a DB driver for Crystal and I'm struggling to work out what to set the nativeTypeNum to when calling dpiStmt_bindValueByName with the isNull member of my dpiData structure set to 1 (i.e. NULL).

I thought it shouldn't matter.  If the isNull indicator is set to 'true', the value member of the structure should be ignored.  However, if I set nativeTypeNum to something that doesn't match the context of the statement (e.g. DPI_NATIVE_TYPE_BYTES for a number), I get a runtime ORA-00932.

What am I doing wrong?

As a couple of examples, lets say my driver is provided with the following statements:

`select user_id, username from users where username like coalesce(:usr, 'A%')`
or
`select user_id, username from users where user_id < coalesce(:id, 10)`

If I get a not-null bind value, all's good. I can determine the data type of the bind value and set the nativeTypeNum accordingly.  If however I get a value of `nil`, I'm not sure what to do.

I'm using ODPI-C version 3, connecting to a 12.2 DB.  I'm running on a Mac running 10.13.6.  My Instant client version is 12.2.0.1.

Maybe I missed it but I can't see any of the samples binding NULL values.

Thanks,

Steve

**Comment by anthony-tuininga** [comment]
In Oracle Database, a null value still has a type. So it is a null string, or a null number, or a null date. In languages like Python and Node.js which don't have such a concept, the "null" value is turned into a null string. Usually this is sufficient. There are cases (such as calling an overloaded stored procedure) where you must specify the type more exactly, so a way is enabled for the developer to do so. These are uncommon, however, so to start with I'd suggest using a type of DPI_NATIVE_TYPE_BYTES.

**Comment by anthony-tuininga** [comment]
Oh, and if/when you have a working driver, please provide a link and I can add it to the README along with the other drivers using ODPI-C.

**Comment by horrendo** [comment]
Thanks Anthony. I'm not sure if this means anything to you, but my bind method looks like this:

```
    def bind(name : String, val)
      n = name.upcase
      if bind_var_names.includes?(n)
        v = val.to_ora
        unless LibODPIC.stmt_bind_value_by_name(@h, n, n.size, val.class.native_ora_type, pointerof(v)) == DPI_SUCCESS
          @raise_func.call
        end
      else
        raise BindError.new(self, name)
      end
    end
```

I then inject `to_ora` and `native_ora_type` methods into each of the native types I'm supporting.  For example:

```
struct UInt64
  def to_ora
    d = OraLib::LibODPIC::Data.new
    d.is_null = 0
    buffer = OraLib::LibODPIC::DataBuffer.new
    buffer.as_uint64 = self
    d.value = buffer
    d
  end

  def self.native_ora_type
    OraLib::DPI_NATIVE_TYPE_UINT64
  end
```

For the `Nil` type I had this:

```
struct Nil
  def to_ora
    d = OraLib::LibODPIC::Data.new
    d.is_null = 1
    d
  end

  def self.native_ora_type
    OraLib::DPI_NATIVE_TYPE_BYTES
  end
end
```

This works fine if my bind variable is being used in a 'char' context but fails with the ora-932 if my bind variable is being used in a numeric context.

**Comment by horrendo** [comment]
I can probably implement a workaround by allowing the `bind` function to take a `class` as as arg (which would mean NULL value of type `class`), or implement new classes for `NullXXX` types.

**Comment by anthony-tuininga** [comment]
Can you provide the full test case you are using as well? I am not familiar with Crystal but I know Oracle Database quite well and might be able to help further with that information.

**Comment by horrendo** [comment]
Thanks again Anthony. For now I've got a workable solution. I created an overloaded `bind` function that takes a class as an argument:
```
    def bind(name : String, val : Class)
      n = name.upcase
      if bind_var_names.includes?(n)
        v = nil.to_ora
        t = val.native_ora_type
        unless LibODPIC.stmt_bind_value_by_name(@h, n, n.size, t, pointerof(v)) == DPI_SUCCESS
          @raise_func.call
        end
      else
        raise BindError.new(self, name)
      end
    end
```
It allows me to give the developer the opportunity to define the 'type' of NULL value:
```
require "./src/ora.cr"

class Users
  DB.mapping({
    user_id:  Int32,
    username: String,
  })
end

QRY_1 = "select user_id, username from users where username like coalesce(:usr, 'A%')"
QRY_2 = "select user_id, username from users where user_id < coalesce(:id, 10)"
DB.connect("ora://crystal:abcd1234@localhost/pdb1.local.domain.com") do |db|
  users = Users.from_rs(db.query(QRY_1, usr: "S%"))
  puts "I found #{users.size} users"
  users = Users.from_rs(db.query(QRY_1, usr: String))
  puts "I found #{users.size} users"
  users = Users.from_rs(db.query(QRY_2, id: 1000))
  puts "I found #{users.size} users"
  users = Users.from_rs(db.query(QRY_2, id: Int32))
  puts "I found #{users.size} users"
end
```
I'll certainly let you know when my driver is ready to be added to your list.

**Comment by anthony-tuininga** [comment]
Sounds good. I presume this means that your question has been answered?

**Comment by horrendo** [comment]
Yep. I'm sure I'll have others though ;-).

Thanks a lot for being so incredibly response.  Your library is just great.  So much easier than fighting with OCI.

**Comment by anthony-tuininga** [comment]
Glad to hear it! I'll close this issue and you can open another one when a new question appears. :-)
