### ISSUE TITLE
Update dpiStmt docs on dpiStmt_getQueryValue

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#79]
rst docs talks about a `dpiData *data` argument.

```
.. function:: int dpiStmt_getQueryValue(dpiStmt \*stmt, uint32_t pos, \
        dpiNativeTypeNum \*nativeTypeNum, dpiData \*data)
```

But the source code shows a `dpiData **data` argument.

```c
int dpiStmt_getQueryValue(dpiStmt *stmt, uint32_t pos,
        dpiNativeTypeNum *nativeTypeNum, dpiData **data)
```

I guess the rst docs should be updated to:

```
.. function:: int dpiStmt_getQueryValue(dpiStmt \*stmt, uint32_t pos, \
        dpiNativeTypeNum \*nativeTypeNum, dpiData \*\*data)
```

**Comment by anthony-tuininga** [comment]
Thanks for pointing out that discrepancy! It has now been corrected. :-)

**Comment by anthony-tuininga** [comment]
@felipenoris, I see you are building a Julia driver. Did you want me to add it to the list of third-party drivers listed in the [README](https://github.com/oracle/odpi)?

**Comment by felipenoris** [comment]
@anthony-tuininga Sure! It will be functional by the end of this month. I'll also register it as an official Julia package.

**Comment by cjbj** [comment]
@felipenoris Excellent!

**Comment by cjbj** [comment]
@felipenoris does your package have a name yet?

**Comment by felipenoris** [comment]
It's currently **Oracle.jl**.

**Comment by anthony-tuininga** [comment]
I just added a reference in the README. :-)

**Comment by felipenoris** [comment]
@anthony-tuininga , just one more comment and suggestion on these docs.

It now says: `**data** [OUT] -- a pointer to a pointer...` . But I think it would be better described as a `reference to a dpiData array`. It also important to note that it points to the `last element` of the array when using `dpiStmt_fetchRows`.

There are no clues in the docs on how to retrieve data after executing `dpiStmt_fetchRows`.

**Comment by anthony-tuininga** [comment]
I've made a small change to use the term "reference" instead of "pointer" -- since it is a reference into an array of those structures. So if you ask for the first row (pos=0) you will get a reference to the first element of the array, but if you ask for the fifth row (pos=4) you will get a reference to the fifth element of the array. The function dpiStmt_getQueryValue() should be used when fetching rows one a at time via dpiStmt_fetch().

The function dpiStmt_fetchRows() is only needed when you need to control when the round-trip to the database takes place; if that knowledge isn't required there is no significant performance penalty for using dpiStmt_fetch(). If you decide to use it anyway, then you will want to create variables which will give you access to the dpiData array directly. You don't need to call dpiStmt_getQueryValue() in that case!

Hope all of that is clear!

**Comment by felipenoris** [comment]
I'm sorry about my lack of understanding of these concepts about variables in Oracle databases. I never actually used this database before, so I'm learning while writing this driver.

I'm afraid I'm misusing the ODPI-C. 

In the Julia package I'm writing, the high-level API to iterate a query result is this:

```julia
for row in Oracle.query(conn, "SELECT * FROM TB_BIND")
    println( row["ID"]  ) # will print the value for column ID of table TB_BIND
end
```

But under the hood, the test below shows what's actually happening, which works fine.

```julia
@testset "Fetch Many" begin
    Oracle.execute!(conn, "CREATE TABLE TB_TEST_FETCH_MANY ( ID NUMBER(4,0) NULL, VAL NUMBER(4,0) NULL )")
    for i in 1:10
        Oracle.execute!(conn, "INSERT INTO TB_TEST_FETCH_MANY ( ID, VAL ) VALUES ( $i, $(10i))")
    end

    stmt = Oracle.Stmt(conn, "SELECT ID, VAL FROM TB_TEST_FETCH_MANY")
    result = Oracle.execute!(stmt)
    @test result.num_columns == 2

    fetch_rows_result = Oracle.fetch_rows!(stmt, 3) # this line will call dpiStmt_fetchRows with maxRows = 3

    @test fetch_rows_result.buffer_row_index == 0 # bufferRowIndex returned by dpiStmt_fetchRows
    @test fetch_rows_result.num_rows_fetched == 3 # numRowsFetched returned by dpiStmt_fetchRows
    @test fetch_rows_result.more_rows == 1 # moreRows returned by dpiStmt_fetchRows

    value_id = Oracle.query_value(stmt, 1) # *dpiData resulting from dpiStmt_getQueryValue for pos = 1
    value_val = Oracle.query_value(stmt, 2) # *dpiData resulting from dpiStmt_getQueryValue for pos = 2 

    @test value_id[-2] == 1
    @test value_val[-2] == 10

    @test value_id[-1] == 2
    @test value_val[-1] == 20

    @test value_id[0] == 3
    @test value_val[0] == 30

    Oracle.execute!(conn, "DROP TABLE TB_TEST_FETCH_MANY")
end
```

What's interesting in this example is that I'm using `dpiStmt_getQueryValue` to retrieve values from `dpiStmt_fetchRows`. Also, the `**dpiData` returned from `dpiStmt_getQueryValue` is treated as a reference to a pointer, or a reference to a `dpiData` array.

For instance, the line `value_id[-2]` will retrieve the value pointed by `p - 2*sizeof(dpiData)` where `p` is the pointer returned by `dpiStmt_getQueryValue`, which is pointing to the last value.

Which leads me to ask you 2 things:

* am I misusing `dpiStmt_getQueryValue` in this example?

* If I use `dpiStmt_fetch` instead, every call to this function will perform IO operation to communicate to the database?

Thanks!

**Comment by anthony-tuininga** [comment]
@felipenoris,

- dpiStmt_getQueryValue() is intended to be paired with dpiStmt_fetch(), so yes you are misusing it :-)
- if you want to use dpiStmt_fetch(), you should create variables and then define them using dpiStmt_define()
- bufferRowIndex is the index into the row buffers and as such refers to a row number, not a column position
- dpiStmt_getQueryValue() expects a column position
- dpiStmt_fetch() only preforms an I/O operation when the internal row buffers have been exhausted (the default is 100 rows)

So for your code you should do something like the following:

```c
int found;
uint32_t bufferRowIndex;
dpiData *columnData1, *columnData2;
dpiNativeTypeNum nativeTypeNum;

while (1) {
    if (dpiStmt_fetch(stmt, &found, &bufferRowIndex) < 0)
        exit(1);
    if (!found)
        break;
    if (dpiStmt_getQueryValue(stmt, 1, &nativeTypeNum, &columnData1) < 0 ||
           dpiStmt_getQueryValue(stmt, 2, &nativeTypeNum, &columnData2) < 0)
        exit(1);
}
```

Does that make more sense?

**Comment by felipenoris** [comment]
@anthony-tuininga, thanks! Yes, it makes a lot of sense! I'll change my cursor implementation based on `fetch` instead of `fetchMany`.
