### ISSUE TITLE
Is OCIThread supported?

### ISSUE THREAD

**Issue by jssprasanna** [oracle/odpi#8]
Just wanted to know whether OCIThread is supported in ODPI for now, I see no APIs offering multi-threading using OCIThread, don't know whether I am missing something here!

**Comment by anthony-tuininga** [comment]
What particular API are you looking for? ODPI supports multi-threading by setting the create mode to include the flag DPI_MODE_CREATE_THREADED. In this mode all accesses to database objects are protected by a mutex. Was there something else you were looking for?

**Comment by jssprasanna** [comment]
Anthony, Thanks a lot for the reply. Request you to please add a sample C program for the same. Once Again thanks a lot for the awesome ODPI!
