### ISSUE TITLE
Helper functions to set/get null values to dpiData

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#82]
I created a patch to this library to add the function:

```c
int dpiData_isNull(dpiData *data) {
    return data->isNull;
}
```

The objective is the same described in https://oracle.github.io/odpi/doc/functions/dpiData.html, since I'm using a language that does not support C's union.

I would suggest to add a getter/setter function handling null values for dpiData structure.

**Edit**

I'm aware that only `dpiDataBuffer` is a C union, but in my case this also affects dpiData, unless I copy the content of the pointer *dpiData returned by the C API to a location owned by the language I'm using, which would be inefficient.

**Comment by anthony-tuininga** [comment]
That request seems reasonable to me, so I have just pushed changes to add that capability, as requested. Let me know if that meets your needs.

**Comment by felipenoris** [comment]
Thanks for the update!

I would expect `dpiData_setNull` to accept a second argument to select wether I would like to set the value to true (1) or false (0). The current implementation always set it to 1, and I don´t have a way to set it to 0.

**Comment by anthony-tuininga** [comment]
I considered that, but the other dpiData_set() methods all set the null indicator to false, so there is no need to set it independently -- and it would be unsafe to do so anyway!

**Comment by felipenoris** [comment]
@anthony-tuininga awesome! So, this looks good to me. Thank you!
