### ISSUE TITLE
How do I fetch output from dbms_output.put_line()

### ISSUE THREAD

**Issue by bangusi** [oracle/odpi#84]
I need to capture the output from `dbms_output.put_line` from a PL/SQL block. Not a stored procedure.
example PL/SQL block like this
```
DECLARE
hello varchar2(100);
BEGIN
    dbms_output.enable();
	hello := 'Hello, World';
    dbms_output.put_line (hello); 
END;
```

Using c++  on Windows
```
dpiStmt *stmt;
dpiConn_prepareStmt(conn, 0, sql_enable_output.c_str(), sql_enable_output.size(), NULL, 0, &stmt) 
dpiStmt_execute(stmt, 0, NULL) ;
```

**Comment by cjbj** [comment]
You're on the right track: enabling, creating and fetching DBMS_OUTPUT is all done via PL/SQL.  There are no direct ODPI examples, but you can see the general PL/SQL call flow in higher levels examples like https://github.com/oracle/node-oracledb/blob/master/examples/dbmsoutputgetline.js and https://github.com/oracle/node-oracledb/blob/master/examples/dbmsoutputpipe.js 
You just need to do the equivalent in ODPI-C - check the ODPI-C examples and tests for generic info about using PL/SQL.

**Comment by bangusi** [comment]
OK. So essentially I need to call DBMS_OUTPUT.GET_LINE.
Turns out this [ocilib](https://github.com/vrogier/ocilib) has a build in function to do this sort of thing
