### ISSUE TITLE
Missing docs for dpiLob_close

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#88]
Looks like the docs are missing for `dpiLob_close` function in [LOB Functions page](https://oracle.github.io/odpi/doc/functions/dpiLob.html).

In the source code `int dpiLob_close(dpiLob *lob)` function exists and is marked as Public.

**Comment by anthony-tuininga** [comment]
Yes, you are correct. That function was added later than the rest of them, but the documentation was missed! This is now corrected. Thanks!
