### ISSUE TITLE
dpiPool_create strange code path

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#89]
Hi! This code path in `dpiPool_create` looks a little odd. Is it safe to check just the minor version to achieve the logic described in the code comment?

```c
    // size changed in 3.1; must use local variable until version 4 released
    if (!createParams || context->dpiMinorVersion < 1) {
        dpiContext__initPoolCreateParams(&localCreateParams);
        if (createParams)
            memcpy(&localCreateParams, createParams,
                    sizeof(dpiPoolCreateParams__v30));
        createParams = &localCreateParams;
    }
```

**Comment by anthony-tuininga** [comment]
It is safe, as the code in dpiContext_create() ensures that the major versions must match before proceeding further!

**Comment by anthony-tuininga** [comment]
The reason for the code is because the size of the structure changed in version 3.1.

**Comment by felipenoris** [comment]
Oh, I see. Thanks!
