### ISSUE TITLE
Question about dpiLob_getChunkSize

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#91]
Does this function always return a number of bytes, or it returns a number of chars in the case the LOB holds character data?

**Comment by anthony-tuininga** [comment]
The value is always in bytes. I have adjusted the documentation to make that clear. :-)

**Comment by anthony-tuininga** [comment]
@felipenoris, I draw your attention to a couple of new samples that I just [added](https://github.com/oracle/odpi/commit/6a4a6f17d0391e36d637583c51adcc2cdba71ba0) that demonstrate how to fetch CLOBs as strings and BLOBs as bytes. For smaller LOBs this can be a substantial performance boost as fewer round trips to the database are required. Please keep this in mind while developing your Julia driver!
