### ISSUE TITLE
Question about argument lifetime in dpiData_setBytes

### ISSUE THREAD

**Issue by felipenoris** [oracle/odpi#93]
Regarding `dpiData_setBytes` defined by:

`void dpiData_setBytes(dpiData *data, char *ptr, uint32_t length)`

When setting bytes to `data`, does the string in address `ptr` must have the same lifetime as `data`, or the string gets copied? My concern is that if I free the string pointed by `ptr` when a reference to `data` is still active the string could be lost.

**Comment by anthony-tuininga** [comment]
See the comment in the [documentation](https://oracle.github.io/odpi/doc/structs/dpiData.html). Effectively, if you are the one supplying the data, you need to make sure it remains viable for the duration of any call that uses that data. Once the call is complete you can free the pointer quite safely -- so long as you don't use that data in another call to ODPI-C, of course!

**Comment by felipenoris** [comment]
Got it! Thanks!
