### ISSUE TITLE
Possible Memory leaks in dpiStmt_fetch, How to avoid?

### ISSUE THREAD

**Issue by junaidriaz** [oracle/odpi#98]
There are some memory leaks observed in dpiStmt_fetch method.

**leak sample:**
```
CallStack[12]: may-leak=4 (16960 bytes)
    expired=4 (16960 bytes), free_expired=0 (0 bytes)
    alloc=4 (16960 bytes), free=0 (0 bytes)
    freed memory live time: min=0 max=0 average=0
    un-freed memory live time: max=1045
    0x00007f0cf682e160  libc-2.17.so  __malloc()+0
    0x00007f0ce8a59aad  libclntsh.so  kpummapg()+141
    0x00007f0ceb22d28a  libclntsh.so  kgh_invoke_alloc_cb()+202
    0x00007f0ceb2285bb  libclntsh.so  kghgex()+2507
    0x00007f0ceb22c48a  libclntsh.so  kghfnd()+362
    0x00007f0ceb22aaa2  libclntsh.so  kghalo()+4610
    0x00007f0ceb227dc1  libclntsh.so  kghgex()+465
    0x00007f0ceb22c48a  libclntsh.so  kghfnd()+362
    0x00007f0ceb22aaa2  libclntsh.so  kghalo()+4610
    0x00007f0ceb227dc1  libclntsh.so  kghgex()+465
    0x00007f0ceb22c48a  libclntsh.so  kghfnd()+362
    0x00007f0ceb22aaa2  libclntsh.so  kghalo()+4610
    0x00007f0ce846905b  libclntsh.so  kpuhhaloc()+363
    0x00007f0ce84c5ec4  libclntsh.so  kpughndl0()+516
    0x00007f0ce84d8726  libclntsh.so  kpudfni()+2438
    0x00007f0ce84d8c8b  libclntsh.so  kpudfn2()+427
    0x00007f0cf3607de8  libodpic.so  dpiOci__defineByPos2()+120  src/dpiOci.c:1141
    0x00007f0cf35fcdbc  libodpic.so  dpiStmt__define()+220  src/dpiStmt.c:494
    0x00007f0cf35fd7ad  libodpic.so  dpiStmt__beforeFetch()+253  src/dpiStmt.c:899
    0x00007f0cf35fd841  libodpic.so  dpiStmt__fetch()+17  src/dpiStmt.c:641
    0x00007f0cf35fe9e3  libodpic.so  dpiStmt_fetch()+147  src/dpiStmt.c:1270
```
Detailed memory leaks log file generated by [memleax](https://github.com/WuBingzheng/memleax) are attached [here](https://gist.github.com/junaidriaz/cb964ddc2f016206e8400181bcf12f3d)

Please review the source code is [here](https://gist.github.com/junaidriaz/d5762f94f014590d28779dee4f37acb3)

### Questions
I have few questions which may solve this problem.
1: Is there any memory allocated at line [61](https://gist.github.com/junaidriaz/d5762f94f014590d28779dee4f37acb3#file-cdpi-c-L61) ? If yes who has to free this memory?
2: Can free above mentioned memory after line [105](https://gist.github.com/junaidriaz/d5762f94f014590d28779dee4f37acb3#file-cdpi-c-L105)? If yes then how to do that?

please correct me if there is some bug in my code thanks.

```
odpi version : 3.1
oracle instant client: 18.1
gcc: 4.8.5
```

**Comment by anthony-tuininga** [comment]
1. dpiStmt_defineValue() will indeed allocate a new variable and will store a reference to it on the statement for the specified column position. This is managed internally. You simply need to ensure that you either (a) close the statement, (b) remove the last reference which will implicitly close the statement or (c) execute a different statement

2. I'm not sure exactly what you are referring to here. The memory for the variable which you are referencing by calling dpiStmt_getQueryValue() is allocated via the call to dpiStmt_defineValue() and will remain valid as long as none of the three scenarios noted above take place. You do not need to free this memory yourself.

I don't see any code to close the statement or release the reference, but perhaps that is somewhere else?

**Comment by junaidriaz** [comment]
> 1. dpiStmt_defineValue() will indeed allocate a new variable and will store a reference to it on the statement for the specified column position. This is managed internally. You simply need to ensure that you either (a) close the statement, (b) remove the last reference which will implicitly close the statement or (c) execute a different statement

Thanks, got it.


> I don't see any code to close the statement or release the reference, but perhaps that is somewhere else?

I am releasing cursor variable using **dpiVar_release** at line [15](https://gist.github.com/junaidriaz/d5762f94f014590d28779dee4f37acb3#file-cdpi-c-L15) by following example of [ref cursor line 82](https://github.com/oracle/odpi/blob/master/samples/TestRefCursors.c#L82). Do I need to use **dpiStmt_release(cursorStmt)** to free cursor ?


Main stmt reference, which was created immediately after get connection (code is below),  is being released later after fetching other out parameters and cursors.

```
    if (dpiConn_prepareStmt(connection, 0, pocdpiDataAccessSessionData->pchSQL, (u_int32_t)strlen(pocdpiDataAccessSessionData->pchSQL), NULL, 0, &stmt) < 0) {
        char error[DEFAULT_SIZE] ="\0";
        cdpi_GetOracleError(NULL, "failed to prepare stmt", &pocdpiContext->Config_data.ocdpiDBConfig, error);
        cdpi_SetDataAccessError(pocdpiDataAccessSessionData, ORA_INTERNAL_ERROR, error);
        goto CDPI_ERROR;
    }
```

**Comment by anthony-tuininga** [comment]
The example you referenced is correct as far as I know. I didn't realise you were fetching from the REF cursor in your code.

Can you create an example that repeats the calls to demonstrate what you believe is a memory leak? Note that until you close the *main* cursor, there is still a reference to the variable (containing the ref cursor) held by it, so until you close it all of that memory will be held. It should be freed, however, once you close the main cursor. I hope that's clear?

**Comment by junaidriaz** [comment]
> Can you create an example that repeats the calls to demonstrate what you believe is a memory leak? 

Sure, let me do it after weekend as I need to have access to database located at office data center. 

> Note that until you close the _main_ cursor, there is still a reference to the variable (containing the ref cursor) held by it, so until you close it all of that memory will be held. It should be freed, however, once you close the main cursor. I hope that's clear?

Noted.

**Comment by junaidriaz** [comment]
I have tried but could not produce memory leak in a simple [example](https://gist.github.com/junaidriaz/6a6891e3a54bf44ca8e38f43b5b7c60c). I am closing this issue for now. Thanks for your cooperation.

**Comment by judith-ipac** [comment]
Hello, is it too late to ask a follow-up question?  I am investigating memory which is allocated during a call to dpiStmt_defineValue() and (if I use a connection from a pool) not freed.   I am using  commit 4da9801 of the  https://github.com/oracle/odpi.git repo.  

Debug output (DPI_DEBUG_LEVEL=127 and my own print statements) from a run in which I use a standalone connection indicates that the pointer allocated by dpiOci__defineByPos2() (which is indirectly called by dpiStmt_defineValue()) is freed not during the subsequent call to dpiStmt_close() but after that, during a call to dpiConn__free(), which calls dpiEnv__free() which calls dpiOci__handleFree() which frees the pointer.    

When I use a connection from a pool rather than a standalone connection, dpiConn__free() does not call dpiEnv__free() and the pointer allocated by  dpiOci__defineByPos2()  is not freed.  Is this how it should be? For all I know, this is by design, and yet memory use is orders of magnitude higher when we link to libodpic than when we use a different library to talk to Oracle.

Unfortunately I do not have a standalone example, but I will gladly post debug output if anybody out there is willing to take a look.  Thanks in advance.

**Comment by cjbj** [comment]
Use a gist for debug output and if we see anything, we will let you know.

**Comment by judith-ipac** [comment]
Thanks for your reply!  I don't understand the first part of it, but here is some debug output.

Debug/print statements preceding and immediately following OCI's allocation of a pointer at 0x7fcc91e2cc80:

ODPI [01386] 2021-01-17 20:45:03.933: fn start dpiStmt_defineValue(0x7fcd4019abe0)
ODPI [01386] 2021-01-17 20:45:03.933: defineValue(), before dpiVar__allocate()
ODPI [01386] 2021-01-17 20:45:03.933: dpiVar__allocate(), enter
ODPI [01386] 2021-01-17 20:45:03.933: allocated 176 bytes at 0x7fcc9166cb70 (allocate handle)
ODPI [01386] 2021-01-17 20:45:03.933: ref 0x7fcc9166cb70 (dpiVar) -> 1 [NEW]
ODPI [01386] 2021-01-17 20:45:03.933: dpiGen__setRefCount(), enter
ODPI [01386] 2021-01-17 20:45:03.933: dpiGen__setRefCount(), threaded: 1, ref_count: 285
ODPI [01386] 2021-01-17 20:45:03.933: ref 0x7fcd4003e490 (dpiConn) -> 286
ODPI [01386] 2021-01-17 20:45:03.933: dpiVar__allocate(), before initBuffer
ODPI [01386] 2021-01-17 20:45:03.933: allocated 720896 bytes at 0x7fcc9166cc30 (allocate buffer)
ODPI [01386] 2021-01-17 20:45:03.933: allocated 65536 bytes at 0x7fcc9171cc40 (allocate indicator)
ODPI [01386] 2021-01-17 20:45:03.934: allocated 131072 bytes at 0x7fcc9172cc50 (allocate actual length)
ODPI [01386] 2021-01-17 20:45:03.934: before additional allocate
ODPI [01386] 2021-01-17 20:45:03.934: allocated 5636096 bytes at 0x7fcc9174cc60 (allocate temp buffer)
ODPI [01386] 2021-01-17 20:45:03.934: allocated 1572864 bytes at 0x7fcc91cacc70 (allocate external data)
ODPI [01386] 2021-01-17 20:45:03.936: after allocate external data
ODPI [01386] 2021-01-17 20:45:03.936: before variable specific
ODPI [01386] 2021-01-17 20:45:03.936: initBuffer(), leaving
ODPI [01386] 2021-01-17 20:45:03.936: dpiVar__allocate(), after initBuffer
ODPI [01386] 2021-01-17 20:45:03.936: dpiVar__allocate(), leaving
ODPI [01386] 2021-01-17 20:45:03.937: dpiStmt__define(), before defineByPos()
ODPI [01386] 2021-01-17 20:45:03.937: dpiStmt__define(), before defineByPos2()
ODPI [01386] 2021-01-17 20:45:03.937: dpiOci__defineByPos2(), enter, var is null: 0
ODPI [01386] 2021-01-17 20:45:03.937: defineByPos2(), isDynamic 0, oracleTypeNum 2010, nativeTypeNum 3003, oracleType: 6
ODPI [01386] 2021-01-17 20:45:03.937: OCI allocated 4256 bytes at 0x7fcc91e2cc80
ODPI [01386] 2021-01-17 20:45:03.937: dpiOci__defineByPos2(), leaving
ODPI [01386] 2021-01-17 20:45:03.937: dpiStmt__define(), after defineByPos()

And debug/print statements starting with dpiStmt_release():

ODPI [01386] 2021-01-17 20:45:04.310: fn start dpiStmt_release(0x7fcd4019abe0)
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), enter
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), threaded: 1, ref_count: 1
ODPI [01386] 2021-01-17 20:45:04.310: ref 0x7fcd4019abe0 (dpiStmt) -> 0
ODPI [01386] 2021-01-17 20:45:04.310: before freeProc for dpiStmt
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), enter
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), threaded: 1, ref_count: 2
ODPI [01386] 2021-01-17 20:45:04.310: ref 0x7fcd4003e490 (dpiConn) -> 1
ODPI [01386] 2021-01-17 20:45:04.310: freed ptr at 0x7fcd4019abe0
ODPI [01386] 2021-01-17 20:45:04.310: fn end dpiStmt_release(0x7fcd4019abe0) -> 0
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__endPublicFn(), returning 0
ODPI [01386] 2021-01-17 20:45:04.310: fn start dpiConn_release(0x7fcd4003e490)
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), enter
ODPI [01386] 2021-01-17 20:45:04.310: dpiGen__setRefCount(), threaded: 1, ref_count: 1
ODPI [01386] 2021-01-17 20:45:04.310: ref 0x7fcd4003e490 (dpiConn) -> 0
ODPI [01386] 2021-01-17 20:45:04.310: before freeProc for dpiConn
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__free(), enter
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__free(), got handle
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), enter
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), pooled connections, dead session: 0
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), no ptr available
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), before sessionRelease()
ODPI [01386] 2021-01-17 20:45:04.311: dpiOci__sessionRelease(), enter
ODPI [01386] 2021-01-17 20:45:04.311: dpiOci__sessionRelease(), before OCI call
ODPI [01386] 2021-01-17 20:45:04.311: dpiOci__sessionRelease(), after OCI call, exit1
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), after sessionRelease()
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__close(), exit
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__free(), got pool, env is NULL: 0
ODPI [01386] 2021-01-17 20:45:04.311: dpiGen__setRefCount(), enter
ODPI [01386] 2021-01-17 20:45:04.311: dpiGen__setRefCount(), threaded: 1, ref_count: 2
ODPI [01386] 2021-01-17 20:45:04.311: ref 0x561594b0aa50 (dpiPool) -> 1
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__free(), got openStmts
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401bde00
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401fd520
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401a5540
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401a5420
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401fcaf0
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd401c0720
ODPI [01386] 2021-01-17 20:45:04.311: freed ptr at 0x7fcd4003e490
ODPI [01386] 2021-01-17 20:45:04.311: dpiConn__free(), exit
ODPI [01386] 2021-01-17 20:45:04.311: fn end dpiConn_release(0x7fcd4003e490) -> 0
ODPI [01386] 2021-01-17 20:45:04.311: dpiHandlePool__release(), enter
ODPI [01386] 2021-01-17 20:45:04.311: dpiHandlePool__release(), exit
ODPI [01386] 2021-01-17 20:45:04.311: dpiGen__endPublicFn(), returning 0

Thanks for taking a look.

**Comment by judith-ipac** [comment]
Evidently a pointer like the one above, allocated during a call to dpiOci__defineByPos2(), is associated to conn->env; it is freed (in the non-pool case) when dpiEnv__free() is called.  Is there a provision for freeing memory in a pool->env before the pool itself is released?

**Comment by anthony-tuininga** [comment]
Are you able to provide the code you are using that generates this output? That would be helpful.

**Comment by judith-ipac** [comment]
Hello, thanks for taking an interest.  I am working on a standalone example that doesn't refer to our database tables and will post it as soon as possible.

**Comment by judith-ipac** [comment]
Hello again and sorry for the delay.  I have been working on a standalone example which I will attach below.  It does illustrate the phenomenon I described above of pointers not being freed until dpiPoolrelease() is called, but I'm not sure that that fully explains the ever-increasing memory use we see in the real-life application we are modifying to use ODPI.   I'm new to ODPI and it's quite likely that I am calling ODPI functions improperly or that there is a configuration option I could modify.  If you could take a look at the example, that would be great.   There are comments and compilation instructions at the top of the file.  Thank you.

Er.  I've never tried to upload files this way.  I had to append a ".txt" to the filename before github would even pretend to accept it.  I hope this will work.


[odpi_demo_alloc.c.txt](https://github.com/oracle/odpi/files/6016316/odpi_demo_alloc.c.txt)

**Comment by anthony-tuininga** [comment]
Hi, I took a look at your code. I had to make a number of small changes to get it to compile -- you are perhaps using a different compiler than I am? In any case, I ran it and you appear to be managing references properly as when I set `DPI_DEBUG_LEVEL` to the value 2, the number of references went to zero at the end of the program as it should.

You can set the statement cache to size 0 if you are concerned about memory (or simply to verify that memory usage is stable before letting the default value be retained). The statement cache remembers statements that have been executed and improves performance -- but does use more memory as it retains information.

I set the number of iterations to be very large (500) and after a minute or two the memory stabilised and never went up after that.

I have used this Python script to examine the output from setting `DPI_DEBUG_LEVEL` to 32:

```import sys

ALLOCATED_STRING = ": allocated "
FREED_STRING = ": freed "

OCI_ALLOCATED_STRING = ": OCI allocated "
OCI_FREED_STRING = ": OCI freed "

memoryLocations = {}
orderedMemoryLocations = []

for line in open(sys.argv[1]):

    # check for ODPI-C allocation
    pos = line.find(ALLOCATED_STRING)
    if pos > 0:
        parts = line[pos + len(ALLOCATED_STRING):].split()
        size = int(parts[0])
        memoryLocation = parts[3]
        memoryLocations[memoryLocation] = size
        orderedMemoryLocations.append(memoryLocation)
        continue

    # check for ODPI-C free
    pos = line.find(FREED_STRING)
    if pos > 0:
        parts = line[pos + len(FREED_STRING):].split()
        memoryLocation = parts[2]
        del memoryLocations[memoryLocation]
        orderedMemoryLocations.remove(memoryLocation)
        continue

    # check for OCI allocation
    pos = line.find(OCI_ALLOCATED_STRING)
    if pos > 0:
        parts = line[pos + len(OCI_ALLOCATED_STRING):].split()
        size = int(parts[0])
        memoryLocation = parts[3]
        memoryLocations[memoryLocation] = size
        orderedMemoryLocations.append(memoryLocation)
        continue

    # check for OCI free
    pos = line.find(OCI_FREED_STRING)
    if pos > 0:
        parts = line[pos + len(OCI_FREED_STRING):].split()
        memoryLocation = parts[2]
        del memoryLocations[memoryLocation]
        orderedMemoryLocations.remove(memoryLocation)
        continue

for memoryLocation in orderedMemoryLocations:
    print(memoryLocation, "-> size", memoryLocations.get(memoryLocation))
```

I generally print something in the output so I know where the final close is done -- or if you include the logging level for function calls (4) then you can use that. In order to find out if there is an actual leak somewhere, you need to see if the memory allocated prior to the close of the pool (or standalone connection) remains constant no matter how many iterations are executed. ODPI-C allocates some memory globally which is never freed -- but this is minimal (a few KB). Let me know if you discover anything specific that I can look at!

**Comment by cjbj** [comment]
@anthony-tuininga can you add that script to the debugging doc?

**Comment by judith-ipac** [comment]
anthony-tuininga, thank you very much for looking at my script.  Did
you run it with ABORT_BEFORE_CLEANUP turned on and note the number of
un-freed pointers remaining after all queries have been handled, which
increases with the number and size of tables?  Our real-life
application involves nearly a thousand tables, some with hundreds of
columns and billions of rows.

Our real-life queries are of course more complicated than the simple
SELECT statements in the script; I haven't investigated how that complexity
affects memory use.

Below is a small table showing memory use of two versions of our
application, one using occi and one odpi.  The instances ran on the
same hardware and served the same set of queries under the same
conditions.


                Startup             After serving 13000 queries

occi:           75.7m                 136m

odpi:          146.7m               0.011t

For purposes of comparison, the production (occi-based) instance which
has been running for 10 days and has served 380K queries is stable at
0.980g.

I will make a version of the script above that uses occi rather than
odpi and see what I can learn from that.  Unfortunately I have not
figured out how to turn on the equivalent of DPI_DEBUG_LEVEL = 32
for the occi library.  I would be extremely grateful for any
recommendations!

Thanks again,
Judith

**Comment by sudarshan12s** [comment]
@judith-ipac , can you confirm  statement cache  settings on OCCI and odpi application. On OCCI, we use setStmtCacheSize on pool to enable/disable statement cache. on ODPI, we use dpiPool_setStmtCacheSize. Its by default disabled in OCCI and enabled in odpi. 

DPI_DEBUG_LEVEL is specific to odpi. OCCI doesn't support exact one and needs some additional changes to get similar behaviour using createEnvironment alloc/free memory registered functions. 

Thanks

**Comment by sudarshan12s** [comment]
On the un-freed pointers. 

Session pool shall cache some data related to the sessions cached in the pool which is limited by max pool configured. 
data includes  session specific infn, server handle, service information, statements associated with the session (limited by stmt cache size enabled per session) and prefetch buffers, define handles which are associated with statements. 

This memory of remaining sessions in the pool after worker threads completion shall be cleaned up only as part of session pool destroy.

**Comment by judith-ipac** [comment]
Hi, @sudarshan12s, I was just about to reply to your previous message when I saw your latest.  I did try disabling the statement cache using setStmtCacheSize().  For the sample code I posted here, that change reduced the number of un-freed pointers at the end of the select/fetch loop by about a factor of 5.  I don't have a way of recording the change in memory use for that example.  For our real-life application, that change did not noticably affect memory use, which still skyrocketed even with the statement cache disabled.

**Comment by sudarshan12s** [comment]
you mean for odpi real life application and not similar OCCI application?

Thanks

**Comment by judith-ipac** [comment]
Thanks for the information about kinds of data whose associated memory is freed only when the session pool is destroyed.  Would the prefetch buffers be the ones that take up the most memory?  Could you please suggest other parameters that have different default values in ODPI and OCCI?

**Comment by judith-ipac** [comment]
About your latest question: the ODPI-based version of our real-life application uses much more memory than the OCCI-based one whether or not I disable the statement cache on the ODPI-based version.

**Comment by sudarshan12s** [comment]
Can you test with jemalloc library in your lab environment with odpi
application which shows high memory usage.

You can set LD_PRELOAD to the location where library is installed and run
the exe/application.
 ex: export LD_PRELOAD=$JEMALLOCDIR/libjemalloc.so.2  <odpi_application>

The above test was just to understand if there were fragmentation issues .


Thanks

**Comment by judith-ipac** [comment]
Thanks for the suggestion, @sudarshan12s, I will try that.  In the meantime, following another of your comments, I adjusted the values of fetchArraySize and prefetchRows, and so far that seems to be helping.  Thank you very much for your advice.

**Comment by judith-ipac** [comment]
Hello again. It seems that adjusting those two configuration settings has solved the problem.  Thank you!

**Comment by cjbj** [comment]
@judith-ipac how did you determine what values to set them to?  What was the sweet spot for memory use vs performance for you?
